// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package normalizersqlc

import (
	"context"
)

type Querier interface {
	ListPendingLearningInteractions(ctx context.Context, arg ListPendingLearningInteractionsParams) ([]ListPendingLearningInteractionsRow, error)
	ListPendingQuizEvents(ctx context.Context, arg ListPendingQuizEventsParams) ([]ListPendingQuizEventsRow, error)
}

var _ Querier = (*Queries)(nil)
