// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: raw_quiz_events.sql

package normalizersqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPendingQuizEvents = `-- name: ListPendingQuizEvents :many
select
  q.event_id,
  q.user_id,
  q.question_id,
  q.coarse_unit_id,
  q.video_id,
  q.recommendation_run_id,
  q.trigger_type,
  q.selected_option_ids,
  q.selection_interval_ms,
  q.is_first_try_correct,
  q.total_elapsed_ms,
  q.shown_at,
  q.completed_at
from analytics.quiz_events q
where ($1::uuid is null or q.user_id = $1::uuid)
  and ($2::timestamptz is null or q.completed_at < $2::timestamptz)
  and not exists (
    select 1
    from learning.unit_learning_events e
    where e.user_id = q.user_id
      and e.source_type = 'quiz_event'
      and e.source_ref_id = q.event_id::text
      and e.coarse_unit_id = q.coarse_unit_id
  )
order by q.completed_at asc, q.event_id asc
limit $3::int
`

type ListPendingQuizEventsParams struct {
	UserID         pgtype.UUID        `json:"user_id"`
	OccurredBefore pgtype.Timestamptz `json:"occurred_before"`
	LimitCount     int32              `json:"limit_count"`
}

type ListPendingQuizEventsRow struct {
	EventID             pgtype.UUID        `json:"event_id"`
	UserID              pgtype.UUID        `json:"user_id"`
	QuestionID          pgtype.UUID        `json:"question_id"`
	CoarseUnitID        int64              `json:"coarse_unit_id"`
	VideoID             pgtype.UUID        `json:"video_id"`
	RecommendationRunID pgtype.UUID        `json:"recommendation_run_id"`
	TriggerType         string             `json:"trigger_type"`
	SelectedOptionIds   []string           `json:"selected_option_ids"`
	SelectionIntervalMs []int32            `json:"selection_interval_ms"`
	IsFirstTryCorrect   bool               `json:"is_first_try_correct"`
	TotalElapsedMs      int32              `json:"total_elapsed_ms"`
	ShownAt             pgtype.Timestamptz `json:"shown_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) ListPendingQuizEvents(ctx context.Context, arg ListPendingQuizEventsParams) ([]ListPendingQuizEventsRow, error) {
	rows, err := q.db.Query(ctx, listPendingQuizEvents, arg.UserID, arg.OccurredBefore, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingQuizEventsRow{}
	for rows.Next() {
		var i ListPendingQuizEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.UserID,
			&i.QuestionID,
			&i.CoarseUnitID,
			&i.VideoID,
			&i.RecommendationRunID,
			&i.TriggerType,
			&i.SelectedOptionIds,
			&i.SelectionIntervalMs,
			&i.IsFirstTryCorrect,
			&i.TotalElapsedMs,
			&i.ShownAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
