// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package semanticsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SemanticCoarseUnit struct {
	ID              int64              `json:"id"`
	Kind            string             `json:"kind"`
	Label           string             `json:"label"`
	Lang            string             `json:"lang"`
	Pos             pgtype.Text        `json:"pos"`
	EnglishDef      pgtype.Text        `json:"english_def"`
	ChineseDef      pgtype.Text        `json:"chinese_def"`
	ChineseCriteria pgtype.Text        `json:"chinese_criteria"`
	ChineseLabel    pgtype.Text        `json:"chinese_label"`
	EnglishLabel    pgtype.Text        `json:"english_label"`
	Pattern         []byte             `json:"pattern"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Version         int32              `json:"version"`
	FineUnitIds     []int64            `json:"fine_unit_ids"`
	OriginalDefs    []string           `json:"original_defs"`
}

type SemanticFineUnit struct {
	ID          int64              `json:"id"`
	Kind        string             `json:"kind"`
	Label       string             `json:"label"`
	Lang        string             `json:"lang"`
	Pos         pgtype.Text        `json:"pos"`
	Def         pgtype.Text        `json:"def"`
	Pattern     []byte             `json:"pattern"`
	Meta        []byte             `json:"meta"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ExternalKey pgtype.Text        `json:"external_key"`
}

type SemanticUnitCollection struct {
	CollectionID    pgtype.UUID        `json:"collection_id"`
	Slug            string             `json:"slug"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	Category        string             `json:"category"`
	Status          string             `json:"status"`
	CoarseUnitCount int32              `json:"coarse_unit_count"`
	WordUnitCount   int32              `json:"word_unit_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type SemanticUnitCollectionMember struct {
	CollectionID   pgtype.UUID        `json:"collection_id"`
	CoarseUnitID   int64              `json:"coarse_unit_id"`
	SortOrder      int32              `json:"sort_order"`
	TargetPriority pgtype.Numeric     `json:"target_priority"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
