// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package semanticsqlc

import (
	"context"
)

type Querier interface {
	ListActiveUnitCollections(ctx context.Context) ([]ListActiveUnitCollectionsRow, error)
}

var _ Querier = (*Queries)(nil)
