// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: unit_collections.sql

package semanticsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listActiveUnitCollections = `-- name: ListActiveUnitCollections :many
select
  collection_id,
  slug,
  name,
  description,
  category,
  coarse_unit_count,
  word_unit_count
from semantic.unit_collections
where status = 'active'
order by category asc, name asc, slug asc
`

type ListActiveUnitCollectionsRow struct {
	CollectionID    pgtype.UUID `json:"collection_id"`
	Slug            string      `json:"slug"`
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	Category        string      `json:"category"`
	CoarseUnitCount int32       `json:"coarse_unit_count"`
	WordUnitCount   int32       `json:"word_unit_count"`
}

func (q *Queries) ListActiveUnitCollections(ctx context.Context) ([]ListActiveUnitCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveUnitCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveUnitCollectionsRow{}
	for rows.Next() {
		var i ListActiveUnitCollectionsRow
		if err := rows.Scan(
			&i.CollectionID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.CoarseUnitCount,
			&i.WordUnitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
