// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package analyticssqlc

import (
	"context"
)

type Querier interface {
	InsertLearningInteractionEvent(ctx context.Context, arg InsertLearningInteractionEventParams) (InsertLearningInteractionEventRow, error)
	InsertQuizEvent(ctx context.Context, arg InsertQuizEventParams) (InsertQuizEventRow, error)
}

var _ Querier = (*Queries)(nil)
