// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: raw_events.sql

package analyticssqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertLearningInteractionEvent = `-- name: InsertLearningInteractionEvent :one
insert into analytics.learning_interaction_events (
  client_event_id,
  user_id,
  client_context,
  event_type,
  source_surface,
  video_id,
  watch_session_id,
  recommendation_run_id,
  related_quiz_event_id,
  coarse_unit_id,
  token_text,
  sentence_index,
  span_index,
  occurred_at,
  exposure_start_ms,
  exposure_end_ms,
  exposure_count,
  lookup_visible_ms,
  lookup_sentence_audio_replay_count,
  lookup_word_audio_play_count,
  lookup_practice_now_clicked,
  event_payload
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $21,
  $22
)
on conflict (user_id, client_event_id) do update
set client_event_id = excluded.client_event_id
returning event_id, (xmax = 0) as inserted
`

type InsertLearningInteractionEventParams struct {
	ClientEventID                  string             `json:"client_event_id"`
	UserID                         pgtype.UUID        `json:"user_id"`
	ClientContext                  []byte             `json:"client_context"`
	EventType                      string             `json:"event_type"`
	SourceSurface                  string             `json:"source_surface"`
	VideoID                        pgtype.UUID        `json:"video_id"`
	WatchSessionID                 pgtype.UUID        `json:"watch_session_id"`
	RecommendationRunID            pgtype.UUID        `json:"recommendation_run_id"`
	RelatedQuizEventID             pgtype.UUID        `json:"related_quiz_event_id"`
	CoarseUnitID                   pgtype.Int8        `json:"coarse_unit_id"`
	TokenText                      pgtype.Text        `json:"token_text"`
	SentenceIndex                  pgtype.Int4        `json:"sentence_index"`
	SpanIndex                      pgtype.Int4        `json:"span_index"`
	OccurredAt                     pgtype.Timestamptz `json:"occurred_at"`
	ExposureStartMs                pgtype.Int4        `json:"exposure_start_ms"`
	ExposureEndMs                  pgtype.Int4        `json:"exposure_end_ms"`
	ExposureCount                  pgtype.Int4        `json:"exposure_count"`
	LookupVisibleMs                pgtype.Int4        `json:"lookup_visible_ms"`
	LookupSentenceAudioReplayCount int32              `json:"lookup_sentence_audio_replay_count"`
	LookupWordAudioPlayCount       int32              `json:"lookup_word_audio_play_count"`
	LookupPracticeNowClicked       bool               `json:"lookup_practice_now_clicked"`
	EventPayload                   []byte             `json:"event_payload"`
}

type InsertLearningInteractionEventRow struct {
	EventID  pgtype.UUID `json:"event_id"`
	Inserted bool        `json:"inserted"`
}

func (q *Queries) InsertLearningInteractionEvent(ctx context.Context, arg InsertLearningInteractionEventParams) (InsertLearningInteractionEventRow, error) {
	row := q.db.QueryRow(ctx, insertLearningInteractionEvent,
		arg.ClientEventID,
		arg.UserID,
		arg.ClientContext,
		arg.EventType,
		arg.SourceSurface,
		arg.VideoID,
		arg.WatchSessionID,
		arg.RecommendationRunID,
		arg.RelatedQuizEventID,
		arg.CoarseUnitID,
		arg.TokenText,
		arg.SentenceIndex,
		arg.SpanIndex,
		arg.OccurredAt,
		arg.ExposureStartMs,
		arg.ExposureEndMs,
		arg.ExposureCount,
		arg.LookupVisibleMs,
		arg.LookupSentenceAudioReplayCount,
		arg.LookupWordAudioPlayCount,
		arg.LookupPracticeNowClicked,
		arg.EventPayload,
	)
	var i InsertLearningInteractionEventRow
	err := row.Scan(&i.EventID, &i.Inserted)
	return i, err
}

const insertQuizEvent = `-- name: InsertQuizEvent :one
insert into analytics.quiz_events (
  client_event_id,
  user_id,
  client_context,
  question_id,
  coarse_unit_id,
  video_id,
  recommendation_run_id,
  trigger_type,
  selected_option_ids,
  selection_interval_ms,
  is_first_try_correct,
  total_elapsed_ms,
  shown_at,
  completed_at
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14
)
on conflict (user_id, client_event_id) do update
set client_event_id = excluded.client_event_id
returning event_id, (xmax = 0) as inserted
`

type InsertQuizEventParams struct {
	ClientEventID       string             `json:"client_event_id"`
	UserID              pgtype.UUID        `json:"user_id"`
	ClientContext       []byte             `json:"client_context"`
	QuestionID          pgtype.UUID        `json:"question_id"`
	CoarseUnitID        int64              `json:"coarse_unit_id"`
	VideoID             pgtype.UUID        `json:"video_id"`
	RecommendationRunID pgtype.UUID        `json:"recommendation_run_id"`
	TriggerType         string             `json:"trigger_type"`
	SelectedOptionIds   []string           `json:"selected_option_ids"`
	SelectionIntervalMs []int32            `json:"selection_interval_ms"`
	IsFirstTryCorrect   bool               `json:"is_first_try_correct"`
	TotalElapsedMs      int32              `json:"total_elapsed_ms"`
	ShownAt             pgtype.Timestamptz `json:"shown_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
}

type InsertQuizEventRow struct {
	EventID  pgtype.UUID `json:"event_id"`
	Inserted bool        `json:"inserted"`
}

func (q *Queries) InsertQuizEvent(ctx context.Context, arg InsertQuizEventParams) (InsertQuizEventRow, error) {
	row := q.db.QueryRow(ctx, insertQuizEvent,
		arg.ClientEventID,
		arg.UserID,
		arg.ClientContext,
		arg.QuestionID,
		arg.CoarseUnitID,
		arg.VideoID,
		arg.RecommendationRunID,
		arg.TriggerType,
		arg.SelectedOptionIds,
		arg.SelectionIntervalMs,
		arg.IsFirstTryCorrect,
		arg.TotalElapsedMs,
		arg.ShownAt,
		arg.CompletedAt,
	)
	var i InsertQuizEventRow
	err := row.Scan(&i.EventID, &i.Inserted)
	return i, err
}
