// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: raw_events.sql

package analyticssqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertLearningInteractionEvent = `-- name: InsertLearningInteractionEvent :one
insert into analytics.learning_interaction_events (
  client_event_id,
  user_id,
  client_context,
  event_type,
  source_surface,
  video_id,
  watch_session_id,
  recommendation_run_id,
  related_quiz_event_id,
  coarse_unit_id,
  token_text,
  sentence_index,
  span_index,
  occurred_at,
  exposure_start_ms,
  exposure_end_ms,
  exposure_count,
  lookup_visible_ms,
  lookup_sentence_audio_replay_count,
  lookup_word_audio_play_count,
  lookup_practice_now_clicked,
  event_payload
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $21,
  $22
)
on conflict (user_id, client_event_id) do update
set client_event_id = excluded.client_event_id
returning event_id, (xmax = 0) as inserted
`

type InsertLearningInteractionEventParams struct {
	ClientEventID                  string             `json:"client_event_id"`
	UserID                         pgtype.UUID        `json:"user_id"`
	ClientContext                  []byte             `json:"client_context"`
	EventType                      string             `json:"event_type"`
	SourceSurface                  string             `json:"source_surface"`
	VideoID                        pgtype.UUID        `json:"video_id"`
	WatchSessionID                 pgtype.UUID        `json:"watch_session_id"`
	RecommendationRunID            pgtype.UUID        `json:"recommendation_run_id"`
	RelatedQuizEventID             pgtype.UUID        `json:"related_quiz_event_id"`
	CoarseUnitID                   pgtype.Int8        `json:"coarse_unit_id"`
	TokenText                      pgtype.Text        `json:"token_text"`
	SentenceIndex                  pgtype.Int4        `json:"sentence_index"`
	SpanIndex                      pgtype.Int4        `json:"span_index"`
	OccurredAt                     pgtype.Timestamptz `json:"occurred_at"`
	ExposureStartMs                pgtype.Int4        `json:"exposure_start_ms"`
	ExposureEndMs                  pgtype.Int4        `json:"exposure_end_ms"`
	ExposureCount                  pgtype.Int4        `json:"exposure_count"`
	LookupVisibleMs                pgtype.Int4        `json:"lookup_visible_ms"`
	LookupSentenceAudioReplayCount int32              `json:"lookup_sentence_audio_replay_count"`
	LookupWordAudioPlayCount       int32              `json:"lookup_word_audio_play_count"`
	LookupPracticeNowClicked       bool               `json:"lookup_practice_now_clicked"`
	EventPayload                   []byte             `json:"event_payload"`
}

type InsertLearningInteractionEventRow struct {
	EventID  pgtype.UUID `json:"event_id"`
	Inserted bool        `json:"inserted"`
}

func (q *Queries) InsertLearningInteractionEvent(ctx context.Context, arg InsertLearningInteractionEventParams) (InsertLearningInteractionEventRow, error) {
	row := q.db.QueryRow(ctx, insertLearningInteractionEvent,
		arg.ClientEventID,
		arg.UserID,
		arg.ClientContext,
		arg.EventType,
		arg.SourceSurface,
		arg.VideoID,
		arg.WatchSessionID,
		arg.RecommendationRunID,
		arg.RelatedQuizEventID,
		arg.CoarseUnitID,
		arg.TokenText,
		arg.SentenceIndex,
		arg.SpanIndex,
		arg.OccurredAt,
		arg.ExposureStartMs,
		arg.ExposureEndMs,
		arg.ExposureCount,
		arg.LookupVisibleMs,
		arg.LookupSentenceAudioReplayCount,
		arg.LookupWordAudioPlayCount,
		arg.LookupPracticeNowClicked,
		arg.EventPayload,
	)
	var i InsertLearningInteractionEventRow
	err := row.Scan(&i.EventID, &i.Inserted)
	return i, err
}

const insertLearningInteractionEvents = `-- name: InsertLearningInteractionEvents :many
with input as (
  select
    ordinality::integer as input_index,
    item->>'client_event_id' as client_event_id,
    (item->>'user_id')::uuid as user_id,
    coalesce(item->'client_context', '{}'::jsonb) as client_context,
    item->>'event_type' as event_type,
    item->>'source_surface' as source_surface,
    case when nullif(item->>'video_id', '') is null then null else (item->>'video_id')::uuid end as video_id,
    case when nullif(item->>'watch_session_id', '') is null then null else (item->>'watch_session_id')::uuid end as watch_session_id,
    case when nullif(item->>'recommendation_run_id', '') is null then null else (item->>'recommendation_run_id')::uuid end as recommendation_run_id,
    case when nullif(item->>'related_quiz_event_id', '') is null then null else (item->>'related_quiz_event_id')::uuid end as related_quiz_event_id,
    case when nullif(item->>'coarse_unit_id', '') is null then null else (item->>'coarse_unit_id')::bigint end as coarse_unit_id,
    nullif(item->>'token_text', '') as token_text,
    case when nullif(item->>'sentence_index', '') is null then null else (item->>'sentence_index')::integer end as sentence_index,
    case when nullif(item->>'span_index', '') is null then null else (item->>'span_index')::integer end as span_index,
    (item->>'occurred_at')::timestamptz as occurred_at,
    case when nullif(item->>'exposure_start_ms', '') is null then null else (item->>'exposure_start_ms')::integer end as exposure_start_ms,
    case when nullif(item->>'exposure_end_ms', '') is null then null else (item->>'exposure_end_ms')::integer end as exposure_end_ms,
    case when nullif(item->>'exposure_count', '') is null then null else (item->>'exposure_count')::integer end as exposure_count,
    case when nullif(item->>'lookup_visible_ms', '') is null then null else (item->>'lookup_visible_ms')::integer end as lookup_visible_ms,
    coalesce((item->>'lookup_sentence_audio_replay_count')::integer, 0) as lookup_sentence_audio_replay_count,
    coalesce((item->>'lookup_word_audio_play_count')::integer, 0) as lookup_word_audio_play_count,
    coalesce((item->>'lookup_practice_now_clicked')::boolean, false) as lookup_practice_now_clicked,
    coalesce(item->'event_payload', '{}'::jsonb) as event_payload
  from jsonb_array_elements($1::jsonb) with ordinality as events(item, ordinality)
),
upserted as (
  insert into analytics.learning_interaction_events (
    client_event_id,
    user_id,
    client_context,
    event_type,
    source_surface,
    video_id,
    watch_session_id,
    recommendation_run_id,
    related_quiz_event_id,
    coarse_unit_id,
    token_text,
    sentence_index,
    span_index,
    occurred_at,
    exposure_start_ms,
    exposure_end_ms,
    exposure_count,
    lookup_visible_ms,
    lookup_sentence_audio_replay_count,
    lookup_word_audio_play_count,
    lookup_practice_now_clicked,
    event_payload
  )
  select
    client_event_id,
    user_id,
    client_context,
    event_type,
    source_surface,
    video_id,
    watch_session_id,
    recommendation_run_id,
    related_quiz_event_id,
    coarse_unit_id,
    token_text,
    sentence_index,
    span_index,
    occurred_at,
    exposure_start_ms,
    exposure_end_ms,
    exposure_count,
    lookup_visible_ms,
    lookup_sentence_audio_replay_count,
    lookup_word_audio_play_count,
    lookup_practice_now_clicked,
    event_payload
  from input
  on conflict (user_id, client_event_id) do update
  set client_event_id = excluded.client_event_id
  returning user_id, client_event_id, event_id, (xmax = 0) as inserted
)
select input.client_event_id::text as client_event_id, upserted.event_id, upserted.inserted
from input
join upserted
  on upserted.user_id = input.user_id
 and upserted.client_event_id = input.client_event_id
order by input.input_index
`

type InsertLearningInteractionEventsRow struct {
	ClientEventID string      `json:"client_event_id"`
	EventID       pgtype.UUID `json:"event_id"`
	Inserted      bool        `json:"inserted"`
}

func (q *Queries) InsertLearningInteractionEvents(ctx context.Context, events []byte) ([]InsertLearningInteractionEventsRow, error) {
	rows, err := q.db.Query(ctx, insertLearningInteractionEvents, events)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InsertLearningInteractionEventsRow{}
	for rows.Next() {
		var i InsertLearningInteractionEventsRow
		if err := rows.Scan(&i.ClientEventID, &i.EventID, &i.Inserted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertQuizEvent = `-- name: InsertQuizEvent :one
insert into analytics.quiz_events (
  client_event_id,
  user_id,
  client_context,
  question_id,
  coarse_unit_id,
  video_id,
  recommendation_run_id,
  trigger_type,
  selected_option_ids,
  selection_interval_ms,
  is_first_try_correct,
  total_elapsed_ms,
  shown_at,
  completed_at
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14
)
on conflict (user_id, client_event_id) do update
set client_event_id = excluded.client_event_id
returning event_id, (xmax = 0) as inserted
`

type InsertQuizEventParams struct {
	ClientEventID       string             `json:"client_event_id"`
	UserID              pgtype.UUID        `json:"user_id"`
	ClientContext       []byte             `json:"client_context"`
	QuestionID          pgtype.UUID        `json:"question_id"`
	CoarseUnitID        int64              `json:"coarse_unit_id"`
	VideoID             pgtype.UUID        `json:"video_id"`
	RecommendationRunID pgtype.UUID        `json:"recommendation_run_id"`
	TriggerType         string             `json:"trigger_type"`
	SelectedOptionIds   []string           `json:"selected_option_ids"`
	SelectionIntervalMs []int32            `json:"selection_interval_ms"`
	IsFirstTryCorrect   bool               `json:"is_first_try_correct"`
	TotalElapsedMs      int32              `json:"total_elapsed_ms"`
	ShownAt             pgtype.Timestamptz `json:"shown_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
}

type InsertQuizEventRow struct {
	EventID  pgtype.UUID `json:"event_id"`
	Inserted bool        `json:"inserted"`
}

func (q *Queries) InsertQuizEvent(ctx context.Context, arg InsertQuizEventParams) (InsertQuizEventRow, error) {
	row := q.db.QueryRow(ctx, insertQuizEvent,
		arg.ClientEventID,
		arg.UserID,
		arg.ClientContext,
		arg.QuestionID,
		arg.CoarseUnitID,
		arg.VideoID,
		arg.RecommendationRunID,
		arg.TriggerType,
		arg.SelectedOptionIds,
		arg.SelectionIntervalMs,
		arg.IsFirstTryCorrect,
		arg.TotalElapsedMs,
		arg.ShownAt,
		arg.CompletedAt,
	)
	var i InsertQuizEventRow
	err := row.Scan(&i.EventID, &i.Inserted)
	return i, err
}
