create schema if not exists learning;

create table if not exists learning.user_unit_states (
  user_id uuid not null references auth.users(id) on delete cascade,
  coarse_unit_id bigint not null references semantic.coarse_unit(id) on delete cascade,

  is_target boolean not null default false,
  target_source text,
  target_source_ref_id text,
  target_priority numeric(8,4) not null default 0,

  status text not null default 'new'
    check (status in ('new', 'learning', 'reviewing', 'mastered')),

  progress_percent numeric(5,2) not null default 0
    check (progress_percent between 0 and 100),

  mastery_score numeric(5,4) not null default 0
    check (mastery_score between 0 and 1),

  first_observed_at timestamptz,
  last_observed_at timestamptz,
  observation_count integer not null default 0,

  progress_event_count integer not null default 0,
  last_progress_at timestamptz,
  last_progress_quality smallint check (last_progress_quality between 0 and 5),
  recent_progress_qualities smallint[] not null default '{}',
  recent_progress_passes boolean[] not null default '{}',
  progress_success_count integer not null default 0,
  progress_failure_count integer not null default 0,
  consecutive_success_count integer not null default 0,
  consecutive_failure_count integer not null default 0,

  schedule_repetition integer not null default 0,
  schedule_interval_days numeric(8,2) not null default 0,
  schedule_ease_factor numeric(6,4) not null default 2.5
    check (schedule_ease_factor >= 1.3),
  next_review_at timestamptz,

  latest_learning_event_occurred_at timestamptz,
  latest_reset_boundary_at timestamptz,
  latest_learning_event_ledger_seq bigint not null default 0
    check (latest_learning_event_ledger_seq >= 0),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  primary key (user_id, coarse_unit_id)
);

create table if not exists learning.unit_learning_events (
  event_id uuid primary key default gen_random_uuid(),
  ledger_seq bigint generated by default as identity,
  user_id uuid not null references auth.users(id) on delete cascade,
  coarse_unit_id bigint not null references semantic.coarse_unit(id) on delete cascade,
  video_id uuid references catalog.videos(video_id) on delete set null,

  event_type text not null,
  reducer_effect text not null,
  progress_quality smallint,

  source_type text not null,
  source_ref_id text not null,
  is_correct boolean,

  counts_toward_success_streak boolean not null default false,
  consumed_watch_session_ids uuid[] not null default '{}'::uuid[],

  metadata jsonb not null default '{}'::jsonb
    check (jsonb_typeof(metadata) = 'object'),
  occurred_at timestamptz not null,
  reset_boundary_at timestamptz,
  created_at timestamptz not null default now(),

  constraint chk_unit_learning_events_event_type
    check (event_type in ('exposure', 'lookup', 'quiz', 'self_mark_mastered', 'reset_unlearned')),
  constraint chk_unit_learning_events_reducer_effect
    check (reducer_effect in ('observe_only', 'affects_progress', 'set_mastered', 'reset_unlearned')),
  constraint chk_unit_learning_events_progress_quality
    check (
      (reducer_effect = 'affects_progress' and progress_quality between 0 and 5)
      or
      (reducer_effect = 'observe_only' and progress_quality is null)
      or
      (reducer_effect = 'set_mastered' and progress_quality is null)
      or
      (reducer_effect = 'reset_unlearned' and progress_quality is null)
    ),
  constraint chk_unit_learning_events_set_mastered_event_type
    check (
      reducer_effect <> 'set_mastered'
      or event_type = 'self_mark_mastered'
    ),
  constraint chk_unit_learning_events_reset_unlearned_event_type
    check (
      reducer_effect <> 'reset_unlearned'
      or event_type = 'reset_unlearned'
    ),
  constraint chk_unit_learning_events_reset_boundary
    check (
      (
        reducer_effect = 'reset_unlearned'
        and event_type = 'reset_unlearned'
        and reset_boundary_at is not null
      )
      or
      (
        reducer_effect <> 'reset_unlearned'
        and reset_boundary_at is null
      )
    ),
  constraint chk_unit_learning_events_success_streak_effect
    check (
      reducer_effect = 'affects_progress'
      or counts_toward_success_streak = false
    ),
  constraint chk_unit_learning_events_exposure_session3_consumed_sessions
    check (
      (
        source_type = 'exposure_session3_v1'
        and event_type = 'exposure'
        and reducer_effect = 'affects_progress'
        and progress_quality = 4
        and counts_toward_success_streak = false
        and cardinality(consumed_watch_session_ids) = 3
        and array_position(consumed_watch_session_ids, null) is null
      )
      or
      (
        source_type <> 'exposure_session3_v1'
        and cardinality(consumed_watch_session_ids) = 0
      )
    ),
  constraint uq_unit_learning_events_source_unit
    unique (user_id, source_type, source_ref_id, coarse_unit_id)
);

create index if not exists idx_learning_states_user_target_status_due
on learning.user_unit_states (user_id, is_target, status, next_review_at);

create index if not exists idx_learning_states_user_updated_at
on learning.user_unit_states (user_id, updated_at desc);

create index if not exists idx_user_unit_states_active_unit_ids
on learning.user_unit_states (user_id, coarse_unit_id)
where is_target = true
  and status in ('new', 'learning', 'reviewing');

create index if not exists idx_user_unit_states_unmastered_progress
on learning.user_unit_states (user_id, progress_percent desc, coarse_unit_id)
where is_target = true
  and status in ('new', 'learning', 'reviewing');

create index if not exists idx_user_unit_states_mastered_progress
on learning.user_unit_states (user_id, coarse_unit_id)
where status = 'mastered';

create index if not exists idx_user_unit_states_active_collection_targets
on learning.user_unit_states (user_id, target_source, coarse_unit_id)
where is_target = true;

create unique index if not exists uq_unit_learning_events_ledger_seq
on learning.unit_learning_events (ledger_seq);

create index if not exists idx_learning_events_user_ledger_seq
on learning.unit_learning_events (user_id, ledger_seq);

create index if not exists idx_learning_events_user_unit_ledger_seq
on learning.unit_learning_events (user_id, coarse_unit_id, ledger_seq);

create index if not exists idx_learning_events_reset_boundary
on learning.unit_learning_events (user_id, coarse_unit_id, reset_boundary_at desc, ledger_seq desc)
where source_type = 'learning_unit_reset'
  and event_type = 'reset_unlearned'
  and reducer_effect = 'reset_unlearned'
  and reset_boundary_at is not null;

create unique index if not exists uq_unit_learning_events_reset_client_event
on learning.unit_learning_events (user_id, source_type, source_ref_id)
where source_type = 'learning_unit_reset';

create table if not exists learning.user_learning_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  active_collection_id uuid not null references semantic.unit_collections(collection_id),
  active_collection_slug text not null
    constraint user_learning_profiles_active_collection_slug_canonical_check
    check (active_collection_slug = lower(active_collection_slug) and active_collection_slug ~ '^[a-z0-9][a-z0-9-]{0,80}$'),
  active_collection_activated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_user_unit_states_active_target_priority
on learning.user_unit_states (
  user_id,
  target_priority desc,
  coarse_unit_id
)
where is_target = true
  and status in ('new', 'learning', 'reviewing');

create index if not exists idx_user_unit_states_mastered_target
on learning.user_unit_states (
  user_id,
  coarse_unit_id
)
where is_target = true
  and status = 'mastered';
