// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: end_quiz.sql

package catalogsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const hasVisibleVideoForEndQuiz = `-- name: HasVisibleVideoForEndQuiz :one
select exists (
  select 1
  from catalog.videos v
  where v.video_id = $1::uuid
    and v.status = 'active'
    and v.visibility_status = 'public'
    and (v.publish_at is null or v.publish_at <= now())
)::boolean
`

func (q *Queries) HasVisibleVideoForEndQuiz(ctx context.Context, videoID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasVisibleVideoForEndQuiz, videoID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listUnitQuizQuestionCandidates = `-- name: ListUnitQuizQuestionCandidates :many
select
  q.question_id,
  q.scope_type,
  q.question_type,
  q.coarse_unit_id,
  q.target_text,
  q.context_sentence_index,
  q.context_span_index,
  q.context_start_ms,
  q.context_end_ms,
  q.content_payload
from catalog.questions q
where q.video_id is null
  and q.coarse_unit_id = any($1::bigint[])
  and q.scope_type = 'unit'
  and q.status = 'active'
order by q.coarse_unit_id, q.created_at desc, q.question_id
`

type ListUnitQuizQuestionCandidatesRow struct {
	QuestionID           pgtype.UUID `json:"question_id"`
	ScopeType            string      `json:"scope_type"`
	QuestionType         string      `json:"question_type"`
	CoarseUnitID         int64       `json:"coarse_unit_id"`
	TargetText           string      `json:"target_text"`
	ContextSentenceIndex pgtype.Int4 `json:"context_sentence_index"`
	ContextSpanIndex     pgtype.Int4 `json:"context_span_index"`
	ContextStartMs       pgtype.Int4 `json:"context_start_ms"`
	ContextEndMs         pgtype.Int4 `json:"context_end_ms"`
	ContentPayload       []byte      `json:"content_payload"`
}

func (q *Queries) ListUnitQuizQuestionCandidates(ctx context.Context, coarseUnitIds []int64) ([]ListUnitQuizQuestionCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listUnitQuizQuestionCandidates, coarseUnitIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnitQuizQuestionCandidatesRow{}
	for rows.Next() {
		var i ListUnitQuizQuestionCandidatesRow
		if err := rows.Scan(
			&i.QuestionID,
			&i.ScopeType,
			&i.QuestionType,
			&i.CoarseUnitID,
			&i.TargetText,
			&i.ContextSentenceIndex,
			&i.ContextSpanIndex,
			&i.ContextStartMs,
			&i.ContextEndMs,
			&i.ContentPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideoUnitQuizQuestionCandidates = `-- name: ListVideoUnitQuizQuestionCandidates :many
select
  q.question_id,
  q.scope_type,
  q.question_type,
  q.coarse_unit_id,
  q.target_text,
  q.context_sentence_index,
  q.context_span_index,
  q.context_start_ms,
  q.context_end_ms,
  q.content_payload
from catalog.questions q
where q.video_id = $1::uuid
  and q.coarse_unit_id = any($2::bigint[])
  and q.scope_type = 'video_unit'
  and q.status = 'active'
order by q.coarse_unit_id, q.created_at desc, q.question_id
`

type ListVideoUnitQuizQuestionCandidatesParams struct {
	VideoID       pgtype.UUID `json:"video_id"`
	CoarseUnitIds []int64     `json:"coarse_unit_ids"`
}

type ListVideoUnitQuizQuestionCandidatesRow struct {
	QuestionID           pgtype.UUID `json:"question_id"`
	ScopeType            string      `json:"scope_type"`
	QuestionType         string      `json:"question_type"`
	CoarseUnitID         int64       `json:"coarse_unit_id"`
	TargetText           string      `json:"target_text"`
	ContextSentenceIndex pgtype.Int4 `json:"context_sentence_index"`
	ContextSpanIndex     pgtype.Int4 `json:"context_span_index"`
	ContextStartMs       pgtype.Int4 `json:"context_start_ms"`
	ContextEndMs         pgtype.Int4 `json:"context_end_ms"`
	ContentPayload       []byte      `json:"content_payload"`
}

func (q *Queries) ListVideoUnitQuizQuestionCandidates(ctx context.Context, arg ListVideoUnitQuizQuestionCandidatesParams) ([]ListVideoUnitQuizQuestionCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listVideoUnitQuizQuestionCandidates, arg.VideoID, arg.CoarseUnitIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVideoUnitQuizQuestionCandidatesRow{}
	for rows.Next() {
		var i ListVideoUnitQuizQuestionCandidatesRow
		if err := rows.Scan(
			&i.QuestionID,
			&i.ScopeType,
			&i.QuestionType,
			&i.CoarseUnitID,
			&i.TargetText,
			&i.ContextSentenceIndex,
			&i.ContextSpanIndex,
			&i.ContextStartMs,
			&i.ContextEndMs,
			&i.ContentPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
