// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_lookup.sql

package catalogsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getVideoDetailByID = `-- name: GetVideoDetailByID :one
select
  v.video_id,
  v.title,
  coalesce(v.description, '')::text as description,
  v.video_object_path,
  v.thumbnail_url,
  transcript.transcript_object_path,
  v.duration_ms,
  coalesce(s.view_count, 0)::bigint as view_count,
  coalesce(s.like_count, 0)::bigint as like_count,
  coalesce(s.favorite_count, 0)::bigint as favorite_count,
  coalesce(user_state.has_liked, false)::boolean as has_liked,
  coalesce(user_state.has_bookmarked, false)::boolean as has_favorited
from catalog.videos v
left join catalog.video_engagement_stats s on s.video_id = v.video_id
left join catalog.video_transcripts transcript on transcript.video_id = v.video_id
left join catalog.video_user_states user_state
  on user_state.user_id = $1::uuid
 and user_state.video_id = v.video_id
where v.video_id = $2::uuid
  and v.status = 'active'
  and v.visibility_status = 'public'
  and (v.publish_at is null or v.publish_at <= now())
`

type GetVideoDetailByIDParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	VideoID pgtype.UUID `json:"video_id"`
}

type GetVideoDetailByIDRow struct {
	VideoID              pgtype.UUID `json:"video_id"`
	Title                string      `json:"title"`
	Description          string      `json:"description"`
	VideoObjectPath      string      `json:"video_object_path"`
	ThumbnailUrl         pgtype.Text `json:"thumbnail_url"`
	TranscriptObjectPath pgtype.Text `json:"transcript_object_path"`
	DurationMs           int32       `json:"duration_ms"`
	ViewCount            int64       `json:"view_count"`
	LikeCount            int64       `json:"like_count"`
	FavoriteCount        int64       `json:"favorite_count"`
	HasLiked             bool        `json:"has_liked"`
	HasFavorited         bool        `json:"has_favorited"`
}

func (q *Queries) GetVideoDetailByID(ctx context.Context, arg GetVideoDetailByIDParams) (GetVideoDetailByIDRow, error) {
	row := q.db.QueryRow(ctx, getVideoDetailByID, arg.UserID, arg.VideoID)
	var i GetVideoDetailByIDRow
	err := row.Scan(
		&i.VideoID,
		&i.Title,
		&i.Description,
		&i.VideoObjectPath,
		&i.ThumbnailUrl,
		&i.TranscriptObjectPath,
		&i.DurationMs,
		&i.ViewCount,
		&i.LikeCount,
		&i.FavoriteCount,
		&i.HasLiked,
		&i.HasFavorited,
	)
	return i, err
}

const listFeedVideosByIDs = `-- name: ListFeedVideosByIDs :many
select
  v.video_id,
  v.title,
  v.thumbnail_url,
  coalesce(s.view_count, 0)::bigint as view_count
from catalog.videos v
left join catalog.video_engagement_stats s on s.video_id = v.video_id
where v.video_id = any($1::uuid[])
  and v.status = 'active'
  and v.visibility_status = 'public'
  and (v.publish_at is null or v.publish_at <= now())
order by v.video_id
`

type ListFeedVideosByIDsRow struct {
	VideoID      pgtype.UUID `json:"video_id"`
	Title        string      `json:"title"`
	ThumbnailUrl pgtype.Text `json:"thumbnail_url"`
	ViewCount    int64       `json:"view_count"`
}

func (q *Queries) ListFeedVideosByIDs(ctx context.Context, videoIds []pgtype.UUID) ([]ListFeedVideosByIDsRow, error) {
	rows, err := q.db.Query(ctx, listFeedVideosByIDs, videoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedVideosByIDsRow{}
	for rows.Next() {
		var i ListFeedVideosByIDsRow
		if err := rows.Scan(
			&i.VideoID,
			&i.Title,
			&i.ThumbnailUrl,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitLabelsByIDs = `-- name: ListUnitLabelsByIDs :many
select
  id,
  label
from semantic.coarse_unit
where id = any($1::bigint[])
  and status = 'active'
order by id
`

type ListUnitLabelsByIDsRow struct {
	ID    int64  `json:"id"`
	Label string `json:"label"`
}

func (q *Queries) ListUnitLabelsByIDs(ctx context.Context, coarseUnitIds []int64) ([]ListUnitLabelsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listUnitLabelsByIDs, coarseUnitIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnitLabelsByIDsRow{}
	for rows.Next() {
		var i ListUnitLabelsByIDsRow
		if err := rows.Scan(&i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
