// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package catalogsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AnalyticsVideoWatchEvent struct {
	WatchEventID        pgtype.UUID        `json:"watch_event_id"`
	WatchSessionID      pgtype.UUID        `json:"watch_session_id"`
	UserID              pgtype.UUID        `json:"user_id"`
	VideoID             pgtype.UUID        `json:"video_id"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	LastSeenAt          pgtype.Timestamptz `json:"last_seen_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
	LastPositionMs      int32              `json:"last_position_ms"`
	MaxPositionMs       int32              `json:"max_position_ms"`
	ActiveWatchMs       int64              `json:"active_watch_ms"`
	IsCompleted         bool               `json:"is_completed"`
	ProgressReportCount int32              `json:"progress_report_count"`
	ClientContext       []byte             `json:"client_context"`
	Metadata            []byte             `json:"metadata"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type AuthUser struct {
	ID               pgtype.UUID        `json:"id"`
	Email            pgtype.Text        `json:"email"`
	EmailConfirmedAt pgtype.Timestamptz `json:"email_confirmed_at"`
}

type CatalogQuestion struct {
	QuestionID           pgtype.UUID        `json:"question_id"`
	ScopeType            string             `json:"scope_type"`
	QuestionType         string             `json:"question_type"`
	CoarseUnitID         int64              `json:"coarse_unit_id"`
	TargetText           string             `json:"target_text"`
	VideoID              pgtype.UUID        `json:"video_id"`
	ContextSentenceIndex pgtype.Int4        `json:"context_sentence_index"`
	ContextSpanIndex     pgtype.Int4        `json:"context_span_index"`
	ContextStartMs       pgtype.Int4        `json:"context_start_ms"`
	ContextEndMs         pgtype.Int4        `json:"context_end_ms"`
	ContentPayload       []byte             `json:"content_payload"`
	Status               string             `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type CatalogVideo struct {
	VideoID                  pgtype.UUID        `json:"video_id"`
	SourceClipKey            string             `json:"source_clip_key"`
	ParentVideoName          string             `json:"parent_video_name"`
	ParentVideoSlug          string             `json:"parent_video_slug"`
	ClipSeq                  pgtype.Int4        `json:"clip_seq"`
	SourceStartMs            pgtype.Int4        `json:"source_start_ms"`
	SourceEndMs              pgtype.Int4        `json:"source_end_ms"`
	SourceStartSentenceIndex pgtype.Int4        `json:"source_start_sentence_index"`
	SourceEndSentenceIndex   pgtype.Int4        `json:"source_end_sentence_index"`
	Title                    string             `json:"title"`
	Description              pgtype.Text        `json:"description"`
	ClipReason               pgtype.Text        `json:"clip_reason"`
	EngagementScore          []byte             `json:"engagement_score"`
	Language                 string             `json:"language"`
	DurationMs               int32              `json:"duration_ms"`
	VideoObjectPath          string             `json:"video_object_path"`
	ThumbnailUrl             pgtype.Text        `json:"thumbnail_url"`
	Status                   string             `json:"status"`
	VisibilityStatus         string             `json:"visibility_status"`
	PublishAt                pgtype.Timestamptz `json:"publish_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type CatalogVideoEngagementStat struct {
	VideoID        pgtype.UUID        `json:"video_id"`
	ViewCount      int64              `json:"view_count"`
	LikeCount      int64              `json:"like_count"`
	FavoriteCount  int64              `json:"favorite_count"`
	CompletedCount int64              `json:"completed_count"`
	TotalWatchMs   int64              `json:"total_watch_ms"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CatalogVideoIngestionRecord struct {
	IngestionRecordID pgtype.UUID        `json:"ingestion_record_id"`
	SourceClipKey     string             `json:"source_clip_key"`
	VideoID           pgtype.UUID        `json:"video_id"`
	SourceName        pgtype.Text        `json:"source_name"`
	Status            string             `json:"status"`
	WarningCodes      []string           `json:"warning_codes"`
	ErrorCode         pgtype.Text        `json:"error_code"`
	ErrorMessage      pgtype.Text        `json:"error_message"`
	Context           []byte             `json:"context"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type CatalogVideoSemanticSpan struct {
	VideoID       pgtype.UUID        `json:"video_id"`
	SentenceIndex int32              `json:"sentence_index"`
	SpanIndex     int32              `json:"span_index"`
	StartMs       int32              `json:"start_ms"`
	EndMs         int32              `json:"end_ms"`
	CoarseUnitID  pgtype.Int8        `json:"coarse_unit_id"`
	SurfaceText   string             `json:"surface_text"`
	Explanation   pgtype.Text        `json:"explanation"`
	BaseForm      pgtype.Text        `json:"base_form"`
	Translation   pgtype.Text        `json:"translation"`
	Dictionary    pgtype.Text        `json:"dictionary"`
	MappingReason pgtype.Text        `json:"mapping_reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type CatalogVideoTranscript struct {
	VideoID                 pgtype.UUID        `json:"video_id"`
	TranscriptObjectPath    string             `json:"transcript_object_path"`
	TranscriptChecksum      string             `json:"transcript_checksum"`
	TranscriptFormatVersion int32              `json:"transcript_format_version"`
	SentenceCount           int32              `json:"sentence_count"`
	SemanticSpanCount       int32              `json:"semantic_span_count"`
	MappedSpanCount         int32              `json:"mapped_span_count"`
	UnmappedSpanCount       int32              `json:"unmapped_span_count"`
	MappedSpanRatio         pgtype.Numeric     `json:"mapped_span_ratio"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type CatalogVideoTranscriptSentence struct {
	VideoID       pgtype.UUID        `json:"video_id"`
	SentenceIndex int32              `json:"sentence_index"`
	StartMs       int32              `json:"start_ms"`
	EndMs         int32              `json:"end_ms"`
	Text          string             `json:"text"`
	Translation   pgtype.Text        `json:"translation"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type CatalogVideoUnitIndex struct {
	VideoID                          pgtype.UUID        `json:"video_id"`
	CoarseUnitID                     int64              `json:"coarse_unit_id"`
	MentionCount                     int32              `json:"mention_count"`
	SentenceCount                    int32              `json:"sentence_count"`
	CoverageMs                       int32              `json:"coverage_ms"`
	CoverageRatio                    pgtype.Numeric     `json:"coverage_ratio"`
	SentenceIndexes                  []int32            `json:"sentence_indexes"`
	BestEvidenceSentenceIndex        int32              `json:"best_evidence_sentence_index"`
	BestEvidenceSpanIndex            int32              `json:"best_evidence_span_index"`
	BestEvidenceScores               []byte             `json:"best_evidence_scores"`
	BestEvidenceQuestionRejectReason pgtype.Text        `json:"best_evidence_question_reject_reason"`
	BestEvidenceSelectionReason      pgtype.Text        `json:"best_evidence_selection_reason"`
	BestEvidenceCandidateScore       pgtype.Numeric     `json:"best_evidence_candidate_score"`
	BestEvidenceTargetText           pgtype.Text        `json:"best_evidence_target_text"`
	CreatedAt                        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                        pgtype.Timestamptz `json:"updated_at"`
	BestEvidenceStartMs              pgtype.Int4        `json:"best_evidence_start_ms"`
	BestEvidenceEndMs                pgtype.Int4        `json:"best_evidence_end_ms"`
}

type CatalogVideoUserState struct {
	UserID                 pgtype.UUID        `json:"user_id"`
	VideoID                pgtype.UUID        `json:"video_id"`
	HasLiked               bool               `json:"has_liked"`
	HasBookmarked          bool               `json:"has_bookmarked"`
	HasWatched             bool               `json:"has_watched"`
	LikedAt                pgtype.Timestamptz `json:"liked_at"`
	BookmarkedAt           pgtype.Timestamptz `json:"bookmarked_at"`
	LikeStateUpdatedAt     pgtype.Timestamptz `json:"like_state_updated_at"`
	FavoriteStateUpdatedAt pgtype.Timestamptz `json:"favorite_state_updated_at"`
	FirstWatchedAt         pgtype.Timestamptz `json:"first_watched_at"`
	LastWatchedAt          pgtype.Timestamptz `json:"last_watched_at"`
	WatchCount             int32              `json:"watch_count"`
	CompletedCount         int32              `json:"completed_count"`
	LastPositionMs         int32              `json:"last_position_ms"`
	MaxPositionMs          int32              `json:"max_position_ms"`
	TotalWatchMs           int64              `json:"total_watch_ms"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type CatalogWordFavorite struct {
	FavoriteID      pgtype.UUID        `json:"favorite_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	FavoriteKeyType string             `json:"favorite_key_type"`
	CoarseUnitID    pgtype.Int8        `json:"coarse_unit_id"`
	Source          string             `json:"source"`
	VideoID         pgtype.UUID        `json:"video_id"`
	SentenceIndex   pgtype.Int4        `json:"sentence_index"`
	TokenIndex      pgtype.Int4        `json:"token_index"`
	IsFavorited     bool               `json:"is_favorited"`
	FavoritedAt     pgtype.Timestamptz `json:"favorited_at"`
	StateUpdatedAt  pgtype.Timestamptz `json:"state_updated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type SemanticCoarseUnit struct {
	ID           int64       `json:"id"`
	Kind         string      `json:"kind"`
	Label        string      `json:"label"`
	Pos          pgtype.Text `json:"pos"`
	ChineseDef   pgtype.Text `json:"chinese_def"`
	ChineseLabel pgtype.Text `json:"chinese_label"`
	Status       string      `json:"status"`
}
