// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package catalogsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AnalyticsVideoWatchEvent struct {
	WatchSessionID      pgtype.UUID        `json:"watch_session_id"`
	UserID              pgtype.UUID        `json:"user_id"`
	VideoID             pgtype.UUID        `json:"video_id"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	LastSeenAt          pgtype.Timestamptz `json:"last_seen_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
	LastPositionMs      int32              `json:"last_position_ms"`
	MaxPositionMs       int32              `json:"max_position_ms"`
	ActiveWatchMs       int64              `json:"active_watch_ms"`
	IsCompleted         bool               `json:"is_completed"`
	ProgressReportCount int32              `json:"progress_report_count"`
	ClientContext       []byte             `json:"client_context"`
	Metadata            []byte             `json:"metadata"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type AuthUser struct {
	ID pgtype.UUID `json:"id"`
}

type CatalogQuestion struct {
	QuestionID           pgtype.UUID        `json:"question_id"`
	ScopeType            string             `json:"scope_type"`
	QuestionType         string             `json:"question_type"`
	CoarseUnitID         int64              `json:"coarse_unit_id"`
	TargetText           string             `json:"target_text"`
	VideoID              pgtype.UUID        `json:"video_id"`
	ContextSentenceIndex pgtype.Int4        `json:"context_sentence_index"`
	ContextSpanIndex     pgtype.Int4        `json:"context_span_index"`
	ContextStartMs       pgtype.Int4        `json:"context_start_ms"`
	ContextEndMs         pgtype.Int4        `json:"context_end_ms"`
	ContentPayload       []byte             `json:"content_payload"`
	Status               string             `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type CatalogVideo struct {
	VideoID               pgtype.UUID        `json:"video_id"`
	SourceClipKey         string             `json:"source_clip_key"`
	ParentVideoName       string             `json:"parent_video_name"`
	ParentVideoSlug       string             `json:"parent_video_slug"`
	ClipSeq               pgtype.Int4        `json:"clip_seq"`
	SourceStartMs         pgtype.Int4        `json:"source_start_ms"`
	SourceEndMs           pgtype.Int4        `json:"source_end_ms"`
	Title                 string             `json:"title"`
	Description           pgtype.Text        `json:"description"`
	ClipReason            pgtype.Text        `json:"clip_reason"`
	Language              string             `json:"language"`
	DurationMs            int32              `json:"duration_ms"`
	HlsMasterPlaylistPath string             `json:"hls_master_playlist_path"`
	ThumbnailUrl          pgtype.Text        `json:"thumbnail_url"`
	Status                string             `json:"status"`
	VisibilityStatus      string             `json:"visibility_status"`
	PublishAt             pgtype.Timestamptz `json:"publish_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type CatalogVideoEngagementStat struct {
	VideoID        pgtype.UUID        `json:"video_id"`
	ViewCount      int64              `json:"view_count"`
	LikeCount      int64              `json:"like_count"`
	FavoriteCount  int64              `json:"favorite_count"`
	CompletedCount int64              `json:"completed_count"`
	TotalWatchMs   int64              `json:"total_watch_ms"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CatalogVideoIngestionRecord struct {
	IngestionRecordID pgtype.UUID        `json:"ingestion_record_id"`
	SourceClipKey     string             `json:"source_clip_key"`
	VideoID           pgtype.UUID        `json:"video_id"`
	SourceName        pgtype.Text        `json:"source_name"`
	Status            string             `json:"status"`
	WarningCodes      []string           `json:"warning_codes"`
	ErrorCode         pgtype.Text        `json:"error_code"`
	ErrorMessage      pgtype.Text        `json:"error_message"`
	Context           []byte             `json:"context"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type CatalogVideoSemanticSpan struct {
	VideoID       pgtype.UUID        `json:"video_id"`
	SentenceIndex int32              `json:"sentence_index"`
	SpanIndex     int32              `json:"span_index"`
	StartMs       int32              `json:"start_ms"`
	EndMs         int32              `json:"end_ms"`
	CoarseUnitID  pgtype.Int8        `json:"coarse_unit_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type CatalogVideoTranscript struct {
	VideoID                 pgtype.UUID        `json:"video_id"`
	TranscriptObjectPath    string             `json:"transcript_object_path"`
	TranscriptChecksum      string             `json:"transcript_checksum"`
	TranscriptFormatVersion int32              `json:"transcript_format_version"`
	SentenceCount           int32              `json:"sentence_count"`
	SemanticSpanCount       int32              `json:"semantic_span_count"`
	MappedSpanCount         int32              `json:"mapped_span_count"`
	UnmappedSpanCount       int32              `json:"unmapped_span_count"`
	MappedSpanRatio         pgtype.Numeric     `json:"mapped_span_ratio"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type CatalogVideoTranscriptSentence struct {
	VideoID       pgtype.UUID        `json:"video_id"`
	SentenceIndex int32              `json:"sentence_index"`
	StartMs       int32              `json:"start_ms"`
	EndMs         int32              `json:"end_ms"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type CatalogVideoUnitIndex struct {
	VideoID                   pgtype.UUID        `json:"video_id"`
	CoarseUnitID              int64              `json:"coarse_unit_id"`
	MentionCount              int32              `json:"mention_count"`
	SentenceCount             int32              `json:"sentence_count"`
	FirstStartMs              int32              `json:"first_start_ms"`
	LastEndMs                 int32              `json:"last_end_ms"`
	CoverageMs                int32              `json:"coverage_ms"`
	CoverageRatio             pgtype.Numeric     `json:"coverage_ratio"`
	SentenceIndexes           []int32            `json:"sentence_indexes"`
	BestEvidenceSentenceIndex int32              `json:"best_evidence_sentence_index"`
	BestEvidenceSpanIndex     int32              `json:"best_evidence_span_index"`
	BestEvidenceSource        string             `json:"best_evidence_source"`
	BestEvidenceModel         pgtype.Text        `json:"best_evidence_model"`
	BestEvidenceVersion       int32              `json:"best_evidence_version"`
	BestEvidenceMetadata      []byte             `json:"best_evidence_metadata"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

type CatalogVideoUserState struct {
	UserID         pgtype.UUID        `json:"user_id"`
	VideoID        pgtype.UUID        `json:"video_id"`
	HasLiked       bool               `json:"has_liked"`
	HasBookmarked  bool               `json:"has_bookmarked"`
	HasWatched     bool               `json:"has_watched"`
	LikedAt        pgtype.Timestamptz `json:"liked_at"`
	BookmarkedAt   pgtype.Timestamptz `json:"bookmarked_at"`
	FirstWatchedAt pgtype.Timestamptz `json:"first_watched_at"`
	LastWatchedAt  pgtype.Timestamptz `json:"last_watched_at"`
	WatchCount     int32              `json:"watch_count"`
	CompletedCount int32              `json:"completed_count"`
	LastPositionMs int32              `json:"last_position_ms"`
	MaxPositionMs  int32              `json:"max_position_ms"`
	TotalWatchMs   int64              `json:"total_watch_ms"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type SemanticCoarseUnit struct {
	ID     int64  `json:"id"`
	Label  string `json:"label"`
	Status string `json:"status"`
}
