// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package catalogsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetVideoDurationMS(ctx context.Context, videoID pgtype.UUID) (int32, error)
	HasVisibleVideoForEndQuiz(ctx context.Context, videoID pgtype.UUID) (bool, error)
	ListFeedVideosByIDs(ctx context.Context, arg ListFeedVideosByIDsParams) ([]ListFeedVideosByIDsRow, error)
	ListUnitLabelsByIDs(ctx context.Context, coarseUnitIds []int64) ([]ListUnitLabelsByIDsRow, error)
	ListUnitQuizQuestionCandidates(ctx context.Context, coarseUnitIds []int64) ([]ListUnitQuizQuestionCandidatesRow, error)
	ListVideoUnitQuizQuestionCandidates(ctx context.Context, arg ListVideoUnitQuizQuestionCandidatesParams) ([]ListVideoUnitQuizQuestionCandidatesRow, error)
	SetVideoFavorited(ctx context.Context, arg SetVideoFavoritedParams) (SetVideoFavoritedRow, error)
	SetVideoLiked(ctx context.Context, arg SetVideoLikedParams) (SetVideoLikedRow, error)
	SetVideoUnfavorited(ctx context.Context, arg SetVideoUnfavoritedParams) (SetVideoUnfavoritedRow, error)
	SetVideoUnliked(ctx context.Context, arg SetVideoUnlikedParams) (SetVideoUnlikedRow, error)
	UpsertVideoEngagementStatsFromWatchProgress(ctx context.Context, arg UpsertVideoEngagementStatsFromWatchProgressParams) error
	UpsertVideoUserStateFromWatchProgress(ctx context.Context, arg UpsertVideoUserStateFromWatchProgressParams) error
	UpsertVideoWatchSession(ctx context.Context, arg UpsertVideoWatchSessionParams) (UpsertVideoWatchSessionRow, error)
}

var _ Querier = (*Queries)(nil)
