// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video_library.sql

package catalogsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listVideoFavorites = `-- name: ListVideoFavorites :many
select
  v.video_id,
  v.title,
  v.thumbnail_url,
  v.duration_ms,
  coalesce(s.view_count, 0)::bigint as view_count,
  state.bookmarked_at
from catalog.video_user_states state
join catalog.videos v on v.video_id = state.video_id
left join catalog.video_engagement_stats s on s.video_id = state.video_id
where state.user_id = $1::uuid
  and state.has_bookmarked = true
  and state.bookmarked_at is not null
  and v.status = 'active'
  and v.visibility_status = 'public'
  and (v.publish_at is null or v.publish_at <= now())
  and (
    not $2::boolean
    or state.bookmarked_at < $3::timestamptz
    or (
      state.bookmarked_at = $3::timestamptz
      and state.video_id > $4::uuid
    )
  )
order by state.bookmarked_at desc, state.video_id asc
limit $5::int
`

type ListVideoFavoritesParams struct {
	UserID        pgtype.UUID        `json:"user_id"`
	HasCursor     bool               `json:"has_cursor"`
	CursorAt      pgtype.Timestamptz `json:"cursor_at"`
	CursorVideoID pgtype.UUID        `json:"cursor_video_id"`
	LimitPlusOne  int32              `json:"limit_plus_one"`
}

type ListVideoFavoritesRow struct {
	VideoID      pgtype.UUID        `json:"video_id"`
	Title        string             `json:"title"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	DurationMs   int32              `json:"duration_ms"`
	ViewCount    int64              `json:"view_count"`
	BookmarkedAt pgtype.Timestamptz `json:"bookmarked_at"`
}

func (q *Queries) ListVideoFavorites(ctx context.Context, arg ListVideoFavoritesParams) ([]ListVideoFavoritesRow, error) {
	rows, err := q.db.Query(ctx, listVideoFavorites,
		arg.UserID,
		arg.HasCursor,
		arg.CursorAt,
		arg.CursorVideoID,
		arg.LimitPlusOne,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVideoFavoritesRow{}
	for rows.Next() {
		var i ListVideoFavoritesRow
		if err := rows.Scan(
			&i.VideoID,
			&i.Title,
			&i.ThumbnailUrl,
			&i.DurationMs,
			&i.ViewCount,
			&i.BookmarkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideoHistory = `-- name: ListVideoHistory :many
select
  v.video_id,
  v.title,
  v.thumbnail_url,
  v.duration_ms,
  coalesce(s.view_count, 0)::bigint as view_count,
  coalesce(state.last_position_ms, 0)::integer as last_position_ms,
  state.last_watched_at
from catalog.video_user_states state
join catalog.videos v on v.video_id = state.video_id
left join catalog.video_engagement_stats s on s.video_id = state.video_id
where state.user_id = $1::uuid
  and state.has_watched = true
  and state.last_watched_at is not null
  and v.status = 'active'
  and v.visibility_status = 'public'
  and (v.publish_at is null or v.publish_at <= now())
  and (
    not $2::boolean
    or state.last_watched_at < $3::timestamptz
    or (
      state.last_watched_at = $3::timestamptz
      and state.video_id > $4::uuid
    )
  )
order by state.last_watched_at desc, state.video_id asc
limit $5::int
`

type ListVideoHistoryParams struct {
	UserID        pgtype.UUID        `json:"user_id"`
	HasCursor     bool               `json:"has_cursor"`
	CursorAt      pgtype.Timestamptz `json:"cursor_at"`
	CursorVideoID pgtype.UUID        `json:"cursor_video_id"`
	LimitPlusOne  int32              `json:"limit_plus_one"`
}

type ListVideoHistoryRow struct {
	VideoID        pgtype.UUID        `json:"video_id"`
	Title          string             `json:"title"`
	ThumbnailUrl   pgtype.Text        `json:"thumbnail_url"`
	DurationMs     int32              `json:"duration_ms"`
	ViewCount      int64              `json:"view_count"`
	LastPositionMs int32              `json:"last_position_ms"`
	LastWatchedAt  pgtype.Timestamptz `json:"last_watched_at"`
}

func (q *Queries) ListVideoHistory(ctx context.Context, arg ListVideoHistoryParams) ([]ListVideoHistoryRow, error) {
	rows, err := q.db.Query(ctx, listVideoHistory,
		arg.UserID,
		arg.HasCursor,
		arg.CursorAt,
		arg.CursorVideoID,
		arg.LimitPlusOne,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVideoHistoryRow{}
	for rows.Next() {
		var i ListVideoHistoryRow
		if err := rows.Scan(
			&i.VideoID,
			&i.Title,
			&i.ThumbnailUrl,
			&i.DurationMs,
			&i.ViewCount,
			&i.LastPositionMs,
			&i.LastWatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
