// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video_watch_progress.sql

package catalogsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getVideoDurationMS = `-- name: GetVideoDurationMS :one
select duration_ms
from catalog.videos
where video_id = $1
`

func (q *Queries) GetVideoDurationMS(ctx context.Context, videoID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getVideoDurationMS, videoID)
	var duration_ms int32
	err := row.Scan(&duration_ms)
	return duration_ms, err
}

const upsertVideoEngagementStatsFromWatchProgress = `-- name: UpsertVideoEngagementStatsFromWatchProgress :exec
insert into catalog.video_engagement_stats (
  video_id,
  view_count,
  completed_count,
  total_watch_ms
) values (
  $1,
  case when $2::boolean then 1 else 0 end,
  case when $3::boolean then 1 else 0 end,
  $4
)
on conflict (video_id) do update set
  view_count = catalog.video_engagement_stats.view_count + case when $2::boolean then 1 else 0 end,
  completed_count = catalog.video_engagement_stats.completed_count + case when $3::boolean then 1 else 0 end,
  total_watch_ms = catalog.video_engagement_stats.total_watch_ms + $4,
  updated_at = now()
`

type UpsertVideoEngagementStatsFromWatchProgressParams struct {
	VideoID            pgtype.UUID `json:"video_id"`
	CreatedSession     bool        `json:"created_session"`
	CompletedSession   bool        `json:"completed_session"`
	DeltaActiveWatchMs int64       `json:"delta_active_watch_ms"`
}

func (q *Queries) UpsertVideoEngagementStatsFromWatchProgress(ctx context.Context, arg UpsertVideoEngagementStatsFromWatchProgressParams) error {
	_, err := q.db.Exec(ctx, upsertVideoEngagementStatsFromWatchProgress,
		arg.VideoID,
		arg.CreatedSession,
		arg.CompletedSession,
		arg.DeltaActiveWatchMs,
	)
	return err
}

const upsertVideoUserStateFromWatchProgress = `-- name: UpsertVideoUserStateFromWatchProgress :exec
insert into catalog.video_user_states (
  user_id,
  video_id,
  has_watched,
  first_watched_at,
  last_watched_at,
  watch_count,
  completed_count,
  last_position_ms,
  max_position_ms,
  total_watch_ms
) values (
  $1,
  $2,
  true,
  $3,
  $4,
  case when $5::boolean then 1 else 0 end,
  case when $6::boolean then 1 else 0 end,
  $7,
  $8,
  $9
)
on conflict (user_id, video_id) do update set
  has_watched = true,
  first_watched_at = coalesce(catalog.video_user_states.first_watched_at, excluded.first_watched_at),
  last_watched_at = greatest(
    coalesce(catalog.video_user_states.last_watched_at, excluded.last_watched_at),
    excluded.last_watched_at
  ),
  watch_count = catalog.video_user_states.watch_count + case when $5::boolean then 1 else 0 end,
  completed_count = catalog.video_user_states.completed_count + case when $6::boolean then 1 else 0 end,
  last_position_ms = case
    when catalog.video_user_states.last_watched_at is null
      or excluded.last_watched_at >= catalog.video_user_states.last_watched_at
    then excluded.last_position_ms
    else catalog.video_user_states.last_position_ms
  end,
  max_position_ms = greatest(catalog.video_user_states.max_position_ms, excluded.max_position_ms),
  total_watch_ms = catalog.video_user_states.total_watch_ms + $9,
  updated_at = now()
`

type UpsertVideoUserStateFromWatchProgressParams struct {
	UserID             pgtype.UUID        `json:"user_id"`
	VideoID            pgtype.UUID        `json:"video_id"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	LastSeenAt         pgtype.Timestamptz `json:"last_seen_at"`
	CreatedSession     bool               `json:"created_session"`
	CompletedSession   bool               `json:"completed_session"`
	LastPositionMs     int32              `json:"last_position_ms"`
	MaxPositionMs      int32              `json:"max_position_ms"`
	DeltaActiveWatchMs int64              `json:"delta_active_watch_ms"`
}

func (q *Queries) UpsertVideoUserStateFromWatchProgress(ctx context.Context, arg UpsertVideoUserStateFromWatchProgressParams) error {
	_, err := q.db.Exec(ctx, upsertVideoUserStateFromWatchProgress,
		arg.UserID,
		arg.VideoID,
		arg.StartedAt,
		arg.LastSeenAt,
		arg.CreatedSession,
		arg.CompletedSession,
		arg.LastPositionMs,
		arg.MaxPositionMs,
		arg.DeltaActiveWatchMs,
	)
	return err
}

const upsertVideoWatchSession = `-- name: UpsertVideoWatchSession :one
with input as (
  select
    $1::uuid as watch_session_id,
    $2::uuid as user_id,
    $3::uuid as video_id,
    $4::timestamptz as occurred_at,
    $5::integer as position_ms,
    $6::bigint as active_watch_ms,
    $7::integer as duration_ms,
    $8::jsonb as client_context,
    $9::jsonb as metadata
),
existing as (
  select e.watch_event_id, e.watch_session_id, e.user_id, e.video_id, e.started_at, e.last_seen_at, e.completed_at, e.last_position_ms, e.max_position_ms, e.active_watch_ms, e.is_completed, e.progress_report_count, e.client_context, e.metadata, e.created_at, e.updated_at
  from analytics.video_watch_events e
  join input i on i.watch_session_id = e.watch_session_id
   and i.user_id = e.user_id
  for update
),
computed_update as (
  select
    i.watch_session_id,
    i.user_id,
    i.video_id,
    i.occurred_at,
    i.position_ms,
    i.active_watch_ms,
    i.duration_ms,
    i.client_context,
    i.metadata,
    e.active_watch_ms as old_active_watch_ms,
    e.is_completed as old_is_completed,
    greatest(e.max_position_ms, i.position_ms) as new_max_position_ms,
    greatest(e.active_watch_ms, i.active_watch_ms) as new_active_watch_ms,
    (
      greatest(e.active_watch_ms, i.active_watch_ms) > 10000
      and i.duration_ms > 0
      and (greatest(e.max_position_ms, i.position_ms)::numeric / i.duration_ms::numeric) >= 0.9
    ) as computed_completed
  from input i
  join existing e
    on e.watch_session_id = i.watch_session_id
   and e.user_id = i.user_id
   and e.video_id = i.video_id
),
inserted as (
  insert into analytics.video_watch_events (
    watch_session_id,
    user_id,
    video_id,
    started_at,
    last_seen_at,
    completed_at,
    last_position_ms,
    max_position_ms,
    active_watch_ms,
    is_completed,
    progress_report_count,
    client_context,
    metadata
  )
  select
    i.watch_session_id,
    i.user_id,
    i.video_id,
    i.occurred_at,
    i.occurred_at,
    case
      when i.active_watch_ms > 10000
       and i.duration_ms > 0
       and (i.position_ms::numeric / i.duration_ms::numeric) >= 0.9
      then i.occurred_at
      else null
    end,
    i.position_ms,
    i.position_ms,
    i.active_watch_ms,
    (
      i.active_watch_ms > 10000
      and i.duration_ms > 0
      and (i.position_ms::numeric / i.duration_ms::numeric) >= 0.9
    ),
    1,
    i.client_context,
    i.metadata
  from input i
  where not exists (select 1 from existing)
  on conflict (user_id, watch_session_id) do nothing
  returning
    true::boolean as created_session,
    is_completed as completed_session,
    active_watch_ms as delta_active_watch_ms,
    started_at,
    last_seen_at,
    last_position_ms,
    max_position_ms,
    active_watch_ms,
    is_completed
),
updated as (
  update analytics.video_watch_events e
  set
    last_seen_at = greatest(e.last_seen_at, c.occurred_at),
    last_position_ms = case
      when c.occurred_at >= e.last_seen_at then c.position_ms
      else e.last_position_ms
    end,
    max_position_ms = c.new_max_position_ms,
    active_watch_ms = c.new_active_watch_ms,
    is_completed = e.is_completed or c.computed_completed,
    completed_at = coalesce(
      e.completed_at,
      case
        when not e.is_completed and c.computed_completed then c.occurred_at
        else null
      end
    ),
    progress_report_count = e.progress_report_count + 1,
    client_context = c.client_context,
    metadata = c.metadata,
    updated_at = now()
  from computed_update c
  where e.user_id = c.user_id
    and e.watch_session_id = c.watch_session_id
    and e.video_id = c.video_id
  returning
    false::boolean as created_session,
    (not c.old_is_completed and c.computed_completed)::boolean as completed_session,
    (c.new_active_watch_ms - c.old_active_watch_ms)::bigint as delta_active_watch_ms,
    e.started_at,
    e.last_seen_at,
    e.last_position_ms,
    e.max_position_ms,
    e.active_watch_ms,
    e.is_completed
)
select created_session, completed_session, delta_active_watch_ms, started_at, last_seen_at, last_position_ms, max_position_ms, active_watch_ms, is_completed
from inserted
union all
select created_session, completed_session, delta_active_watch_ms, started_at, last_seen_at, last_position_ms, max_position_ms, active_watch_ms, is_completed
from updated
limit 1
`

type UpsertVideoWatchSessionParams struct {
	WatchSessionID pgtype.UUID        `json:"watch_session_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	VideoID        pgtype.UUID        `json:"video_id"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	PositionMs     int32              `json:"position_ms"`
	ActiveWatchMs  int64              `json:"active_watch_ms"`
	DurationMs     int32              `json:"duration_ms"`
	ClientContext  []byte             `json:"client_context"`
	Metadata       []byte             `json:"metadata"`
}

type UpsertVideoWatchSessionRow struct {
	CreatedSession     bool               `json:"created_session"`
	CompletedSession   bool               `json:"completed_session"`
	DeltaActiveWatchMs int64              `json:"delta_active_watch_ms"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	LastSeenAt         pgtype.Timestamptz `json:"last_seen_at"`
	LastPositionMs     int32              `json:"last_position_ms"`
	MaxPositionMs      int32              `json:"max_position_ms"`
	ActiveWatchMs      int64              `json:"active_watch_ms"`
	IsCompleted        bool               `json:"is_completed"`
}

func (q *Queries) UpsertVideoWatchSession(ctx context.Context, arg UpsertVideoWatchSessionParams) (UpsertVideoWatchSessionRow, error) {
	row := q.db.QueryRow(ctx, upsertVideoWatchSession,
		arg.WatchSessionID,
		arg.UserID,
		arg.VideoID,
		arg.OccurredAt,
		arg.PositionMs,
		arg.ActiveWatchMs,
		arg.DurationMs,
		arg.ClientContext,
		arg.Metadata,
	)
	var i UpsertVideoWatchSessionRow
	err := row.Scan(
		&i.CreatedSession,
		&i.CompletedSession,
		&i.DeltaActiveWatchMs,
		&i.StartedAt,
		&i.LastSeenAt,
		&i.LastPositionMs,
		&i.MaxPositionMs,
		&i.ActiveWatchMs,
		&i.IsCompleted,
	)
	return i, err
}
