// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video_interactions.sql

package catalogsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const setVideoFavorited = `-- name: SetVideoFavorited :one
with input as (
  select
    $1::uuid as user_id,
    $2::uuid as video_id,
    $3::timestamptz as occurred_at
),
target_video as (
  select videos.video_id
  from catalog.videos
  join input on input.video_id = videos.video_id
  where videos.status = 'active'
    and videos.visibility_status = 'public'
    and (videos.publish_at is null or videos.publish_at <= now())
),
inserted_state as (
  insert into catalog.video_user_states (
    user_id,
    video_id,
    has_bookmarked,
    bookmarked_at,
    favorite_state_updated_at,
    updated_at
  )
  select
    input.user_id,
    target_video.video_id,
    true,
    input.occurred_at,
    input.occurred_at,
    now()
  from input
  join target_video on true
  on conflict (user_id, video_id) do nothing
  returning video_id
),
previous_state as (
  select
    state.video_id,
    state.has_bookmarked,
    state.favorite_state_updated_at
  from catalog.video_user_states state
  join input
    on input.user_id = state.user_id
   and input.video_id = state.video_id
  join target_video on target_video.video_id = state.video_id
  where not exists (select 1 from inserted_state)
  for update of state
),
accepted_update as (
  update catalog.video_user_states state
  set
    has_bookmarked = true,
    bookmarked_at = input.occurred_at,
    favorite_state_updated_at = input.occurred_at,
    updated_at = now()
  from input
  join previous_state previous on previous.video_id = input.video_id
  where state.user_id = input.user_id
    and state.video_id = input.video_id
    and coalesce(previous.favorite_state_updated_at, '-infinity'::timestamptz) <= input.occurred_at
  returning state.video_id
),
delta as (
  select (
    (select count(*) from inserted_state)
    + coalesce((
      select case
        when previous.has_bookmarked = false
         and coalesce(previous.favorite_state_updated_at, '-infinity'::timestamptz) <= input.occurred_at
        then 1
        else 0
      end
      from previous_state previous
      cross join input
    ), 0)
  )::bigint as value
),
upsert_stats as (
  insert into catalog.video_engagement_stats (
    video_id,
    favorite_count,
    updated_at
  )
  select
    target_video.video_id,
    delta.value,
    now()
  from target_video
  cross join delta
  on conflict (video_id) do update set
    favorite_count = catalog.video_engagement_stats.favorite_count + excluded.favorite_count,
    updated_at = case
      when excluded.favorite_count > 0 then now()
      else catalog.video_engagement_stats.updated_at
    end
  returning video_id, favorite_count
),
final_state as (
  select
    target_video.video_id,
    case
      when exists (select 1 from inserted_state) then true
      when exists (select 1 from accepted_update) then true
      else coalesce((select previous.has_bookmarked from previous_state previous), false)
    end as has_bookmarked
  from target_video
)
select
  target_video.video_id,
  coalesce(final_state.has_bookmarked, false)::boolean as has_favorited,
  coalesce(upsert_stats.favorite_count, stats.favorite_count, 0)::bigint as favorite_count
from target_video
left join final_state on final_state.video_id = target_video.video_id
left join upsert_stats on upsert_stats.video_id = target_video.video_id
left join catalog.video_engagement_stats stats on stats.video_id = target_video.video_id
`

type SetVideoFavoritedParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	VideoID    pgtype.UUID        `json:"video_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type SetVideoFavoritedRow struct {
	VideoID       pgtype.UUID `json:"video_id"`
	HasFavorited  bool        `json:"has_favorited"`
	FavoriteCount int64       `json:"favorite_count"`
}

func (q *Queries) SetVideoFavorited(ctx context.Context, arg SetVideoFavoritedParams) (SetVideoFavoritedRow, error) {
	row := q.db.QueryRow(ctx, setVideoFavorited, arg.UserID, arg.VideoID, arg.OccurredAt)
	var i SetVideoFavoritedRow
	err := row.Scan(&i.VideoID, &i.HasFavorited, &i.FavoriteCount)
	return i, err
}

const setVideoLiked = `-- name: SetVideoLiked :one
with input as (
  select
    $1::uuid as user_id,
    $2::uuid as video_id,
    $3::timestamptz as occurred_at
),
target_video as (
  select videos.video_id
  from catalog.videos
  join input on input.video_id = videos.video_id
  where videos.status = 'active'
    and videos.visibility_status = 'public'
    and (videos.publish_at is null or videos.publish_at <= now())
),
inserted_state as (
  insert into catalog.video_user_states (
    user_id,
    video_id,
    has_liked,
    liked_at,
    like_state_updated_at,
    updated_at
  )
  select
    input.user_id,
    target_video.video_id,
    true,
    input.occurred_at,
    input.occurred_at,
    now()
  from input
  join target_video on true
  on conflict (user_id, video_id) do nothing
  returning video_id
),
previous_state as (
  select
    state.video_id,
    state.has_liked,
    state.like_state_updated_at
  from catalog.video_user_states state
  join input
    on input.user_id = state.user_id
   and input.video_id = state.video_id
  join target_video on target_video.video_id = state.video_id
  where not exists (select 1 from inserted_state)
  for update of state
),
accepted_update as (
  update catalog.video_user_states state
  set
    has_liked = true,
    liked_at = input.occurred_at,
    like_state_updated_at = input.occurred_at,
    updated_at = now()
  from input
  join previous_state previous on previous.video_id = input.video_id
  where state.user_id = input.user_id
    and state.video_id = input.video_id
    and coalesce(previous.like_state_updated_at, '-infinity'::timestamptz) <= input.occurred_at
  returning state.video_id
),
delta as (
  select (
    (select count(*) from inserted_state)
    + coalesce((
      select case
        when previous.has_liked = false
         and coalesce(previous.like_state_updated_at, '-infinity'::timestamptz) <= input.occurred_at
        then 1
        else 0
      end
      from previous_state previous
      cross join input
    ), 0)
  )::bigint as value
),
upsert_stats as (
  insert into catalog.video_engagement_stats (
    video_id,
    like_count,
    updated_at
  )
  select
    target_video.video_id,
    delta.value,
    now()
  from target_video
  cross join delta
  on conflict (video_id) do update set
    like_count = catalog.video_engagement_stats.like_count + excluded.like_count,
    updated_at = case
      when excluded.like_count > 0 then now()
      else catalog.video_engagement_stats.updated_at
    end
  returning video_id, like_count
),
final_state as (
  select
    target_video.video_id,
    case
      when exists (select 1 from inserted_state) then true
      when exists (select 1 from accepted_update) then true
      else coalesce((select previous.has_liked from previous_state previous), false)
    end as has_liked
  from target_video
)
select
  target_video.video_id,
  coalesce(final_state.has_liked, false)::boolean as has_liked,
  coalesce(upsert_stats.like_count, stats.like_count, 0)::bigint as like_count
from target_video
left join final_state on final_state.video_id = target_video.video_id
left join upsert_stats on upsert_stats.video_id = target_video.video_id
left join catalog.video_engagement_stats stats on stats.video_id = target_video.video_id
`

type SetVideoLikedParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	VideoID    pgtype.UUID        `json:"video_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type SetVideoLikedRow struct {
	VideoID   pgtype.UUID `json:"video_id"`
	HasLiked  bool        `json:"has_liked"`
	LikeCount int64       `json:"like_count"`
}

func (q *Queries) SetVideoLiked(ctx context.Context, arg SetVideoLikedParams) (SetVideoLikedRow, error) {
	row := q.db.QueryRow(ctx, setVideoLiked, arg.UserID, arg.VideoID, arg.OccurredAt)
	var i SetVideoLikedRow
	err := row.Scan(&i.VideoID, &i.HasLiked, &i.LikeCount)
	return i, err
}

const setVideoUnfavorited = `-- name: SetVideoUnfavorited :one
with input as (
  select
    $1::uuid as user_id,
    $2::uuid as video_id,
    $3::timestamptz as occurred_at
),
target_video as (
  select videos.video_id
  from catalog.videos
  join input on input.video_id = videos.video_id
  where videos.status = 'active'
    and videos.visibility_status = 'public'
    and (videos.publish_at is null or videos.publish_at <= now())
),
previous_state as (
  select
    state.video_id,
    state.has_bookmarked,
    state.favorite_state_updated_at
  from catalog.video_user_states state
  join input
    on input.user_id = state.user_id
   and input.video_id = state.video_id
  join target_video on target_video.video_id = state.video_id
  for update of state
),
accepted_update as (
  update catalog.video_user_states state
  set
    has_bookmarked = false,
    bookmarked_at = null,
    favorite_state_updated_at = input.occurred_at,
    updated_at = now()
  from input
  join previous_state previous on previous.video_id = input.video_id
  where state.user_id = input.user_id
    and state.video_id = input.video_id
    and coalesce(previous.favorite_state_updated_at, '-infinity'::timestamptz) <= input.occurred_at
  returning state.video_id
),
delta as (
  select coalesce((
    select case
      when previous.has_bookmarked = true
       and coalesce(previous.favorite_state_updated_at, '-infinity'::timestamptz) <= input.occurred_at
      then 1
      else 0
    end
    from previous_state previous
    cross join input
  ), 0)::bigint as value
),
upsert_stats as (
  insert into catalog.video_engagement_stats (
    video_id,
    favorite_count,
    updated_at
  )
  select
    target_video.video_id,
    0,
    now()
  from target_video
  on conflict (video_id) do update set
    favorite_count = greatest(0, catalog.video_engagement_stats.favorite_count - (select value from delta)),
    updated_at = case
      when (select value from delta) > 0 then now()
      else catalog.video_engagement_stats.updated_at
    end
  returning video_id, favorite_count
),
final_state as (
  select
    target_video.video_id,
    case
      when exists (select 1 from accepted_update) then false
      else coalesce((select previous.has_bookmarked from previous_state previous), false)
    end as has_bookmarked
  from target_video
)
select
  target_video.video_id,
  coalesce(final_state.has_bookmarked, false)::boolean as has_favorited,
  coalesce(upsert_stats.favorite_count, stats.favorite_count, 0)::bigint as favorite_count
from target_video
left join final_state on final_state.video_id = target_video.video_id
left join upsert_stats on upsert_stats.video_id = target_video.video_id
left join catalog.video_engagement_stats stats on stats.video_id = target_video.video_id
`

type SetVideoUnfavoritedParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	VideoID    pgtype.UUID        `json:"video_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type SetVideoUnfavoritedRow struct {
	VideoID       pgtype.UUID `json:"video_id"`
	HasFavorited  bool        `json:"has_favorited"`
	FavoriteCount int64       `json:"favorite_count"`
}

func (q *Queries) SetVideoUnfavorited(ctx context.Context, arg SetVideoUnfavoritedParams) (SetVideoUnfavoritedRow, error) {
	row := q.db.QueryRow(ctx, setVideoUnfavorited, arg.UserID, arg.VideoID, arg.OccurredAt)
	var i SetVideoUnfavoritedRow
	err := row.Scan(&i.VideoID, &i.HasFavorited, &i.FavoriteCount)
	return i, err
}

const setVideoUnliked = `-- name: SetVideoUnliked :one
with input as (
  select
    $1::uuid as user_id,
    $2::uuid as video_id,
    $3::timestamptz as occurred_at
),
target_video as (
  select videos.video_id
  from catalog.videos
  join input on input.video_id = videos.video_id
  where videos.status = 'active'
    and videos.visibility_status = 'public'
    and (videos.publish_at is null or videos.publish_at <= now())
),
previous_state as (
  select
    state.video_id,
    state.has_liked,
    state.like_state_updated_at
  from catalog.video_user_states state
  join input
    on input.user_id = state.user_id
   and input.video_id = state.video_id
  join target_video on target_video.video_id = state.video_id
  for update of state
),
accepted_update as (
  update catalog.video_user_states state
  set
    has_liked = false,
    liked_at = null,
    like_state_updated_at = input.occurred_at,
    updated_at = now()
  from input
  join previous_state previous on previous.video_id = input.video_id
  where state.user_id = input.user_id
    and state.video_id = input.video_id
    and coalesce(previous.like_state_updated_at, '-infinity'::timestamptz) <= input.occurred_at
  returning state.video_id
),
delta as (
  select coalesce((
    select case
      when previous.has_liked = true
       and coalesce(previous.like_state_updated_at, '-infinity'::timestamptz) <= input.occurred_at
      then 1
      else 0
    end
    from previous_state previous
    cross join input
  ), 0)::bigint as value
),
upsert_stats as (
  insert into catalog.video_engagement_stats (
    video_id,
    like_count,
    updated_at
  )
  select
    target_video.video_id,
    0,
    now()
  from target_video
  on conflict (video_id) do update set
    like_count = greatest(0, catalog.video_engagement_stats.like_count - (select value from delta)),
    updated_at = case
      when (select value from delta) > 0 then now()
      else catalog.video_engagement_stats.updated_at
    end
  returning video_id, like_count
),
final_state as (
  select
    target_video.video_id,
    case
      when exists (select 1 from accepted_update) then false
      else coalesce((select previous.has_liked from previous_state previous), false)
    end as has_liked
  from target_video
)
select
  target_video.video_id,
  coalesce(final_state.has_liked, false)::boolean as has_liked,
  coalesce(upsert_stats.like_count, stats.like_count, 0)::bigint as like_count
from target_video
left join final_state on final_state.video_id = target_video.video_id
left join upsert_stats on upsert_stats.video_id = target_video.video_id
left join catalog.video_engagement_stats stats on stats.video_id = target_video.video_id
`

type SetVideoUnlikedParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	VideoID    pgtype.UUID        `json:"video_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type SetVideoUnlikedRow struct {
	VideoID   pgtype.UUID `json:"video_id"`
	HasLiked  bool        `json:"has_liked"`
	LikeCount int64       `json:"like_count"`
}

func (q *Queries) SetVideoUnliked(ctx context.Context, arg SetVideoUnlikedParams) (SetVideoUnlikedRow, error) {
	row := q.db.QueryRow(ctx, setVideoUnliked, arg.UserID, arg.VideoID, arg.OccurredAt)
	var i SetVideoUnlikedRow
	err := row.Scan(&i.VideoID, &i.HasLiked, &i.LikeCount)
	return i, err
}
