// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: word_favorites.sql

package catalogsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWordFavoriteVideoContext = `-- name: GetWordFavoriteVideoContext :one
select
  v.title,
  v.duration_ms,
  sentence.text as sentence_text,
  sentence.translation as sentence_translation,
  sentence.start_ms as sentence_start_ms,
  sentence.end_ms as sentence_end_ms
from catalog.videos v
join catalog.video_transcript_sentences sentence
  on sentence.video_id = v.video_id
where v.video_id = $1::uuid
  and sentence.sentence_index = $2::integer
  and v.status = 'active'
  and v.visibility_status = 'public'
  and (v.publish_at is null or v.publish_at <= now())
`

type GetWordFavoriteVideoContextParams struct {
	VideoID       pgtype.UUID `json:"video_id"`
	SentenceIndex int32       `json:"sentence_index"`
}

type GetWordFavoriteVideoContextRow struct {
	Title               string      `json:"title"`
	DurationMs          int32       `json:"duration_ms"`
	SentenceText        string      `json:"sentence_text"`
	SentenceTranslation pgtype.Text `json:"sentence_translation"`
	SentenceStartMs     int32       `json:"sentence_start_ms"`
	SentenceEndMs       int32       `json:"sentence_end_ms"`
}

func (q *Queries) GetWordFavoriteVideoContext(ctx context.Context, arg GetWordFavoriteVideoContextParams) (GetWordFavoriteVideoContextRow, error) {
	row := q.db.QueryRow(ctx, getWordFavoriteVideoContext, arg.VideoID, arg.SentenceIndex)
	var i GetWordFavoriteVideoContextRow
	err := row.Scan(
		&i.Title,
		&i.DurationMs,
		&i.SentenceText,
		&i.SentenceTranslation,
		&i.SentenceStartMs,
		&i.SentenceEndMs,
	)
	return i, err
}

const hasWordFavoriteByCoarse = `-- name: HasWordFavoriteByCoarse :one
select exists (
  select 1
  from catalog.word_favorites
  where user_id = $1::uuid
    and favorite_key_type = 'coarse_unit'
    and coarse_unit_id = $2::bigint
    and is_favorited = true
)
`

type HasWordFavoriteByCoarseParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	CoarseUnitID int64       `json:"coarse_unit_id"`
}

func (q *Queries) HasWordFavoriteByCoarse(ctx context.Context, arg HasWordFavoriteByCoarseParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasWordFavoriteByCoarse, arg.UserID, arg.CoarseUnitID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasWordFavoriteByToken = `-- name: HasWordFavoriteByToken :one
select exists (
  select 1
  from catalog.word_favorites
  where user_id = $1::uuid
    and favorite_key_type = 'video_token'
    and video_id = $2::uuid
    and sentence_index = $3::integer
    and token_index = $4::integer
    and is_favorited = true
)
`

type HasWordFavoriteByTokenParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	VideoID       pgtype.UUID `json:"video_id"`
	SentenceIndex int32       `json:"sentence_index"`
	TokenIndex    int32       `json:"token_index"`
}

func (q *Queries) HasWordFavoriteByToken(ctx context.Context, arg HasWordFavoriteByTokenParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasWordFavoriteByToken,
		arg.UserID,
		arg.VideoID,
		arg.SentenceIndex,
		arg.TokenIndex,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listWordFavorites = `-- name: ListWordFavorites :many
select
  wf.favorite_id,
  wf.favorited_at,
  wf.coarse_unit_id,
  cu.label,
  cu.pos,
  cu.chinese_label,
  cu.chinese_def,
  wf.source,
  wf.video_id,
  wf.sentence_index,
  wf.token_index,
  span.surface_text as source_text,
  sentence.translation as source_translation,
  span.dictionary as source_dictionary,
  span.explanation as source_explanation
from catalog.word_favorites wf
left join semantic.coarse_unit cu
  on cu.id = wf.coarse_unit_id
 and cu.status = 'active'
left join catalog.videos source_video
  on source_video.video_id = wf.video_id
 and source_video.status = 'active'
 and source_video.visibility_status = 'public'
 and (source_video.publish_at is null or source_video.publish_at <= now())
left join catalog.video_transcript_sentences sentence
  on sentence.video_id = source_video.video_id
 and sentence.sentence_index = wf.sentence_index
left join catalog.video_semantic_spans span
  on span.video_id = sentence.video_id
 and span.sentence_index = sentence.sentence_index
 and span.span_index = wf.token_index
where wf.user_id = $1::uuid
  and wf.is_favorited = true
  and wf.favorited_at is not null
  and (
    (wf.favorite_key_type = 'coarse_unit' and cu.id is not null)
    or
    (wf.favorite_key_type = 'video_token' and span.video_id is not null)
  )
  and (
    not $2::boolean
    or wf.favorited_at < $3::timestamptz
    or (
      wf.favorited_at = $3::timestamptz
      and wf.favorite_id > $4::uuid
    )
  )
order by wf.favorited_at desc, wf.favorite_id asc
limit $5::integer
`

type ListWordFavoritesParams struct {
	UserID            pgtype.UUID        `json:"user_id"`
	HasCursor         bool               `json:"has_cursor"`
	CursorFavoritedAt pgtype.Timestamptz `json:"cursor_favorited_at"`
	CursorFavoriteID  pgtype.UUID        `json:"cursor_favorite_id"`
	LimitPlusOne      int32              `json:"limit_plus_one"`
}

type ListWordFavoritesRow struct {
	FavoriteID        pgtype.UUID        `json:"favorite_id"`
	FavoritedAt       pgtype.Timestamptz `json:"favorited_at"`
	CoarseUnitID      pgtype.Int8        `json:"coarse_unit_id"`
	Label             pgtype.Text        `json:"label"`
	Pos               pgtype.Text        `json:"pos"`
	ChineseLabel      pgtype.Text        `json:"chinese_label"`
	ChineseDef        pgtype.Text        `json:"chinese_def"`
	Source            string             `json:"source"`
	VideoID           pgtype.UUID        `json:"video_id"`
	SentenceIndex     pgtype.Int4        `json:"sentence_index"`
	TokenIndex        pgtype.Int4        `json:"token_index"`
	SourceText        pgtype.Text        `json:"source_text"`
	SourceTranslation pgtype.Text        `json:"source_translation"`
	SourceDictionary  pgtype.Text        `json:"source_dictionary"`
	SourceExplanation pgtype.Text        `json:"source_explanation"`
}

func (q *Queries) ListWordFavorites(ctx context.Context, arg ListWordFavoritesParams) ([]ListWordFavoritesRow, error) {
	rows, err := q.db.Query(ctx, listWordFavorites,
		arg.UserID,
		arg.HasCursor,
		arg.CursorFavoritedAt,
		arg.CursorFavoriteID,
		arg.LimitPlusOne,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWordFavoritesRow{}
	for rows.Next() {
		var i ListWordFavoritesRow
		if err := rows.Scan(
			&i.FavoriteID,
			&i.FavoritedAt,
			&i.CoarseUnitID,
			&i.Label,
			&i.Pos,
			&i.ChineseLabel,
			&i.ChineseDef,
			&i.Source,
			&i.VideoID,
			&i.SentenceIndex,
			&i.TokenIndex,
			&i.SourceText,
			&i.SourceTranslation,
			&i.SourceDictionary,
			&i.SourceExplanation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCoarseWordFavorite = `-- name: SetCoarseWordFavorite :one
with input as (
  select
    $1::uuid as user_id,
    $2::bigint as coarse_unit_id,
    $3::text as source,
    $4::uuid as video_id,
    $5::integer as sentence_index,
    $6::integer as token_index,
    $7::timestamptz as occurred_at
),
existing as (
  select wf.state_updated_at, wf.is_favorited
  from catalog.word_favorites wf
  join input i
    on i.user_id = wf.user_id
   and i.coarse_unit_id = wf.coarse_unit_id
  where wf.favorite_key_type = 'coarse_unit'
  for update
),
state as (
  select
    exists (
      select 1
      from existing
      where state_updated_at > (select occurred_at from input)
    ) as is_stale,
    exists (
      select 1
      from existing
      where state_updated_at = (select occurred_at from input)
        and is_favorited = true
    ) as is_duplicate_set,
    exists (
      select 1
      from semantic.coarse_unit cu
      join input i on i.coarse_unit_id = cu.id
      where cu.status = 'active'
    ) as target_exists
),
upsert as (
insert into catalog.word_favorites (
  user_id,
  favorite_key_type,
  coarse_unit_id,
  source,
  video_id,
  sentence_index,
  token_index,
  is_favorited,
  favorited_at,
  state_updated_at
)
select
  i.user_id,
  'coarse_unit',
  i.coarse_unit_id,
  i.source,
  i.video_id,
  i.sentence_index,
  i.token_index,
  true,
  i.occurred_at,
  i.occurred_at
from input i
cross join state s
where not s.is_stale
  and not s.is_duplicate_set
  and s.target_exists
on conflict (user_id, coarse_unit_id) where favorite_key_type = 'coarse_unit'
do update set
  source = excluded.source,
  video_id = excluded.video_id,
  sentence_index = excluded.sentence_index,
  token_index = excluded.token_index,
  is_favorited = true,
  favorited_at = case
    when catalog.word_favorites.is_favorited then catalog.word_favorites.favorited_at
    else excluded.favorited_at
  end,
  state_updated_at = excluded.state_updated_at,
  updated_at = now()
where catalog.word_favorites.state_updated_at <= excluded.state_updated_at
returning 1
)
select case
  when (select is_stale from state) then 'stale'
  when (select is_duplicate_set from state) then 'applied'
  when not (select target_exists from state) then 'target_not_found'
  when exists (select 1 from upsert) then 'applied'
  else 'stale'
end::text as outcome
`

type SetCoarseWordFavoriteParams struct {
	UserID        pgtype.UUID        `json:"user_id"`
	CoarseUnitID  int64              `json:"coarse_unit_id"`
	Source        string             `json:"source"`
	VideoID       pgtype.UUID        `json:"video_id"`
	SentenceIndex pgtype.Int4        `json:"sentence_index"`
	TokenIndex    pgtype.Int4        `json:"token_index"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) SetCoarseWordFavorite(ctx context.Context, arg SetCoarseWordFavoriteParams) (string, error) {
	row := q.db.QueryRow(ctx, setCoarseWordFavorite,
		arg.UserID,
		arg.CoarseUnitID,
		arg.Source,
		arg.VideoID,
		arg.SentenceIndex,
		arg.TokenIndex,
		arg.OccurredAt,
	)
	var outcome string
	err := row.Scan(&outcome)
	return outcome, err
}

const setTokenWordFavorite = `-- name: SetTokenWordFavorite :one
with input as (
  select
    $1::uuid as user_id,
    $2::uuid as video_id,
    $3::integer as sentence_index,
    $4::integer as token_index,
    $5::timestamptz as occurred_at
),
existing as (
  select wf.state_updated_at, wf.is_favorited
  from catalog.word_favorites wf
  join input i
    on i.user_id = wf.user_id
   and i.video_id = wf.video_id
   and i.sentence_index = wf.sentence_index
   and i.token_index = wf.token_index
  where wf.favorite_key_type = 'video_token'
  for update
),
state as (
  select
    exists (
      select 1
      from existing
      where state_updated_at > (select occurred_at from input)
    ) as is_stale,
    exists (
      select 1
      from existing
      where state_updated_at = (select occurred_at from input)
        and is_favorited = true
    ) as is_duplicate_set,
    exists (
      select 1
      from catalog.videos v
      join input i on i.video_id = v.video_id
      join catalog.video_transcript_sentences sentence
        on sentence.video_id = v.video_id
       and sentence.sentence_index = i.sentence_index
      join catalog.video_semantic_spans span
        on span.video_id = sentence.video_id
       and span.sentence_index = sentence.sentence_index
       and span.span_index = i.token_index
      where v.status = 'active'
        and v.visibility_status = 'public'
        and (v.publish_at is null or v.publish_at <= now())
    ) as target_exists
),
upsert as (
insert into catalog.word_favorites (
  user_id,
  favorite_key_type,
  coarse_unit_id,
  source,
  video_id,
  sentence_index,
  token_index,
  is_favorited,
  favorited_at,
  state_updated_at
)
select
  i.user_id,
  'video_token',
  null,
  'video_transcript',
  i.video_id,
  i.sentence_index,
  i.token_index,
  true,
  i.occurred_at,
  i.occurred_at
from input i
cross join state s
where not s.is_stale
  and not s.is_duplicate_set
  and s.target_exists
on conflict (user_id, video_id, sentence_index, token_index) where favorite_key_type = 'video_token'
do update set
  is_favorited = true,
  favorited_at = case
    when catalog.word_favorites.is_favorited then catalog.word_favorites.favorited_at
    else excluded.favorited_at
  end,
  state_updated_at = excluded.state_updated_at,
  updated_at = now()
where catalog.word_favorites.state_updated_at <= excluded.state_updated_at
returning 1
)
select case
  when (select is_stale from state) then 'stale'
  when (select is_duplicate_set from state) then 'applied'
  when not (select target_exists from state) then 'target_not_found'
  when exists (select 1 from upsert) then 'applied'
  else 'stale'
end::text as outcome
`

type SetTokenWordFavoriteParams struct {
	UserID        pgtype.UUID        `json:"user_id"`
	VideoID       pgtype.UUID        `json:"video_id"`
	SentenceIndex int32              `json:"sentence_index"`
	TokenIndex    int32              `json:"token_index"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) SetTokenWordFavorite(ctx context.Context, arg SetTokenWordFavoriteParams) (string, error) {
	row := q.db.QueryRow(ctx, setTokenWordFavorite,
		arg.UserID,
		arg.VideoID,
		arg.SentenceIndex,
		arg.TokenIndex,
		arg.OccurredAt,
	)
	var outcome string
	err := row.Scan(&outcome)
	return outcome, err
}

const unsetWordFavoriteByCoarse = `-- name: UnsetWordFavoriteByCoarse :exec
insert into catalog.word_favorites (
  user_id,
  favorite_key_type,
  coarse_unit_id,
  source,
  video_id,
  sentence_index,
  token_index,
  is_favorited,
  favorited_at,
  state_updated_at
)
values (
  $1::uuid,
  'coarse_unit',
  $2::bigint,
  $3::text,
  $4::uuid,
  $5::integer,
  $6::integer,
  false,
  null::timestamptz,
  $7::timestamptz
)
on conflict (user_id, coarse_unit_id) where favorite_key_type = 'coarse_unit'
do update set
  source = excluded.source,
  video_id = excluded.video_id,
  sentence_index = excluded.sentence_index,
  token_index = excluded.token_index,
  is_favorited = false,
  favorited_at = null,
  state_updated_at = excluded.state_updated_at,
  updated_at = now()
where catalog.word_favorites.state_updated_at <= excluded.state_updated_at
`

type UnsetWordFavoriteByCoarseParams struct {
	UserID        pgtype.UUID        `json:"user_id"`
	CoarseUnitID  int64              `json:"coarse_unit_id"`
	Source        string             `json:"source"`
	VideoID       pgtype.UUID        `json:"video_id"`
	SentenceIndex pgtype.Int4        `json:"sentence_index"`
	TokenIndex    pgtype.Int4        `json:"token_index"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) UnsetWordFavoriteByCoarse(ctx context.Context, arg UnsetWordFavoriteByCoarseParams) error {
	_, err := q.db.Exec(ctx, unsetWordFavoriteByCoarse,
		arg.UserID,
		arg.CoarseUnitID,
		arg.Source,
		arg.VideoID,
		arg.SentenceIndex,
		arg.TokenIndex,
		arg.OccurredAt,
	)
	return err
}

const unsetWordFavoriteByToken = `-- name: UnsetWordFavoriteByToken :exec
insert into catalog.word_favorites (
  user_id,
  favorite_key_type,
  coarse_unit_id,
  source,
  video_id,
  sentence_index,
  token_index,
  is_favorited,
  favorited_at,
  state_updated_at
) values (
  $1::uuid,
  'video_token',
  null,
  'video_transcript',
  $2::uuid,
  $3::integer,
  $4::integer,
  false,
  null,
  $5::timestamptz
)
on conflict (user_id, video_id, sentence_index, token_index) where favorite_key_type = 'video_token'
do update set
  is_favorited = false,
  favorited_at = null,
  state_updated_at = excluded.state_updated_at,
  updated_at = now()
where catalog.word_favorites.state_updated_at <= excluded.state_updated_at
`

type UnsetWordFavoriteByTokenParams struct {
	UserID        pgtype.UUID        `json:"user_id"`
	VideoID       pgtype.UUID        `json:"video_id"`
	SentenceIndex int32              `json:"sentence_index"`
	TokenIndex    int32              `json:"token_index"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) UnsetWordFavoriteByToken(ctx context.Context, arg UnsetWordFavoriteByTokenParams) error {
	_, err := q.db.Exec(ctx, unsetWordFavoriteByToken,
		arg.UserID,
		arg.VideoID,
		arg.SentenceIndex,
		arg.TokenIndex,
		arg.OccurredAt,
	)
	return err
}
