// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package recommendationsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthUser struct {
	ID pgtype.UUID `json:"id"`
}

type CatalogVideo struct {
	VideoID          pgtype.UUID        `json:"video_id"`
	DurationMs       int32              `json:"duration_ms"`
	Status           string             `json:"status"`
	VisibilityStatus string             `json:"visibility_status"`
	PublishAt        pgtype.Timestamptz `json:"publish_at"`
}

type CatalogVideoSemanticSpan struct {
	VideoID       pgtype.UUID `json:"video_id"`
	SentenceIndex int32       `json:"sentence_index"`
	SpanIndex     int32       `json:"span_index"`
	CoarseUnitID  pgtype.Int8 `json:"coarse_unit_id"`
	StartMs       int32       `json:"start_ms"`
	EndMs         int32       `json:"end_ms"`
	Text          string      `json:"text"`
	Explanation   pgtype.Text `json:"explanation"`
}

type CatalogVideoTranscript struct {
	VideoID         pgtype.UUID    `json:"video_id"`
	MappedSpanRatio pgtype.Numeric `json:"mapped_span_ratio"`
}

type CatalogVideoTranscriptSentence struct {
	VideoID       pgtype.UUID `json:"video_id"`
	SentenceIndex int32       `json:"sentence_index"`
	Text          string      `json:"text"`
	StartMs       int32       `json:"start_ms"`
	EndMs         int32       `json:"end_ms"`
	Explanation   pgtype.Text `json:"explanation"`
}

type CatalogVideoUnitIndex struct {
	VideoID            pgtype.UUID    `json:"video_id"`
	CoarseUnitID       int64          `json:"coarse_unit_id"`
	MentionCount       int32          `json:"mention_count"`
	SentenceCount      int32          `json:"sentence_count"`
	FirstStartMs       int32          `json:"first_start_ms"`
	LastEndMs          int32          `json:"last_end_ms"`
	CoverageMs         int32          `json:"coverage_ms"`
	CoverageRatio      pgtype.Numeric `json:"coverage_ratio"`
	SentenceIndexes    []int32        `json:"sentence_indexes"`
	EvidenceSpanRefs   []byte         `json:"evidence_span_refs"`
	SampleSurfaceForms []string       `json:"sample_surface_forms"`
}

type CatalogVideoUserState struct {
	UserID         pgtype.UUID        `json:"user_id"`
	VideoID        pgtype.UUID        `json:"video_id"`
	LastWatchedAt  pgtype.Timestamptz `json:"last_watched_at"`
	WatchCount     int32              `json:"watch_count"`
	CompletedCount int32              `json:"completed_count"`
	LastWatchRatio pgtype.Numeric     `json:"last_watch_ratio"`
	MaxWatchRatio  pgtype.Numeric     `json:"max_watch_ratio"`
}

type LearningUserUnitState struct {
	UserID                  pgtype.UUID        `json:"user_id"`
	CoarseUnitID            int64              `json:"coarse_unit_id"`
	IsTarget                bool               `json:"is_target"`
	TargetPriority          pgtype.Numeric     `json:"target_priority"`
	Status                  string             `json:"status"`
	ProgressPercent         pgtype.Numeric     `json:"progress_percent"`
	MasteryScore            pgtype.Numeric     `json:"mastery_score"`
	LastQuality             pgtype.Int2        `json:"last_quality"`
	NextReviewAt            pgtype.Timestamptz `json:"next_review_at"`
	RecentQualityWindow     []int16            `json:"recent_quality_window"`
	RecentCorrectnessWindow []bool             `json:"recent_correctness_window"`
	StrongEventCount        int32              `json:"strong_event_count"`
	ReviewCount             int32              `json:"review_count"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type RecommendationUserUnitServingState struct {
	UserID       pgtype.UUID        `json:"user_id"`
	CoarseUnitID int64              `json:"coarse_unit_id"`
	LastServedAt pgtype.Timestamptz `json:"last_served_at"`
	LastRunID    pgtype.UUID        `json:"last_run_id"`
	ServedCount  int32              `json:"served_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RecommendationUserVideoServingState struct {
	UserID       pgtype.UUID        `json:"user_id"`
	VideoID      pgtype.UUID        `json:"video_id"`
	LastServedAt pgtype.Timestamptz `json:"last_served_at"`
	LastRunID    pgtype.UUID        `json:"last_run_id"`
	ServedCount  int32              `json:"served_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RecommendationVRecommendableVideoUnit struct {
	VideoID            pgtype.UUID        `json:"video_id"`
	CoarseUnitID       pgtype.Int8        `json:"coarse_unit_id"`
	MentionCount       pgtype.Int4        `json:"mention_count"`
	SentenceCount      pgtype.Int4        `json:"sentence_count"`
	FirstStartMs       pgtype.Int4        `json:"first_start_ms"`
	LastEndMs          pgtype.Int4        `json:"last_end_ms"`
	CoverageMs         pgtype.Int4        `json:"coverage_ms"`
	CoverageRatio      pgtype.Numeric     `json:"coverage_ratio"`
	SentenceIndexes    []int32            `json:"sentence_indexes"`
	EvidenceSpanRefs   []byte             `json:"evidence_span_refs"`
	SampleSurfaceForms []string           `json:"sample_surface_forms"`
	DurationMs         pgtype.Int4        `json:"duration_ms"`
	MappedSpanRatio    pgtype.Numeric     `json:"mapped_span_ratio"`
	Status             pgtype.Text        `json:"status"`
	VisibilityStatus   pgtype.Text        `json:"visibility_status"`
	PublishAt          pgtype.Timestamptz `json:"publish_at"`
}

type RecommendationVUnitVideoInventory struct {
	CoarseUnitID       pgtype.Int8        `json:"coarse_unit_id"`
	DistinctVideoCount pgtype.Int4        `json:"distinct_video_count"`
	AvgMentionCount    pgtype.Numeric     `json:"avg_mention_count"`
	AvgSentenceCount   pgtype.Numeric     `json:"avg_sentence_count"`
	AvgCoverageMs      pgtype.Numeric     `json:"avg_coverage_ms"`
	AvgCoverageRatio   pgtype.Numeric     `json:"avg_coverage_ratio"`
	StrongVideoCount   pgtype.Int4        `json:"strong_video_count"`
	SupplyGrade        pgtype.Text        `json:"supply_grade"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type RecommendationVideoRecommendationItem struct {
	RunID                     pgtype.UUID        `json:"run_id"`
	Rank                      int32              `json:"rank"`
	VideoID                   pgtype.UUID        `json:"video_id"`
	Score                     pgtype.Numeric     `json:"score"`
	PrimaryLane               pgtype.Text        `json:"primary_lane"`
	DominantBucket            pgtype.Text        `json:"dominant_bucket"`
	DominantUnitID            pgtype.Int8        `json:"dominant_unit_id"`
	ReasonCodes               []string           `json:"reason_codes"`
	CoveredHardReviewCount    int32              `json:"covered_hard_review_count"`
	CoveredNewNowCount        int32              `json:"covered_new_now_count"`
	CoveredSoftReviewCount    int32              `json:"covered_soft_review_count"`
	CoveredNearFutureCount    int32              `json:"covered_near_future_count"`
	BestEvidenceSentenceIndex pgtype.Int4        `json:"best_evidence_sentence_index"`
	BestEvidenceSpanIndex     pgtype.Int4        `json:"best_evidence_span_index"`
	BestEvidenceStartMs       pgtype.Int4        `json:"best_evidence_start_ms"`
	BestEvidenceEndMs         pgtype.Int4        `json:"best_evidence_end_ms"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
}

type RecommendationVideoRecommendationRun struct {
	RunID              pgtype.UUID        `json:"run_id"`
	UserID             pgtype.UUID        `json:"user_id"`
	RequestContext     []byte             `json:"request_context"`
	SessionMode        pgtype.Text        `json:"session_mode"`
	SelectorMode       pgtype.Text        `json:"selector_mode"`
	PlannerSnapshot    []byte             `json:"planner_snapshot"`
	LaneBudgetSnapshot []byte             `json:"lane_budget_snapshot"`
	CandidateSummary   []byte             `json:"candidate_summary"`
	Underfilled        bool               `json:"underfilled"`
	ResultCount        int32              `json:"result_count"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type SemanticCoarseUnit struct {
	ID int64 `json:"id"`
}
