// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package recommendationsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthUser struct {
	ID               pgtype.UUID        `json:"id"`
	Email            pgtype.Text        `json:"email"`
	EmailConfirmedAt pgtype.Timestamptz `json:"email_confirmed_at"`
}

type CatalogVideo struct {
	VideoID          pgtype.UUID        `json:"video_id"`
	DurationMs       int32              `json:"duration_ms"`
	Status           string             `json:"status"`
	VisibilityStatus string             `json:"visibility_status"`
	PublishAt        pgtype.Timestamptz `json:"publish_at"`
}

type CatalogVideoEngagementStat struct {
	VideoID        pgtype.UUID        `json:"video_id"`
	ViewCount      int64              `json:"view_count"`
	LikeCount      int64              `json:"like_count"`
	FavoriteCount  int64              `json:"favorite_count"`
	CompletedCount int64              `json:"completed_count"`
	TotalWatchMs   int64              `json:"total_watch_ms"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CatalogVideoSemanticSpan struct {
	VideoID       pgtype.UUID `json:"video_id"`
	SentenceIndex int32       `json:"sentence_index"`
	SpanIndex     int32       `json:"span_index"`
	CoarseUnitID  pgtype.Int8 `json:"coarse_unit_id"`
	StartMs       int32       `json:"start_ms"`
	EndMs         int32       `json:"end_ms"`
	SurfaceText   string      `json:"surface_text"`
	Explanation   pgtype.Text `json:"explanation"`
	BaseForm      pgtype.Text `json:"base_form"`
	Translation   pgtype.Text `json:"translation"`
	Dictionary    pgtype.Text `json:"dictionary"`
	MappingReason pgtype.Text `json:"mapping_reason"`
}

type CatalogVideoTranscript struct {
	VideoID         pgtype.UUID    `json:"video_id"`
	MappedSpanRatio pgtype.Numeric `json:"mapped_span_ratio"`
}

type CatalogVideoTranscriptSentence struct {
	VideoID       pgtype.UUID `json:"video_id"`
	SentenceIndex int32       `json:"sentence_index"`
	StartMs       int32       `json:"start_ms"`
	EndMs         int32       `json:"end_ms"`
	Text          string      `json:"text"`
	Translation   pgtype.Text `json:"translation"`
}

type CatalogVideoUnitIndex struct {
	VideoID                          pgtype.UUID    `json:"video_id"`
	CoarseUnitID                     int64          `json:"coarse_unit_id"`
	MentionCount                     int32          `json:"mention_count"`
	SentenceCount                    int32          `json:"sentence_count"`
	CoverageMs                       int32          `json:"coverage_ms"`
	CoverageRatio                    pgtype.Numeric `json:"coverage_ratio"`
	SentenceIndexes                  []int32        `json:"sentence_indexes"`
	BestEvidenceSentenceIndex        int32          `json:"best_evidence_sentence_index"`
	BestEvidenceSpanIndex            int32          `json:"best_evidence_span_index"`
	BestEvidenceStartMs              pgtype.Int4    `json:"best_evidence_start_ms"`
	BestEvidenceEndMs                pgtype.Int4    `json:"best_evidence_end_ms"`
	BestEvidenceScores               []byte         `json:"best_evidence_scores"`
	BestEvidenceQuestionRejectReason pgtype.Text    `json:"best_evidence_question_reject_reason"`
	BestEvidenceSelectionReason      pgtype.Text    `json:"best_evidence_selection_reason"`
	BestEvidenceCandidateScore       pgtype.Numeric `json:"best_evidence_candidate_score"`
	BestEvidenceTargetText           pgtype.Text    `json:"best_evidence_target_text"`
}

type CatalogVideoUserState struct {
	UserID         pgtype.UUID        `json:"user_id"`
	VideoID        pgtype.UUID        `json:"video_id"`
	LastWatchedAt  pgtype.Timestamptz `json:"last_watched_at"`
	WatchCount     int32              `json:"watch_count"`
	CompletedCount int32              `json:"completed_count"`
	LastPositionMs int32              `json:"last_position_ms"`
	MaxPositionMs  int32              `json:"max_position_ms"`
	TotalWatchMs   int64              `json:"total_watch_ms"`
}

type LearningUserUnitState struct {
	UserID              pgtype.UUID        `json:"user_id"`
	CoarseUnitID        int64              `json:"coarse_unit_id"`
	IsTarget            bool               `json:"is_target"`
	TargetPriority      pgtype.Numeric     `json:"target_priority"`
	Status              string             `json:"status"`
	MasteryScore        pgtype.Numeric     `json:"mastery_score"`
	LastProgressQuality pgtype.Int2        `json:"last_progress_quality"`
	NextReviewAt        pgtype.Timestamptz `json:"next_review_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type RecommendationRecallProjectionMetadatum struct {
	ProjectionName      string             `json:"projection_name"`
	ProjectionUpdatedAt pgtype.Timestamptz `json:"projection_updated_at"`
}

type RecommendationUserUnitRecallQueue struct {
	UserID              pgtype.UUID        `json:"user_id"`
	CoarseUnitID        int64              `json:"coarse_unit_id"`
	Status              string             `json:"status"`
	TargetPriority      pgtype.Numeric     `json:"target_priority"`
	MasteryScore        pgtype.Numeric     `json:"mastery_score"`
	LastProgressQuality pgtype.Int2        `json:"last_progress_quality"`
	NextReviewAt        pgtype.Timestamptz `json:"next_review_at"`
	SupplyGrade         string             `json:"supply_grade"`
	StateUpdatedAt      pgtype.Timestamptz `json:"state_updated_at"`
	SourceVersion       string             `json:"source_version"`
	RebuiltAt           pgtype.Timestamptz `json:"rebuilt_at"`
}

type RecommendationUserUnitRecallQueueState struct {
	UserID                     pgtype.UUID        `json:"user_id"`
	SourceLearningMaxUpdatedAt pgtype.Timestamptz `json:"source_learning_max_updated_at"`
	SourceProjectionUpdatedAt  pgtype.Timestamptz `json:"source_projection_updated_at"`
	ActiveTargetUnitCount      int32              `json:"active_target_unit_count"`
	RebuiltAt                  pgtype.Timestamptz `json:"rebuilt_at"`
}

type RecommendationUserUnitServingState struct {
	UserID       pgtype.UUID        `json:"user_id"`
	CoarseUnitID int64              `json:"coarse_unit_id"`
	LastServedAt pgtype.Timestamptz `json:"last_served_at"`
	LastRunID    pgtype.UUID        `json:"last_run_id"`
	ServedCount  int32              `json:"served_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RecommendationUserVideoServingState struct {
	UserID       pgtype.UUID        `json:"user_id"`
	VideoID      pgtype.UUID        `json:"video_id"`
	LastServedAt pgtype.Timestamptz `json:"last_served_at"`
	LastRunID    pgtype.UUID        `json:"last_run_id"`
	ServedCount  int32              `json:"served_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RecommendationVUnitVideoInventory struct {
	CoarseUnitID       pgtype.Int8        `json:"coarse_unit_id"`
	DistinctVideoCount pgtype.Int4        `json:"distinct_video_count"`
	AvgMentionCount    pgtype.Numeric     `json:"avg_mention_count"`
	AvgSentenceCount   pgtype.Numeric     `json:"avg_sentence_count"`
	AvgCoverageMs      pgtype.Numeric     `json:"avg_coverage_ms"`
	AvgCoverageRatio   pgtype.Numeric     `json:"avg_coverage_ratio"`
	StrongVideoCount   pgtype.Int4        `json:"strong_video_count"`
	SupplyGrade        pgtype.Text        `json:"supply_grade"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type RecommendationVVideoUnitRecallIndex struct {
	VideoID                          pgtype.UUID        `json:"video_id"`
	CoarseUnitID                     pgtype.Int8        `json:"coarse_unit_id"`
	MentionCount                     pgtype.Int4        `json:"mention_count"`
	SentenceCount                    pgtype.Int4        `json:"sentence_count"`
	CoverageMs                       pgtype.Int4        `json:"coverage_ms"`
	CoverageRatio                    pgtype.Numeric     `json:"coverage_ratio"`
	SentenceIndexes                  []int32            `json:"sentence_indexes"`
	BestEvidenceSentenceIndex        pgtype.Int4        `json:"best_evidence_sentence_index"`
	BestEvidenceSpanIndex            pgtype.Int4        `json:"best_evidence_span_index"`
	BestEvidenceStartMs              pgtype.Int4        `json:"best_evidence_start_ms"`
	BestEvidenceEndMs                pgtype.Int4        `json:"best_evidence_end_ms"`
	BestEvidenceScores               []byte             `json:"best_evidence_scores"`
	BestEvidenceQuestionRejectReason pgtype.Text        `json:"best_evidence_question_reject_reason"`
	BestEvidenceSelectionReason      pgtype.Text        `json:"best_evidence_selection_reason"`
	BestEvidenceCandidateScore       pgtype.Numeric     `json:"best_evidence_candidate_score"`
	BestEvidenceTargetText           pgtype.Text        `json:"best_evidence_target_text"`
	DurationMs                       pgtype.Int4        `json:"duration_ms"`
	MappedSpanRatio                  pgtype.Numeric     `json:"mapped_span_ratio"`
	Status                           pgtype.Text        `json:"status"`
	VisibilityStatus                 pgtype.Text        `json:"visibility_status"`
	PublishAt                        pgtype.Timestamptz `json:"publish_at"`
	ContentQualityScore              pgtype.Numeric     `json:"content_quality_score"`
	RankWithinUnit                   pgtype.Int4        `json:"rank_within_unit"`
}

type RecommendationVideoRecommendationItem struct {
	RunID          pgtype.UUID        `json:"run_id"`
	Rank           int32              `json:"rank"`
	VideoID        pgtype.UUID        `json:"video_id"`
	Score          pgtype.Numeric     `json:"score"`
	PrimaryLane    pgtype.Text        `json:"primary_lane"`
	DominantRole   pgtype.Text        `json:"dominant_role"`
	DominantUnitID pgtype.Int8        `json:"dominant_unit_id"`
	ReasonCodes    []string           `json:"reason_codes"`
	LearningUnits  []byte             `json:"learning_units"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RecommendationVideoRecommendationRun struct {
	RunID              pgtype.UUID        `json:"run_id"`
	UserID             pgtype.UUID        `json:"user_id"`
	RequestContext     []byte             `json:"request_context"`
	SessionMode        pgtype.Text        `json:"session_mode"`
	SelectorMode       pgtype.Text        `json:"selector_mode"`
	PlannerSnapshot    []byte             `json:"planner_snapshot"`
	LaneBudgetSnapshot []byte             `json:"lane_budget_snapshot"`
	CandidateSummary   []byte             `json:"candidate_summary"`
	Underfilled        bool               `json:"underfilled"`
	ResultCount        int32              `json:"result_count"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type SemanticCoarseUnit struct {
	ID              int64              `json:"id"`
	Kind            string             `json:"kind"`
	Label           string             `json:"label"`
	Lang            string             `json:"lang"`
	Pos             pgtype.Text        `json:"pos"`
	EnglishDef      pgtype.Text        `json:"english_def"`
	ChineseDef      pgtype.Text        `json:"chinese_def"`
	ChineseCriteria pgtype.Text        `json:"chinese_criteria"`
	ChineseLabel    pgtype.Text        `json:"chinese_label"`
	EnglishLabel    pgtype.Text        `json:"english_label"`
	Pattern         []byte             `json:"pattern"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Version         int32              `json:"version"`
	FineUnitIds     []int64            `json:"fine_unit_ids"`
	OriginalDefs    []string           `json:"original_defs"`
}
