// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package recommendationsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	InsertVideoRecommendationItem(ctx context.Context, arg InsertVideoRecommendationItemParams) error
	InsertVideoRecommendationRun(ctx context.Context, arg InsertVideoRecommendationRunParams) error
	ListLearningStatesForRecommendation(ctx context.Context, userID pgtype.UUID) ([]LearningUserUnitState, error)
	ListRecommendableVideoUnitsByUnitIDs(ctx context.Context, coarseUnitIds []int64) ([]RecommendationVRecommendableVideoUnit, error)
	ListSemanticSpansByVideoAndUnit(ctx context.Context, arg ListSemanticSpansByVideoAndUnitParams) ([]CatalogVideoSemanticSpan, error)
	ListTranscriptSentencesByVideoAndIndexes(ctx context.Context, arg ListTranscriptSentencesByVideoAndIndexesParams) ([]CatalogVideoTranscriptSentence, error)
	ListUnitVideoInventoryByUnitIDs(ctx context.Context, coarseUnitIds []int64) ([]RecommendationVUnitVideoInventory, error)
	ListVideoUserStatesByUserAndVideoIDs(ctx context.Context, arg ListVideoUserStatesByUserAndVideoIDsParams) ([]CatalogVideoUserState, error)
	RefreshRecommendableVideoUnits(ctx context.Context) error
	RefreshUnitVideoInventory(ctx context.Context) error
	UpsertUserUnitServingState(ctx context.Context, arg UpsertUserUnitServingStateParams) error
	UpsertUserVideoServingState(ctx context.Context, arg UpsertUserVideoServingStateParams) error
}

var _ Querier = (*Queries)(nil)
