// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package recommendationsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetSemanticSpanByVideoUnitAndRef(ctx context.Context, arg GetSemanticSpanByVideoUnitAndRefParams) (CatalogVideoSemanticSpan, error)
	IncrementUserUnitServingStates(ctx context.Context, arg IncrementUserUnitServingStatesParams) error
	IncrementUserVideoServingStates(ctx context.Context, arg IncrementUserVideoServingStatesParams) error
	InsertVideoRecommendationItem(ctx context.Context, arg InsertVideoRecommendationItemParams) error
	InsertVideoRecommendationRun(ctx context.Context, arg InsertVideoRecommendationRunParams) error
	ListLearningStatesForRecommendation(ctx context.Context, userID pgtype.UUID) ([]LearningUserUnitState, error)
	ListRecommendableVideoUnitsByUnitIDs(ctx context.Context, coarseUnitIds []int64) ([]RecommendationVRecommendableVideoUnit, error)
	ListTranscriptSentencesByVideoAndIndexes(ctx context.Context, arg ListTranscriptSentencesByVideoAndIndexesParams) ([]CatalogVideoTranscriptSentence, error)
	ListUnitVideoInventoryByUnitIDs(ctx context.Context, coarseUnitIds []int64) ([]RecommendationVUnitVideoInventory, error)
	ListUserUnitServingStatesByUnitIDs(ctx context.Context, arg ListUserUnitServingStatesByUnitIDsParams) ([]RecommendationUserUnitServingState, error)
	ListUserVideoServingStatesByVideoIDs(ctx context.Context, arg ListUserVideoServingStatesByVideoIDsParams) ([]RecommendationUserVideoServingState, error)
	ListVideoUserStatesByUserAndVideoIDs(ctx context.Context, arg ListVideoUserStatesByUserAndVideoIDsParams) ([]CatalogVideoUserState, error)
	RefreshRecommendableVideoUnits(ctx context.Context) error
	RefreshUnitVideoInventory(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
