// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recommendation_reads.sql

package recommendationsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listLearningStatesForRecommendation = `-- name: ListLearningStatesForRecommendation :many
select
  user_id,
  coarse_unit_id,
  is_target,
  target_priority,
  status,
  progress_percent,
  mastery_score,
  last_quality,
  next_review_at,
  recent_quality_window,
  recent_correctness_window,
  strong_event_count,
  review_count,
  updated_at
from learning.user_unit_states
where user_id = $1
  and is_target = true
  and status <> 'suspended'
order by target_priority desc, coarse_unit_id asc
`

func (q *Queries) ListLearningStatesForRecommendation(ctx context.Context, userID pgtype.UUID) ([]LearningUserUnitState, error) {
	rows, err := q.db.Query(ctx, listLearningStatesForRecommendation, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningUserUnitState{}
	for rows.Next() {
		var i LearningUserUnitState
		if err := rows.Scan(
			&i.UserID,
			&i.CoarseUnitID,
			&i.IsTarget,
			&i.TargetPriority,
			&i.Status,
			&i.ProgressPercent,
			&i.MasteryScore,
			&i.LastQuality,
			&i.NextReviewAt,
			&i.RecentQualityWindow,
			&i.RecentCorrectnessWindow,
			&i.StrongEventCount,
			&i.ReviewCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendableVideoUnitsByUnitIDs = `-- name: ListRecommendableVideoUnitsByUnitIDs :many
select video_id, coarse_unit_id, mention_count, sentence_count, first_start_ms, last_end_ms, coverage_ms, coverage_ratio, sentence_indexes, evidence_span_refs, sample_surface_forms, duration_ms, mapped_span_ratio, status, visibility_status, publish_at
from recommendation.v_recommendable_video_units
where coarse_unit_id = any($1::bigint[])
order by coarse_unit_id asc, coverage_ratio desc, mention_count desc
`

func (q *Queries) ListRecommendableVideoUnitsByUnitIDs(ctx context.Context, coarseUnitIds []int64) ([]RecommendationVRecommendableVideoUnit, error) {
	rows, err := q.db.Query(ctx, listRecommendableVideoUnitsByUnitIDs, coarseUnitIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecommendationVRecommendableVideoUnit{}
	for rows.Next() {
		var i RecommendationVRecommendableVideoUnit
		if err := rows.Scan(
			&i.VideoID,
			&i.CoarseUnitID,
			&i.MentionCount,
			&i.SentenceCount,
			&i.FirstStartMs,
			&i.LastEndMs,
			&i.CoverageMs,
			&i.CoverageRatio,
			&i.SentenceIndexes,
			&i.EvidenceSpanRefs,
			&i.SampleSurfaceForms,
			&i.DurationMs,
			&i.MappedSpanRatio,
			&i.Status,
			&i.VisibilityStatus,
			&i.PublishAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSemanticSpansByVideoAndUnit = `-- name: ListSemanticSpansByVideoAndUnit :many
select video_id, sentence_index, span_index, coarse_unit_id, start_ms, end_ms, text, explanation
from catalog.video_semantic_spans
where video_id = $1
  and coarse_unit_id = $2
order by sentence_index asc, span_index asc
`

type ListSemanticSpansByVideoAndUnitParams struct {
	VideoID      pgtype.UUID `json:"video_id"`
	CoarseUnitID pgtype.Int8 `json:"coarse_unit_id"`
}

func (q *Queries) ListSemanticSpansByVideoAndUnit(ctx context.Context, arg ListSemanticSpansByVideoAndUnitParams) ([]CatalogVideoSemanticSpan, error) {
	rows, err := q.db.Query(ctx, listSemanticSpansByVideoAndUnit, arg.VideoID, arg.CoarseUnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogVideoSemanticSpan{}
	for rows.Next() {
		var i CatalogVideoSemanticSpan
		if err := rows.Scan(
			&i.VideoID,
			&i.SentenceIndex,
			&i.SpanIndex,
			&i.CoarseUnitID,
			&i.StartMs,
			&i.EndMs,
			&i.Text,
			&i.Explanation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptSentencesByVideoAndIndexes = `-- name: ListTranscriptSentencesByVideoAndIndexes :many
select video_id, sentence_index, text, start_ms, end_ms, explanation
from catalog.video_transcript_sentences
where video_id = $1
  and sentence_index = any($2::integer[])
order by sentence_index asc
`

type ListTranscriptSentencesByVideoAndIndexesParams struct {
	VideoID         pgtype.UUID `json:"video_id"`
	SentenceIndexes []int32     `json:"sentence_indexes"`
}

func (q *Queries) ListTranscriptSentencesByVideoAndIndexes(ctx context.Context, arg ListTranscriptSentencesByVideoAndIndexesParams) ([]CatalogVideoTranscriptSentence, error) {
	rows, err := q.db.Query(ctx, listTranscriptSentencesByVideoAndIndexes, arg.VideoID, arg.SentenceIndexes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogVideoTranscriptSentence{}
	for rows.Next() {
		var i CatalogVideoTranscriptSentence
		if err := rows.Scan(
			&i.VideoID,
			&i.SentenceIndex,
			&i.Text,
			&i.StartMs,
			&i.EndMs,
			&i.Explanation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitVideoInventoryByUnitIDs = `-- name: ListUnitVideoInventoryByUnitIDs :many
select coarse_unit_id, distinct_video_count, avg_mention_count, avg_sentence_count, avg_coverage_ms, avg_coverage_ratio, strong_video_count, supply_grade, updated_at
from recommendation.v_unit_video_inventory
where coarse_unit_id = any($1::bigint[])
order by coarse_unit_id asc
`

func (q *Queries) ListUnitVideoInventoryByUnitIDs(ctx context.Context, coarseUnitIds []int64) ([]RecommendationVUnitVideoInventory, error) {
	rows, err := q.db.Query(ctx, listUnitVideoInventoryByUnitIDs, coarseUnitIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecommendationVUnitVideoInventory{}
	for rows.Next() {
		var i RecommendationVUnitVideoInventory
		if err := rows.Scan(
			&i.CoarseUnitID,
			&i.DistinctVideoCount,
			&i.AvgMentionCount,
			&i.AvgSentenceCount,
			&i.AvgCoverageMs,
			&i.AvgCoverageRatio,
			&i.StrongVideoCount,
			&i.SupplyGrade,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideoUserStatesByUserAndVideoIDs = `-- name: ListVideoUserStatesByUserAndVideoIDs :many
select user_id, video_id, last_watched_at, watch_count, completed_count, last_watch_ratio, max_watch_ratio
from catalog.video_user_states
where user_id = $1
  and video_id = any($2::uuid[])
order by video_id asc
`

type ListVideoUserStatesByUserAndVideoIDsParams struct {
	UserID   pgtype.UUID   `json:"user_id"`
	VideoIds []pgtype.UUID `json:"video_ids"`
}

func (q *Queries) ListVideoUserStatesByUserAndVideoIDs(ctx context.Context, arg ListVideoUserStatesByUserAndVideoIDsParams) ([]CatalogVideoUserState, error) {
	rows, err := q.db.Query(ctx, listVideoUserStatesByUserAndVideoIDs, arg.UserID, arg.VideoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogVideoUserState{}
	for rows.Next() {
		var i CatalogVideoUserState
		if err := rows.Scan(
			&i.UserID,
			&i.VideoID,
			&i.LastWatchedAt,
			&i.WatchCount,
			&i.CompletedCount,
			&i.LastWatchRatio,
			&i.MaxWatchRatio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
