// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recommendation_reads.sql

package recommendationsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLearningStateVersionForRecommendation = `-- name: GetLearningStateVersionForRecommendation :one
select
  count(*)::integer as active_target_unit_count,
  max(updated_at)::timestamptz as source_learning_max_updated_at
from learning.user_unit_states
where user_id = $1
  and is_target = true
  and status in ('new', 'learning', 'reviewing')
`

type GetLearningStateVersionForRecommendationRow struct {
	ActiveTargetUnitCount      int32              `json:"active_target_unit_count"`
	SourceLearningMaxUpdatedAt pgtype.Timestamptz `json:"source_learning_max_updated_at"`
}

func (q *Queries) GetLearningStateVersionForRecommendation(ctx context.Context, userID pgtype.UUID) (GetLearningStateVersionForRecommendationRow, error) {
	row := q.db.QueryRow(ctx, getLearningStateVersionForRecommendation, userID)
	var i GetLearningStateVersionForRecommendationRow
	err := row.Scan(&i.ActiveTargetUnitCount, &i.SourceLearningMaxUpdatedAt)
	return i, err
}

const getRecallProjectionMetadata = `-- name: GetRecallProjectionMetadata :one
select projection_updated_at
from recommendation.recall_projection_metadata
where projection_name = 'video_unit_recall_index'
`

func (q *Queries) GetRecallProjectionMetadata(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getRecallProjectionMetadata)
	var projection_updated_at pgtype.Timestamptz
	err := row.Scan(&projection_updated_at)
	return projection_updated_at, err
}

const getUserRecallQueueState = `-- name: GetUserRecallQueueState :one
select
  user_id,
  source_learning_max_updated_at,
  source_projection_updated_at,
  active_target_unit_count,
  rebuilt_at
from recommendation.user_unit_recall_queue_states
where user_id = $1
`

func (q *Queries) GetUserRecallQueueState(ctx context.Context, userID pgtype.UUID) (RecommendationUserUnitRecallQueueState, error) {
	row := q.db.QueryRow(ctx, getUserRecallQueueState, userID)
	var i RecommendationUserUnitRecallQueueState
	err := row.Scan(
		&i.UserID,
		&i.SourceLearningMaxUpdatedAt,
		&i.SourceProjectionUpdatedAt,
		&i.ActiveTargetUnitCount,
		&i.RebuiltAt,
	)
	return i, err
}

const listLearningStatesForRecommendation = `-- name: ListLearningStatesForRecommendation :many
select
  user_id,
  coarse_unit_id,
  is_target,
  target_priority,
  status,
  mastery_score,
  last_progress_quality,
  next_review_at,
  updated_at
from learning.user_unit_states
where user_id = $1
  and is_target = true
  and status in ('new', 'learning', 'reviewing')
order by target_priority desc, coarse_unit_id asc
`

func (q *Queries) ListLearningStatesForRecommendation(ctx context.Context, userID pgtype.UUID) ([]LearningUserUnitState, error) {
	rows, err := q.db.Query(ctx, listLearningStatesForRecommendation, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningUserUnitState{}
	for rows.Next() {
		var i LearningUserUnitState
		if err := rows.Scan(
			&i.UserID,
			&i.CoarseUnitID,
			&i.IsTarget,
			&i.TargetPriority,
			&i.Status,
			&i.MasteryScore,
			&i.LastProgressQuality,
			&i.NextReviewAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMasteredTargetFillVideoCandidates = `-- name: ListMasteredTargetFillVideoCandidates :many
with matched as (
  select
    rvu.video_id,
    max(rvu.duration_ms)::integer as duration_ms,
    count(distinct rvu.coarse_unit_id)::integer as matched_unit_count,
    coalesce(sum(rvu.mention_count), 0)::bigint as total_mention_count,
    coalesce(max(rvu.coverage_ratio), 0)::numeric(10,5) as max_coverage_ratio,
    coalesce(avg(rvu.mapped_span_ratio), 0)::numeric(10,5) as mapped_span_ratio
  from learning.user_unit_states as states
  join recommendation.v_video_unit_recall_index as rvu
    on rvu.coarse_unit_id = states.coarse_unit_id
  where states.user_id = $1
    and states.is_target = true
    and states.status = 'mastered'
    and not (rvu.video_id = any($3::uuid[]))
  group by rvu.video_id
)
select
  matched.video_id,
  matched.duration_ms,
  matched.matched_unit_count,
  matched.total_mention_count,
  matched.max_coverage_ratio,
  matched.mapped_span_ratio,
  coalesce(stats.view_count, 0)::bigint as view_count,
  coalesce(stats.like_count, 0)::bigint as like_count,
  coalesce(stats.favorite_count, 0)::bigint as favorite_count,
  serving.last_served_at,
  coalesce(serving.served_count, 0)::integer as served_count,
  user_state.last_watched_at,
  coalesce(user_state.watch_count, 0)::integer as watch_count,
  coalesce(user_state.completed_count, 0)::integer as completed_count,
  coalesce(user_state.max_position_ms, 0)::integer as max_position_ms
from matched
left join catalog.video_engagement_stats as stats
  on stats.video_id = matched.video_id
left join recommendation.user_video_serving_states as serving
  on serving.user_id = $1
 and serving.video_id = matched.video_id
left join catalog.video_user_states as user_state
  on user_state.user_id = $1
 and user_state.video_id = matched.video_id
order by
  matched.matched_unit_count desc,
  matched.total_mention_count desc,
  matched.max_coverage_ratio desc,
  matched.mapped_span_ratio desc,
  matched.video_id asc
limit $2::integer
`

type ListMasteredTargetFillVideoCandidatesParams struct {
	UserID           pgtype.UUID   `json:"user_id"`
	FillLimit        int32         `json:"fill_limit"`
	ExcludedVideoIds []pgtype.UUID `json:"excluded_video_ids"`
}

type ListMasteredTargetFillVideoCandidatesRow struct {
	VideoID           pgtype.UUID        `json:"video_id"`
	DurationMs        int32              `json:"duration_ms"`
	MatchedUnitCount  int32              `json:"matched_unit_count"`
	TotalMentionCount int64              `json:"total_mention_count"`
	MaxCoverageRatio  pgtype.Numeric     `json:"max_coverage_ratio"`
	MappedSpanRatio   pgtype.Numeric     `json:"mapped_span_ratio"`
	ViewCount         int64              `json:"view_count"`
	LikeCount         int64              `json:"like_count"`
	FavoriteCount     int64              `json:"favorite_count"`
	LastServedAt      pgtype.Timestamptz `json:"last_served_at"`
	ServedCount       int32              `json:"served_count"`
	LastWatchedAt     pgtype.Timestamptz `json:"last_watched_at"`
	WatchCount        int32              `json:"watch_count"`
	CompletedCount    int32              `json:"completed_count"`
	MaxPositionMs     int32              `json:"max_position_ms"`
}

func (q *Queries) ListMasteredTargetFillVideoCandidates(ctx context.Context, arg ListMasteredTargetFillVideoCandidatesParams) ([]ListMasteredTargetFillVideoCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listMasteredTargetFillVideoCandidates, arg.UserID, arg.FillLimit, arg.ExcludedVideoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMasteredTargetFillVideoCandidatesRow{}
	for rows.Next() {
		var i ListMasteredTargetFillVideoCandidatesRow
		if err := rows.Scan(
			&i.VideoID,
			&i.DurationMs,
			&i.MatchedUnitCount,
			&i.TotalMentionCount,
			&i.MaxCoverageRatio,
			&i.MappedSpanRatio,
			&i.ViewCount,
			&i.LikeCount,
			&i.FavoriteCount,
			&i.LastServedAt,
			&i.ServedCount,
			&i.LastWatchedAt,
			&i.WatchCount,
			&i.CompletedCount,
			&i.MaxPositionMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPopularFillVideoCandidates = `-- name: ListPopularFillVideoCandidates :many
select
  videos.video_id,
  videos.duration_ms,
  0::integer as matched_unit_count,
  0::bigint as total_mention_count,
  0::numeric(10,5) as max_coverage_ratio,
  0::numeric(10,5) as mapped_span_ratio,
  coalesce(stats.view_count, 0)::bigint as view_count,
  coalesce(stats.like_count, 0)::bigint as like_count,
  coalesce(stats.favorite_count, 0)::bigint as favorite_count,
  serving.last_served_at,
  coalesce(serving.served_count, 0)::integer as served_count,
  user_state.last_watched_at,
  coalesce(user_state.watch_count, 0)::integer as watch_count,
  coalesce(user_state.completed_count, 0)::integer as completed_count,
  coalesce(user_state.max_position_ms, 0)::integer as max_position_ms
from catalog.videos as videos
left join catalog.video_engagement_stats as stats
  on stats.video_id = videos.video_id
left join recommendation.user_video_serving_states as serving
  on serving.user_id = $1
 and serving.video_id = videos.video_id
left join catalog.video_user_states as user_state
  on user_state.user_id = $1
 and user_state.video_id = videos.video_id
where videos.status = 'active'
  and videos.visibility_status = 'public'
  and (videos.publish_at is null or videos.publish_at <= now())
  and not (videos.video_id = any($2::uuid[]))
order by
  coalesce(stats.view_count, 0) desc,
  coalesce(stats.like_count, 0) desc,
  coalesce(stats.favorite_count, 0) desc,
  videos.video_id asc
limit $3::integer
`

type ListPopularFillVideoCandidatesParams struct {
	UserID           pgtype.UUID   `json:"user_id"`
	ExcludedVideoIds []pgtype.UUID `json:"excluded_video_ids"`
	FillLimit        int32         `json:"fill_limit"`
}

type ListPopularFillVideoCandidatesRow struct {
	VideoID           pgtype.UUID        `json:"video_id"`
	DurationMs        int32              `json:"duration_ms"`
	MatchedUnitCount  int32              `json:"matched_unit_count"`
	TotalMentionCount int64              `json:"total_mention_count"`
	MaxCoverageRatio  pgtype.Numeric     `json:"max_coverage_ratio"`
	MappedSpanRatio   pgtype.Numeric     `json:"mapped_span_ratio"`
	ViewCount         int64              `json:"view_count"`
	LikeCount         int64              `json:"like_count"`
	FavoriteCount     int64              `json:"favorite_count"`
	LastServedAt      pgtype.Timestamptz `json:"last_served_at"`
	ServedCount       int32              `json:"served_count"`
	LastWatchedAt     pgtype.Timestamptz `json:"last_watched_at"`
	WatchCount        int32              `json:"watch_count"`
	CompletedCount    int32              `json:"completed_count"`
	MaxPositionMs     int32              `json:"max_position_ms"`
}

func (q *Queries) ListPopularFillVideoCandidates(ctx context.Context, arg ListPopularFillVideoCandidatesParams) ([]ListPopularFillVideoCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listPopularFillVideoCandidates, arg.UserID, arg.ExcludedVideoIds, arg.FillLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPopularFillVideoCandidatesRow{}
	for rows.Next() {
		var i ListPopularFillVideoCandidatesRow
		if err := rows.Scan(
			&i.VideoID,
			&i.DurationMs,
			&i.MatchedUnitCount,
			&i.TotalMentionCount,
			&i.MaxCoverageRatio,
			&i.MappedSpanRatio,
			&i.ViewCount,
			&i.LikeCount,
			&i.FavoriteCount,
			&i.LastServedAt,
			&i.ServedCount,
			&i.LastWatchedAt,
			&i.WatchCount,
			&i.CompletedCount,
			&i.MaxPositionMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitVideoInventoryByUnitIDs = `-- name: ListUnitVideoInventoryByUnitIDs :many
select
  coarse_unit_id,
  distinct_video_count,
  avg_mention_count,
  avg_sentence_count,
  avg_coverage_ms,
  avg_coverage_ratio,
  strong_video_count,
  supply_grade,
  updated_at
from recommendation.v_unit_video_inventory
where coarse_unit_id = any($1::bigint[])
order by coarse_unit_id asc
`

func (q *Queries) ListUnitVideoInventoryByUnitIDs(ctx context.Context, coarseUnitIds []int64) ([]RecommendationVUnitVideoInventory, error) {
	rows, err := q.db.Query(ctx, listUnitVideoInventoryByUnitIDs, coarseUnitIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecommendationVUnitVideoInventory{}
	for rows.Next() {
		var i RecommendationVUnitVideoInventory
		if err := rows.Scan(
			&i.CoarseUnitID,
			&i.DistinctVideoCount,
			&i.AvgMentionCount,
			&i.AvgSentenceCount,
			&i.AvgCoverageMs,
			&i.AvgCoverageRatio,
			&i.StrongVideoCount,
			&i.SupplyGrade,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRecallQueueCandidates = `-- name: ListUserRecallQueueCandidates :many
with bucketed as (
  select
    queue.user_id,
    queue.coarse_unit_id,
    queue.status,
    queue.target_priority,
    queue.mastery_score,
    queue.last_progress_quality,
    queue.next_review_at,
    queue.supply_grade,
    queue.state_updated_at,
    serving.last_served_at,
    coalesce(serving.served_count, 0)::integer as served_count,
    case
      when queue.last_progress_quality is not null and queue.last_progress_quality < 3 then 'hard_review'
      when queue.next_review_at is not null and queue.next_review_at <= $1::timestamptz then 'hard_review'
      when queue.status = 'new' and queue.supply_grade <> 'none' then 'new_now'
      when queue.next_review_at is not null and queue.next_review_at <= $1::timestamptz + interval '72 hours' then 'soft_review'
      when queue.mastery_score < 0.6000 then 'soft_review'
      when queue.last_progress_quality is not null and queue.last_progress_quality < 4 then 'soft_review'
      else 'near_future'
    end as bucket
  from recommendation.user_unit_recall_queue as queue
  left join recommendation.user_unit_serving_states as serving
    on serving.user_id = queue.user_id
   and serving.coarse_unit_id = queue.coarse_unit_id
  where queue.user_id = $2
),
scored as (
  select
    bucketed.user_id, bucketed.coarse_unit_id, bucketed.status, bucketed.target_priority, bucketed.mastery_score, bucketed.last_progress_quality, bucketed.next_review_at, bucketed.supply_grade, bucketed.state_updated_at, bucketed.last_served_at, bucketed.served_count, bucketed.bucket,
    (
      case bucket
        when 'hard_review' then 1.00
        when 'new_now' then 0.85
        when 'soft_review' then 0.65
        else 0.45
      end
      + bucketed.target_priority
      + case bucketed.supply_grade
          when 'strong' then 0.08
          when 'ok' then 0.04
          when 'weak' then -0.03
          else -0.08
        end
      + case
          when bucketed.last_served_at is null then 0.12
          when bucketed.last_served_at <= $1::timestamptz - interval '7 days' then 0.08
          when bucketed.last_served_at <= $1::timestamptz - interval '24 hours' then 0.04
          else -0.15
        end
      - least(bucketed.served_count::numeric / 10.0, 0.25)
    )::numeric(10,6) as dynamic_priority
  from bucketed
),
ranked as (
  select user_id, coarse_unit_id, status, target_priority, mastery_score, last_progress_quality, next_review_at, supply_grade, state_updated_at, last_served_at, served_count, bucket, dynamic_priority, bucket_rank
  from (
    select
      scored.user_id, scored.coarse_unit_id, scored.status, scored.target_priority, scored.mastery_score, scored.last_progress_quality, scored.next_review_at, scored.supply_grade, scored.state_updated_at, scored.last_served_at, scored.served_count, scored.bucket, scored.dynamic_priority,
      row_number() over (
        partition by bucket
        order by dynamic_priority desc, last_served_at asc nulls first, coarse_unit_id asc
      )::integer as bucket_rank
    from scored
    where supply_grade <> 'none'
  ) as supplied_ranked
  where bucket_rank <= $3::integer
  union all
  select user_id, coarse_unit_id, status, target_priority, mastery_score, last_progress_quality, next_review_at, supply_grade, state_updated_at, last_served_at, served_count, bucket, dynamic_priority, bucket_rank
  from (
    select
      scored.user_id, scored.coarse_unit_id, scored.status, scored.target_priority, scored.mastery_score, scored.last_progress_quality, scored.next_review_at, scored.supply_grade, scored.state_updated_at, scored.last_served_at, scored.served_count, scored.bucket, scored.dynamic_priority,
      row_number() over (
        partition by bucket
        order by dynamic_priority desc, last_served_at asc nulls first, coarse_unit_id asc
      )::integer as bucket_rank
    from scored
    where supply_grade = 'none'
  ) as no_supply_ranked
  where bucket_rank <= $4::integer
)
select
  user_id,
  coarse_unit_id,
  status,
  target_priority,
  mastery_score,
  last_progress_quality,
  next_review_at,
  supply_grade,
  state_updated_at,
  last_served_at,
  served_count,
  bucket,
  dynamic_priority,
  bucket_rank
from ranked
order by
  case bucket
    when 'hard_review' then 0
    when 'new_now' then 1
    when 'soft_review' then 2
    else 3
  end,
  case when supply_grade = 'none' then 1 else 0 end,
  dynamic_priority desc,
  last_served_at asc nulls first,
  coarse_unit_id asc
`

type ListUserRecallQueueCandidatesParams struct {
	NowAt                  pgtype.Timestamptz `json:"now_at"`
	UserID                 pgtype.UUID        `json:"user_id"`
	SuppliedPerBucketLimit int32              `json:"supplied_per_bucket_limit"`
	NoSupplyPerBucketLimit int32              `json:"no_supply_per_bucket_limit"`
}

type ListUserRecallQueueCandidatesRow struct {
	UserID              pgtype.UUID        `json:"user_id"`
	CoarseUnitID        int64              `json:"coarse_unit_id"`
	Status              string             `json:"status"`
	TargetPriority      pgtype.Numeric     `json:"target_priority"`
	MasteryScore        pgtype.Numeric     `json:"mastery_score"`
	LastProgressQuality pgtype.Int2        `json:"last_progress_quality"`
	NextReviewAt        pgtype.Timestamptz `json:"next_review_at"`
	SupplyGrade         string             `json:"supply_grade"`
	StateUpdatedAt      pgtype.Timestamptz `json:"state_updated_at"`
	LastServedAt        pgtype.Timestamptz `json:"last_served_at"`
	ServedCount         int32              `json:"served_count"`
	Bucket              string             `json:"bucket"`
	DynamicPriority     pgtype.Numeric     `json:"dynamic_priority"`
	BucketRank          int32              `json:"bucket_rank"`
}

func (q *Queries) ListUserRecallQueueCandidates(ctx context.Context, arg ListUserRecallQueueCandidatesParams) ([]ListUserRecallQueueCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listUserRecallQueueCandidates,
		arg.NowAt,
		arg.UserID,
		arg.SuppliedPerBucketLimit,
		arg.NoSupplyPerBucketLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserRecallQueueCandidatesRow{}
	for rows.Next() {
		var i ListUserRecallQueueCandidatesRow
		if err := rows.Scan(
			&i.UserID,
			&i.CoarseUnitID,
			&i.Status,
			&i.TargetPriority,
			&i.MasteryScore,
			&i.LastProgressQuality,
			&i.NextReviewAt,
			&i.SupplyGrade,
			&i.StateUpdatedAt,
			&i.LastServedAt,
			&i.ServedCount,
			&i.Bucket,
			&i.DynamicPriority,
			&i.BucketRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserUnitServingStatesByUnitIDs = `-- name: ListUserUnitServingStatesByUnitIDs :many
select user_id, coarse_unit_id, last_served_at, last_run_id, served_count, created_at, updated_at
from recommendation.user_unit_serving_states
where user_id = $1
  and coarse_unit_id = any($2::bigint[])
order by coarse_unit_id asc
`

type ListUserUnitServingStatesByUnitIDsParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	CoarseUnitIds []int64     `json:"coarse_unit_ids"`
}

func (q *Queries) ListUserUnitServingStatesByUnitIDs(ctx context.Context, arg ListUserUnitServingStatesByUnitIDsParams) ([]RecommendationUserUnitServingState, error) {
	rows, err := q.db.Query(ctx, listUserUnitServingStatesByUnitIDs, arg.UserID, arg.CoarseUnitIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecommendationUserUnitServingState{}
	for rows.Next() {
		var i RecommendationUserUnitServingState
		if err := rows.Scan(
			&i.UserID,
			&i.CoarseUnitID,
			&i.LastServedAt,
			&i.LastRunID,
			&i.ServedCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserVideoServingStatesByVideoIDs = `-- name: ListUserVideoServingStatesByVideoIDs :many
select user_id, video_id, last_served_at, last_run_id, served_count, created_at, updated_at
from recommendation.user_video_serving_states
where user_id = $1
  and video_id = any($2::uuid[])
order by video_id asc
`

type ListUserVideoServingStatesByVideoIDsParams struct {
	UserID   pgtype.UUID   `json:"user_id"`
	VideoIds []pgtype.UUID `json:"video_ids"`
}

func (q *Queries) ListUserVideoServingStatesByVideoIDs(ctx context.Context, arg ListUserVideoServingStatesByVideoIDsParams) ([]RecommendationUserVideoServingState, error) {
	rows, err := q.db.Query(ctx, listUserVideoServingStatesByVideoIDs, arg.UserID, arg.VideoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecommendationUserVideoServingState{}
	for rows.Next() {
		var i RecommendationUserVideoServingState
		if err := rows.Scan(
			&i.UserID,
			&i.VideoID,
			&i.LastServedAt,
			&i.LastRunID,
			&i.ServedCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideoUnitRecallRowsByUnitIDs = `-- name: ListVideoUnitRecallRowsByUnitIDs :many
select
  video_id,
  coarse_unit_id,
  mention_count,
  sentence_count,
  coverage_ms,
  coverage_ratio,
  sentence_indexes,
  best_evidence_sentence_index,
  best_evidence_span_index,
  best_evidence_start_ms,
  best_evidence_end_ms,
  best_evidence_candidate_score,
  best_evidence_target_text,
  duration_ms,
  mapped_span_ratio,
  content_quality_score,
  rank_within_unit
from recommendation.v_video_unit_recall_index
where coarse_unit_id = any($1::bigint[])
  and rank_within_unit <= $2::integer
order by coarse_unit_id asc, rank_within_unit asc
`

type ListVideoUnitRecallRowsByUnitIDsParams struct {
	CoarseUnitIds []int64 `json:"coarse_unit_ids"`
	PerUnitLimit  int32   `json:"per_unit_limit"`
}

type ListVideoUnitRecallRowsByUnitIDsRow struct {
	VideoID                    pgtype.UUID    `json:"video_id"`
	CoarseUnitID               int64          `json:"coarse_unit_id"`
	MentionCount               int32          `json:"mention_count"`
	SentenceCount              int32          `json:"sentence_count"`
	CoverageMs                 int32          `json:"coverage_ms"`
	CoverageRatio              pgtype.Numeric `json:"coverage_ratio"`
	SentenceIndexes            []int32        `json:"sentence_indexes"`
	BestEvidenceSentenceIndex  int32          `json:"best_evidence_sentence_index"`
	BestEvidenceSpanIndex      int32          `json:"best_evidence_span_index"`
	BestEvidenceStartMs        pgtype.Int4    `json:"best_evidence_start_ms"`
	BestEvidenceEndMs          pgtype.Int4    `json:"best_evidence_end_ms"`
	BestEvidenceCandidateScore pgtype.Numeric `json:"best_evidence_candidate_score"`
	BestEvidenceTargetText     pgtype.Text    `json:"best_evidence_target_text"`
	DurationMs                 int32          `json:"duration_ms"`
	MappedSpanRatio            pgtype.Numeric `json:"mapped_span_ratio"`
	ContentQualityScore        pgtype.Numeric `json:"content_quality_score"`
	RankWithinUnit             int32          `json:"rank_within_unit"`
}

func (q *Queries) ListVideoUnitRecallRowsByUnitIDs(ctx context.Context, arg ListVideoUnitRecallRowsByUnitIDsParams) ([]ListVideoUnitRecallRowsByUnitIDsRow, error) {
	rows, err := q.db.Query(ctx, listVideoUnitRecallRowsByUnitIDs, arg.CoarseUnitIds, arg.PerUnitLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVideoUnitRecallRowsByUnitIDsRow{}
	for rows.Next() {
		var i ListVideoUnitRecallRowsByUnitIDsRow
		if err := rows.Scan(
			&i.VideoID,
			&i.CoarseUnitID,
			&i.MentionCount,
			&i.SentenceCount,
			&i.CoverageMs,
			&i.CoverageRatio,
			&i.SentenceIndexes,
			&i.BestEvidenceSentenceIndex,
			&i.BestEvidenceSpanIndex,
			&i.BestEvidenceStartMs,
			&i.BestEvidenceEndMs,
			&i.BestEvidenceCandidateScore,
			&i.BestEvidenceTargetText,
			&i.DurationMs,
			&i.MappedSpanRatio,
			&i.ContentQualityScore,
			&i.RankWithinUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideoUserStatesByUserAndVideoIDs = `-- name: ListVideoUserStatesByUserAndVideoIDs :many
select user_id, video_id, last_watched_at, watch_count, completed_count, last_position_ms, max_position_ms, total_watch_ms
from catalog.video_user_states
where user_id = $1
  and video_id = any($2::uuid[])
order by video_id asc
`

type ListVideoUserStatesByUserAndVideoIDsParams struct {
	UserID   pgtype.UUID   `json:"user_id"`
	VideoIds []pgtype.UUID `json:"video_ids"`
}

func (q *Queries) ListVideoUserStatesByUserAndVideoIDs(ctx context.Context, arg ListVideoUserStatesByUserAndVideoIDsParams) ([]CatalogVideoUserState, error) {
	rows, err := q.db.Query(ctx, listVideoUserStatesByUserAndVideoIDs, arg.UserID, arg.VideoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogVideoUserState{}
	for rows.Next() {
		var i CatalogVideoUserState
		if err := rows.Scan(
			&i.UserID,
			&i.VideoID,
			&i.LastWatchedAt,
			&i.WatchCount,
			&i.CompletedCount,
			&i.LastPositionMs,
			&i.MaxPositionMs,
			&i.TotalWatchMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
