// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recommendation_reads.sql

package recommendationsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listLearningStatesForRecommendation = `-- name: ListLearningStatesForRecommendation :many
select
  user_id,
  coarse_unit_id,
  is_target,
  target_priority,
  status,
  mastery_score,
  last_progress_quality,
  next_review_at,
  updated_at
from learning.user_unit_states
where user_id = $1
  and is_target = true
  and status <> 'suspended'
order by target_priority desc, coarse_unit_id asc
`

func (q *Queries) ListLearningStatesForRecommendation(ctx context.Context, userID pgtype.UUID) ([]LearningUserUnitState, error) {
	rows, err := q.db.Query(ctx, listLearningStatesForRecommendation, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningUserUnitState{}
	for rows.Next() {
		var i LearningUserUnitState
		if err := rows.Scan(
			&i.UserID,
			&i.CoarseUnitID,
			&i.IsTarget,
			&i.TargetPriority,
			&i.Status,
			&i.MasteryScore,
			&i.LastProgressQuality,
			&i.NextReviewAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendableVideoUnitsByUnitIDs = `-- name: ListRecommendableVideoUnitsByUnitIDs :many
select
  video_id,
  coarse_unit_id,
  mention_count,
  sentence_count,
  coverage_ms,
  coverage_ratio,
  sentence_indexes,
  best_evidence_sentence_index,
  best_evidence_span_index,
  best_evidence_candidate_score,
  best_evidence_target_text,
  duration_ms,
  mapped_span_ratio
from recommendation.v_recommendable_video_units
where coarse_unit_id = any($1::bigint[])
order by coarse_unit_id asc, coverage_ratio desc, mention_count desc
`

type ListRecommendableVideoUnitsByUnitIDsRow struct {
	VideoID                    pgtype.UUID    `json:"video_id"`
	CoarseUnitID               pgtype.Int8    `json:"coarse_unit_id"`
	MentionCount               pgtype.Int4    `json:"mention_count"`
	SentenceCount              pgtype.Int4    `json:"sentence_count"`
	CoverageMs                 pgtype.Int4    `json:"coverage_ms"`
	CoverageRatio              pgtype.Numeric `json:"coverage_ratio"`
	SentenceIndexes            []int32        `json:"sentence_indexes"`
	BestEvidenceSentenceIndex  pgtype.Int4    `json:"best_evidence_sentence_index"`
	BestEvidenceSpanIndex      pgtype.Int4    `json:"best_evidence_span_index"`
	BestEvidenceCandidateScore pgtype.Numeric `json:"best_evidence_candidate_score"`
	BestEvidenceTargetText     pgtype.Text    `json:"best_evidence_target_text"`
	DurationMs                 pgtype.Int4    `json:"duration_ms"`
	MappedSpanRatio            pgtype.Numeric `json:"mapped_span_ratio"`
}

func (q *Queries) ListRecommendableVideoUnitsByUnitIDs(ctx context.Context, coarseUnitIds []int64) ([]ListRecommendableVideoUnitsByUnitIDsRow, error) {
	rows, err := q.db.Query(ctx, listRecommendableVideoUnitsByUnitIDs, coarseUnitIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecommendableVideoUnitsByUnitIDsRow{}
	for rows.Next() {
		var i ListRecommendableVideoUnitsByUnitIDsRow
		if err := rows.Scan(
			&i.VideoID,
			&i.CoarseUnitID,
			&i.MentionCount,
			&i.SentenceCount,
			&i.CoverageMs,
			&i.CoverageRatio,
			&i.SentenceIndexes,
			&i.BestEvidenceSentenceIndex,
			&i.BestEvidenceSpanIndex,
			&i.BestEvidenceCandidateScore,
			&i.BestEvidenceTargetText,
			&i.DurationMs,
			&i.MappedSpanRatio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSemanticSpansByRefs = `-- name: ListSemanticSpansByRefs :many
with input as (
  select distinct
    (item->>'video_id')::uuid as video_id,
    (item->>'coarse_unit_id')::bigint as coarse_unit_id,
    (item->>'sentence_index')::integer as sentence_index,
    (item->>'span_index')::integer as span_index
  from jsonb_array_elements($1::jsonb) as refs(item)
)
select
  spans.video_id,
  spans.sentence_index,
  spans.span_index,
  spans.coarse_unit_id,
  spans.start_ms,
  spans.end_ms,
  spans.surface_text,
  spans.explanation,
  spans.base_form,
  spans.translation,
  spans.dictionary,
  spans.mapping_reason
from catalog.video_semantic_spans spans
join input
  on input.video_id = spans.video_id
 and input.coarse_unit_id = spans.coarse_unit_id
 and input.sentence_index = spans.sentence_index
 and input.span_index = spans.span_index
order by spans.video_id, spans.coarse_unit_id, spans.sentence_index, spans.span_index
`

func (q *Queries) ListSemanticSpansByRefs(ctx context.Context, refs []byte) ([]CatalogVideoSemanticSpan, error) {
	rows, err := q.db.Query(ctx, listSemanticSpansByRefs, refs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogVideoSemanticSpan{}
	for rows.Next() {
		var i CatalogVideoSemanticSpan
		if err := rows.Scan(
			&i.VideoID,
			&i.SentenceIndex,
			&i.SpanIndex,
			&i.CoarseUnitID,
			&i.StartMs,
			&i.EndMs,
			&i.SurfaceText,
			&i.Explanation,
			&i.BaseForm,
			&i.Translation,
			&i.Dictionary,
			&i.MappingReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptSentencesByRefs = `-- name: ListTranscriptSentencesByRefs :many
with input as (
  select distinct
    (item->>'video_id')::uuid as video_id,
    (item->>'sentence_index')::integer as sentence_index
  from jsonb_array_elements($1::jsonb) as refs(item)
)
select
  sentences.video_id,
  sentences.sentence_index,
  sentences.start_ms,
  sentences.end_ms,
  sentences.text,
  sentences.translation
from catalog.video_transcript_sentences sentences
join input
  on input.video_id = sentences.video_id
 and input.sentence_index = sentences.sentence_index
order by sentences.video_id, sentences.sentence_index
`

func (q *Queries) ListTranscriptSentencesByRefs(ctx context.Context, refs []byte) ([]CatalogVideoTranscriptSentence, error) {
	rows, err := q.db.Query(ctx, listTranscriptSentencesByRefs, refs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogVideoTranscriptSentence{}
	for rows.Next() {
		var i CatalogVideoTranscriptSentence
		if err := rows.Scan(
			&i.VideoID,
			&i.SentenceIndex,
			&i.StartMs,
			&i.EndMs,
			&i.Text,
			&i.Translation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitVideoInventoryByUnitIDs = `-- name: ListUnitVideoInventoryByUnitIDs :many
select
  coarse_unit_id,
  distinct_video_count,
  avg_mention_count,
  avg_sentence_count,
  avg_coverage_ms,
  avg_coverage_ratio,
  strong_video_count,
  supply_grade,
  updated_at
from recommendation.v_unit_video_inventory
where coarse_unit_id = any($1::bigint[])
order by coarse_unit_id asc
`

func (q *Queries) ListUnitVideoInventoryByUnitIDs(ctx context.Context, coarseUnitIds []int64) ([]RecommendationVUnitVideoInventory, error) {
	rows, err := q.db.Query(ctx, listUnitVideoInventoryByUnitIDs, coarseUnitIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecommendationVUnitVideoInventory{}
	for rows.Next() {
		var i RecommendationVUnitVideoInventory
		if err := rows.Scan(
			&i.CoarseUnitID,
			&i.DistinctVideoCount,
			&i.AvgMentionCount,
			&i.AvgSentenceCount,
			&i.AvgCoverageMs,
			&i.AvgCoverageRatio,
			&i.StrongVideoCount,
			&i.SupplyGrade,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserUnitServingStatesByUnitIDs = `-- name: ListUserUnitServingStatesByUnitIDs :many
select user_id, coarse_unit_id, last_served_at, last_run_id, served_count, created_at, updated_at
from recommendation.user_unit_serving_states
where user_id = $1
  and coarse_unit_id = any($2::bigint[])
order by coarse_unit_id asc
`

type ListUserUnitServingStatesByUnitIDsParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	CoarseUnitIds []int64     `json:"coarse_unit_ids"`
}

func (q *Queries) ListUserUnitServingStatesByUnitIDs(ctx context.Context, arg ListUserUnitServingStatesByUnitIDsParams) ([]RecommendationUserUnitServingState, error) {
	rows, err := q.db.Query(ctx, listUserUnitServingStatesByUnitIDs, arg.UserID, arg.CoarseUnitIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecommendationUserUnitServingState{}
	for rows.Next() {
		var i RecommendationUserUnitServingState
		if err := rows.Scan(
			&i.UserID,
			&i.CoarseUnitID,
			&i.LastServedAt,
			&i.LastRunID,
			&i.ServedCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserVideoServingStatesByVideoIDs = `-- name: ListUserVideoServingStatesByVideoIDs :many
select user_id, video_id, last_served_at, last_run_id, served_count, created_at, updated_at
from recommendation.user_video_serving_states
where user_id = $1
  and video_id = any($2::uuid[])
order by video_id asc
`

type ListUserVideoServingStatesByVideoIDsParams struct {
	UserID   pgtype.UUID   `json:"user_id"`
	VideoIds []pgtype.UUID `json:"video_ids"`
}

func (q *Queries) ListUserVideoServingStatesByVideoIDs(ctx context.Context, arg ListUserVideoServingStatesByVideoIDsParams) ([]RecommendationUserVideoServingState, error) {
	rows, err := q.db.Query(ctx, listUserVideoServingStatesByVideoIDs, arg.UserID, arg.VideoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecommendationUserVideoServingState{}
	for rows.Next() {
		var i RecommendationUserVideoServingState
		if err := rows.Scan(
			&i.UserID,
			&i.VideoID,
			&i.LastServedAt,
			&i.LastRunID,
			&i.ServedCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideoUserStatesByUserAndVideoIDs = `-- name: ListVideoUserStatesByUserAndVideoIDs :many
select user_id, video_id, last_watched_at, watch_count, completed_count, last_position_ms, max_position_ms, total_watch_ms
from catalog.video_user_states
where user_id = $1
  and video_id = any($2::uuid[])
order by video_id asc
`

type ListVideoUserStatesByUserAndVideoIDsParams struct {
	UserID   pgtype.UUID   `json:"user_id"`
	VideoIds []pgtype.UUID `json:"video_ids"`
}

func (q *Queries) ListVideoUserStatesByUserAndVideoIDs(ctx context.Context, arg ListVideoUserStatesByUserAndVideoIDsParams) ([]CatalogVideoUserState, error) {
	rows, err := q.db.Query(ctx, listVideoUserStatesByUserAndVideoIDs, arg.UserID, arg.VideoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogVideoUserState{}
	for rows.Next() {
		var i CatalogVideoUserState
		if err := rows.Scan(
			&i.UserID,
			&i.VideoID,
			&i.LastWatchedAt,
			&i.WatchCount,
			&i.CompletedCount,
			&i.LastPositionMs,
			&i.MaxPositionMs,
			&i.TotalWatchMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
