// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recommendation_writes.sql

package recommendationsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const incrementUserUnitServingStates = `-- name: IncrementUserUnitServingStates :exec
insert into recommendation.user_unit_serving_states (
  user_id,
  coarse_unit_id,
  last_served_at,
  last_run_id,
  served_count,
  updated_at
) 
select
  $1,
  input.coarse_unit_id,
  $2,
  $3,
  1,
  now()
from (
  select distinct unnest($4::bigint[]) as coarse_unit_id
) input
where input.coarse_unit_id is not null
on conflict (user_id, coarse_unit_id) do update
set
  last_served_at = excluded.last_served_at,
  last_run_id = excluded.last_run_id,
  served_count = recommendation.user_unit_serving_states.served_count + 1,
  updated_at = now()
`

type IncrementUserUnitServingStatesParams struct {
	UserID        pgtype.UUID        `json:"user_id"`
	LastServedAt  pgtype.Timestamptz `json:"last_served_at"`
	LastRunID     pgtype.UUID        `json:"last_run_id"`
	CoarseUnitIds []int64            `json:"coarse_unit_ids"`
}

func (q *Queries) IncrementUserUnitServingStates(ctx context.Context, arg IncrementUserUnitServingStatesParams) error {
	_, err := q.db.Exec(ctx, incrementUserUnitServingStates,
		arg.UserID,
		arg.LastServedAt,
		arg.LastRunID,
		arg.CoarseUnitIds,
	)
	return err
}

const incrementUserVideoServingStates = `-- name: IncrementUserVideoServingStates :exec
insert into recommendation.user_video_serving_states (
  user_id,
  video_id,
  last_served_at,
  last_run_id,
  served_count,
  updated_at
)
select
  $1,
  input.video_id,
  $2,
  $3,
  1,
  now()
from (
  select distinct unnest($4::uuid[]) as video_id
) input
where input.video_id is not null
on conflict (user_id, video_id) do update
set
  last_served_at = excluded.last_served_at,
  last_run_id = excluded.last_run_id,
  served_count = recommendation.user_video_serving_states.served_count + 1,
  updated_at = now()
`

type IncrementUserVideoServingStatesParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	LastServedAt pgtype.Timestamptz `json:"last_served_at"`
	LastRunID    pgtype.UUID        `json:"last_run_id"`
	VideoIds     []pgtype.UUID      `json:"video_ids"`
}

func (q *Queries) IncrementUserVideoServingStates(ctx context.Context, arg IncrementUserVideoServingStatesParams) error {
	_, err := q.db.Exec(ctx, incrementUserVideoServingStates,
		arg.UserID,
		arg.LastServedAt,
		arg.LastRunID,
		arg.VideoIds,
	)
	return err
}

const insertVideoRecommendationItems = `-- name: InsertVideoRecommendationItems :exec
insert into recommendation.video_recommendation_items (
  run_id,
  rank,
  video_id,
  score,
  primary_lane,
  dominant_role,
  dominant_unit_id,
  reason_codes,
  learning_units
)
select
  input.run_id,
  input.rank,
  input.video_id,
  input.score,
  nullif(input.primary_lane, ''),
  nullif(input.dominant_role, ''),
  input.dominant_unit_id,
  coalesce(input.reason_codes, array[]::text[]),
  coalesce(input.learning_units, '[]'::jsonb)
from (
  select
    (item->>'run_id')::uuid as run_id,
    (item->>'rank')::integer as rank,
    (item->>'video_id')::uuid as video_id,
    (item->>'score')::numeric as score,
    item->>'primary_lane' as primary_lane,
    item->>'dominant_role' as dominant_role,
    case
      when item ? 'dominant_unit_id' and item->>'dominant_unit_id' is not null
      then (item->>'dominant_unit_id')::bigint
      else null
    end as dominant_unit_id,
    (
      select array_agg(value::text order by ordinality)
      from jsonb_array_elements_text(coalesce(item->'reason_codes', '[]'::jsonb)) with ordinality as codes(value, ordinality)
    ) as reason_codes,
    item->'learning_units' as learning_units
  from jsonb_array_elements($1::jsonb) as items(item)
) input
`

func (q *Queries) InsertVideoRecommendationItems(ctx context.Context, items []byte) error {
	_, err := q.db.Exec(ctx, insertVideoRecommendationItems, items)
	return err
}

const insertVideoRecommendationRun = `-- name: InsertVideoRecommendationRun :exec
insert into recommendation.video_recommendation_runs (
  run_id,
  user_id,
  request_context,
  session_mode,
  selector_mode,
  planner_snapshot,
  lane_budget_snapshot,
  candidate_summary,
  underfilled,
  result_count
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
`

type InsertVideoRecommendationRunParams struct {
	RunID              pgtype.UUID `json:"run_id"`
	UserID             pgtype.UUID `json:"user_id"`
	RequestContext     []byte      `json:"request_context"`
	SessionMode        pgtype.Text `json:"session_mode"`
	SelectorMode       pgtype.Text `json:"selector_mode"`
	PlannerSnapshot    []byte      `json:"planner_snapshot"`
	LaneBudgetSnapshot []byte      `json:"lane_budget_snapshot"`
	CandidateSummary   []byte      `json:"candidate_summary"`
	Underfilled        bool        `json:"underfilled"`
	ResultCount        int32       `json:"result_count"`
}

func (q *Queries) InsertVideoRecommendationRun(ctx context.Context, arg InsertVideoRecommendationRunParams) error {
	_, err := q.db.Exec(ctx, insertVideoRecommendationRun,
		arg.RunID,
		arg.UserID,
		arg.RequestContext,
		arg.SessionMode,
		arg.SelectorMode,
		arg.PlannerSnapshot,
		arg.LaneBudgetSnapshot,
		arg.CandidateSummary,
		arg.Underfilled,
		arg.ResultCount,
	)
	return err
}

const rebuildUserUnitRecallQueue = `-- name: RebuildUserUnitRecallQueue :one
with source as (
  select
    states.user_id,
    states.coarse_unit_id,
    states.status,
    states.target_priority,
    states.mastery_score,
    states.last_progress_quality,
    states.next_review_at,
    coalesce(inventory.supply_grade, 'none')::text as supply_grade,
    states.updated_at as state_updated_at,
    extract(epoch from states.updated_at)::text as source_version
  from learning.user_unit_states as states
  left join recommendation.v_unit_video_inventory as inventory
    on inventory.coarse_unit_id = states.coarse_unit_id
  where states.user_id = $1
    and states.is_target = true
    and states.status in ('new', 'learning', 'reviewing')
),
deleted as (
  delete from recommendation.user_unit_recall_queue
  where user_id = $1
),
inserted as (
  insert into recommendation.user_unit_recall_queue (
    user_id,
    coarse_unit_id,
    status,
    target_priority,
    mastery_score,
    last_progress_quality,
    next_review_at,
    supply_grade,
    state_updated_at,
    source_version,
    rebuilt_at
  )
  select
    user_id,
    coarse_unit_id,
    status,
    target_priority,
    mastery_score,
    last_progress_quality,
    next_review_at,
    supply_grade,
    state_updated_at,
    source_version,
    now()
  from source
  on conflict (user_id, coarse_unit_id) do update
  set
    status = excluded.status,
    target_priority = excluded.target_priority,
    mastery_score = excluded.mastery_score,
    last_progress_quality = excluded.last_progress_quality,
    next_review_at = excluded.next_review_at,
    supply_grade = excluded.supply_grade,
    state_updated_at = excluded.state_updated_at,
    source_version = excluded.source_version,
    rebuilt_at = excluded.rebuilt_at
  returning state_updated_at
),
summary as (
  select
    count(*)::integer as active_target_unit_count,
    max(state_updated_at) as source_learning_max_updated_at
  from source
)
insert into recommendation.user_unit_recall_queue_states (
  user_id,
  source_learning_max_updated_at,
  source_projection_updated_at,
  active_target_unit_count,
  rebuilt_at
)
select
  $1,
  summary.source_learning_max_updated_at,
  $2,
  summary.active_target_unit_count,
  now()
from summary
on conflict (user_id) do update
set
  source_learning_max_updated_at = excluded.source_learning_max_updated_at,
  source_projection_updated_at = excluded.source_projection_updated_at,
  active_target_unit_count = excluded.active_target_unit_count,
  rebuilt_at = excluded.rebuilt_at
returning
  user_id,
  source_learning_max_updated_at,
  source_projection_updated_at,
  active_target_unit_count,
  rebuilt_at
`

type RebuildUserUnitRecallQueueParams struct {
	UserID                    pgtype.UUID        `json:"user_id"`
	SourceProjectionUpdatedAt pgtype.Timestamptz `json:"source_projection_updated_at"`
}

func (q *Queries) RebuildUserUnitRecallQueue(ctx context.Context, arg RebuildUserUnitRecallQueueParams) (RecommendationUserUnitRecallQueueState, error) {
	row := q.db.QueryRow(ctx, rebuildUserUnitRecallQueue, arg.UserID, arg.SourceProjectionUpdatedAt)
	var i RecommendationUserUnitRecallQueueState
	err := row.Scan(
		&i.UserID,
		&i.SourceLearningMaxUpdatedAt,
		&i.SourceProjectionUpdatedAt,
		&i.ActiveTargetUnitCount,
		&i.RebuiltAt,
	)
	return i, err
}

const refreshUnitVideoInventory = `-- name: RefreshUnitVideoInventory :exec
refresh materialized view recommendation.v_unit_video_inventory
`

func (q *Queries) RefreshUnitVideoInventory(ctx context.Context) error {
	_, err := q.db.Exec(ctx, refreshUnitVideoInventory)
	return err
}

const refreshVideoUnitRecallIndex = `-- name: RefreshVideoUnitRecallIndex :exec
refresh materialized view recommendation.v_video_unit_recall_index
`

func (q *Queries) RefreshVideoUnitRecallIndex(ctx context.Context) error {
	_, err := q.db.Exec(ctx, refreshVideoUnitRecallIndex)
	return err
}

const upsertRecallProjectionMetadata = `-- name: UpsertRecallProjectionMetadata :exec
insert into recommendation.recall_projection_metadata (
  projection_name,
  projection_updated_at
)
values ('video_unit_recall_index', $1)
on conflict (projection_name) do update
set projection_updated_at = excluded.projection_updated_at
`

func (q *Queries) UpsertRecallProjectionMetadata(ctx context.Context, projectionUpdatedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, upsertRecallProjectionMetadata, projectionUpdatedAt)
	return err
}
