// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recommendation_writes.sql

package recommendationsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertVideoRecommendationItem = `-- name: InsertVideoRecommendationItem :exec
insert into recommendation.video_recommendation_items (
  run_id,
  rank,
  video_id,
  score,
  primary_lane,
  dominant_bucket,
  dominant_unit_id,
  reason_codes,
  covered_hard_review_count,
  covered_new_now_count,
  covered_soft_review_count,
  covered_near_future_count,
  best_evidence_sentence_index,
  best_evidence_span_index,
  best_evidence_start_ms,
  best_evidence_end_ms
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16
)
`

type InsertVideoRecommendationItemParams struct {
	RunID                     pgtype.UUID    `json:"run_id"`
	Rank                      int32          `json:"rank"`
	VideoID                   pgtype.UUID    `json:"video_id"`
	Score                     pgtype.Numeric `json:"score"`
	PrimaryLane               pgtype.Text    `json:"primary_lane"`
	DominantBucket            pgtype.Text    `json:"dominant_bucket"`
	DominantUnitID            pgtype.Int8    `json:"dominant_unit_id"`
	ReasonCodes               []string       `json:"reason_codes"`
	CoveredHardReviewCount    int32          `json:"covered_hard_review_count"`
	CoveredNewNowCount        int32          `json:"covered_new_now_count"`
	CoveredSoftReviewCount    int32          `json:"covered_soft_review_count"`
	CoveredNearFutureCount    int32          `json:"covered_near_future_count"`
	BestEvidenceSentenceIndex pgtype.Int4    `json:"best_evidence_sentence_index"`
	BestEvidenceSpanIndex     pgtype.Int4    `json:"best_evidence_span_index"`
	BestEvidenceStartMs       pgtype.Int4    `json:"best_evidence_start_ms"`
	BestEvidenceEndMs         pgtype.Int4    `json:"best_evidence_end_ms"`
}

func (q *Queries) InsertVideoRecommendationItem(ctx context.Context, arg InsertVideoRecommendationItemParams) error {
	_, err := q.db.Exec(ctx, insertVideoRecommendationItem,
		arg.RunID,
		arg.Rank,
		arg.VideoID,
		arg.Score,
		arg.PrimaryLane,
		arg.DominantBucket,
		arg.DominantUnitID,
		arg.ReasonCodes,
		arg.CoveredHardReviewCount,
		arg.CoveredNewNowCount,
		arg.CoveredSoftReviewCount,
		arg.CoveredNearFutureCount,
		arg.BestEvidenceSentenceIndex,
		arg.BestEvidenceSpanIndex,
		arg.BestEvidenceStartMs,
		arg.BestEvidenceEndMs,
	)
	return err
}

const insertVideoRecommendationRun = `-- name: InsertVideoRecommendationRun :exec
insert into recommendation.video_recommendation_runs (
  run_id,
  user_id,
  request_context,
  session_mode,
  selector_mode,
  planner_snapshot,
  lane_budget_snapshot,
  candidate_summary,
  underfilled,
  result_count
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
`

type InsertVideoRecommendationRunParams struct {
	RunID              pgtype.UUID `json:"run_id"`
	UserID             pgtype.UUID `json:"user_id"`
	RequestContext     []byte      `json:"request_context"`
	SessionMode        pgtype.Text `json:"session_mode"`
	SelectorMode       pgtype.Text `json:"selector_mode"`
	PlannerSnapshot    []byte      `json:"planner_snapshot"`
	LaneBudgetSnapshot []byte      `json:"lane_budget_snapshot"`
	CandidateSummary   []byte      `json:"candidate_summary"`
	Underfilled        bool        `json:"underfilled"`
	ResultCount        int32       `json:"result_count"`
}

func (q *Queries) InsertVideoRecommendationRun(ctx context.Context, arg InsertVideoRecommendationRunParams) error {
	_, err := q.db.Exec(ctx, insertVideoRecommendationRun,
		arg.RunID,
		arg.UserID,
		arg.RequestContext,
		arg.SessionMode,
		arg.SelectorMode,
		arg.PlannerSnapshot,
		arg.LaneBudgetSnapshot,
		arg.CandidateSummary,
		arg.Underfilled,
		arg.ResultCount,
	)
	return err
}

const refreshRecommendableVideoUnits = `-- name: RefreshRecommendableVideoUnits :exec
refresh materialized view recommendation.v_recommendable_video_units
`

func (q *Queries) RefreshRecommendableVideoUnits(ctx context.Context) error {
	_, err := q.db.Exec(ctx, refreshRecommendableVideoUnits)
	return err
}

const refreshUnitVideoInventory = `-- name: RefreshUnitVideoInventory :exec
refresh materialized view recommendation.v_unit_video_inventory
`

func (q *Queries) RefreshUnitVideoInventory(ctx context.Context) error {
	_, err := q.db.Exec(ctx, refreshUnitVideoInventory)
	return err
}

const upsertUserUnitServingState = `-- name: UpsertUserUnitServingState :exec
insert into recommendation.user_unit_serving_states (
  user_id,
  coarse_unit_id,
  last_served_at,
  last_run_id,
  served_count,
  updated_at
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  now()
)
on conflict (user_id, coarse_unit_id) do update
set
  last_served_at = excluded.last_served_at,
  last_run_id = excluded.last_run_id,
  served_count = excluded.served_count,
  updated_at = now()
`

type UpsertUserUnitServingStateParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	CoarseUnitID int64              `json:"coarse_unit_id"`
	LastServedAt pgtype.Timestamptz `json:"last_served_at"`
	LastRunID    pgtype.UUID        `json:"last_run_id"`
	ServedCount  int32              `json:"served_count"`
}

func (q *Queries) UpsertUserUnitServingState(ctx context.Context, arg UpsertUserUnitServingStateParams) error {
	_, err := q.db.Exec(ctx, upsertUserUnitServingState,
		arg.UserID,
		arg.CoarseUnitID,
		arg.LastServedAt,
		arg.LastRunID,
		arg.ServedCount,
	)
	return err
}

const upsertUserVideoServingState = `-- name: UpsertUserVideoServingState :exec
insert into recommendation.user_video_serving_states (
  user_id,
  video_id,
  last_served_at,
  last_run_id,
  served_count,
  updated_at
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  now()
)
on conflict (user_id, video_id) do update
set
  last_served_at = excluded.last_served_at,
  last_run_id = excluded.last_run_id,
  served_count = excluded.served_count,
  updated_at = now()
`

type UpsertUserVideoServingStateParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	VideoID      pgtype.UUID        `json:"video_id"`
	LastServedAt pgtype.Timestamptz `json:"last_served_at"`
	LastRunID    pgtype.UUID        `json:"last_run_id"`
	ServedCount  int32              `json:"served_count"`
}

func (q *Queries) UpsertUserVideoServingState(ctx context.Context, arg UpsertUserVideoServingStateParams) error {
	_, err := q.db.Exec(ctx, upsertUserVideoServingState,
		arg.UserID,
		arg.VideoID,
		arg.LastServedAt,
		arg.LastRunID,
		arg.ServedCount,
	)
	return err
}
