// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: candidates.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findDueReviewCandidates = `-- name: FindDueReviewCandidates :many
select
  s.user_id,
  s.coarse_unit_id,
  s.is_target,
  s.target_source,
  s.target_source_ref_id,
  s.target_priority,
  s.status,
  s.progress_percent,
  s.mastery_score,
  s.first_seen_at,
  s.last_seen_at,
  s.last_reviewed_at,
  s.seen_count,
  s.strong_event_count,
  s.review_count,
  s.correct_count,
  s.wrong_count,
  s.consecutive_correct,
  s.consecutive_wrong,
  s.last_quality,
  s.recent_quality_window,
  s.recent_correctness_window,
  s.repetition,
  s.interval_days,
  s.ease_factor,
  s.next_review_at,
  s.suspended_reason,
  s.created_at as state_created_at,
  s.updated_at as state_updated_at,
  us.last_recommended_at,
  us.last_recommendation_run_id,
  us.created_at as serving_created_at,
  us.updated_at as serving_updated_at,
  u.kind as unit_kind,
  u.label as unit_label,
  u.pos as unit_pos,
  u.english_def as unit_english_def,
  u.chinese_def as unit_chinese_def
from learning.user_unit_states s
join semantic.coarse_unit u on u.id = s.coarse_unit_id
left join recommendation.user_unit_serving_states us
  on us.user_id = s.user_id
 and us.coarse_unit_id = s.coarse_unit_id
where s.user_id = $1
  and s.is_target = true
  and s.status in ('learning', 'reviewing', 'mastered')
  and s.next_review_at <= $2
order by s.next_review_at asc, s.coarse_unit_id asc
`

type FindDueReviewCandidatesParams struct {
	UserID pgtype.UUID
	Now    pgtype.Timestamptz
}

type FindDueReviewCandidatesRow struct {
	UserID                  pgtype.UUID
	CoarseUnitID            int64
	IsTarget                bool
	TargetSource            pgtype.Text
	TargetSourceRefID       pgtype.Text
	TargetPriority          pgtype.Numeric
	Status                  string
	ProgressPercent         pgtype.Numeric
	MasteryScore            pgtype.Numeric
	FirstSeenAt             pgtype.Timestamptz
	LastSeenAt              pgtype.Timestamptz
	LastReviewedAt          pgtype.Timestamptz
	SeenCount               int32
	StrongEventCount        int32
	ReviewCount             int32
	CorrectCount            int32
	WrongCount              int32
	ConsecutiveCorrect      int32
	ConsecutiveWrong        int32
	LastQuality             pgtype.Int2
	RecentQualityWindow     []int16
	RecentCorrectnessWindow []bool
	Repetition              int32
	IntervalDays            pgtype.Numeric
	EaseFactor              pgtype.Numeric
	NextReviewAt            pgtype.Timestamptz
	SuspendedReason         pgtype.Text
	StateCreatedAt          pgtype.Timestamptz
	StateUpdatedAt          pgtype.Timestamptz
	LastRecommendedAt       pgtype.Timestamptz
	LastRecommendationRunID pgtype.UUID
	ServingCreatedAt        pgtype.Timestamptz
	ServingUpdatedAt        pgtype.Timestamptz
	UnitKind                string
	UnitLabel               string
	UnitPos                 pgtype.Text
	UnitEnglishDef          pgtype.Text
	UnitChineseDef          pgtype.Text
}

func (q *Queries) FindDueReviewCandidates(ctx context.Context, arg FindDueReviewCandidatesParams) ([]FindDueReviewCandidatesRow, error) {
	rows, err := q.db.Query(ctx, findDueReviewCandidates, arg.UserID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindDueReviewCandidatesRow
	for rows.Next() {
		var i FindDueReviewCandidatesRow
		if err := rows.Scan(
			&i.UserID,
			&i.CoarseUnitID,
			&i.IsTarget,
			&i.TargetSource,
			&i.TargetSourceRefID,
			&i.TargetPriority,
			&i.Status,
			&i.ProgressPercent,
			&i.MasteryScore,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.LastReviewedAt,
			&i.SeenCount,
			&i.StrongEventCount,
			&i.ReviewCount,
			&i.CorrectCount,
			&i.WrongCount,
			&i.ConsecutiveCorrect,
			&i.ConsecutiveWrong,
			&i.LastQuality,
			&i.RecentQualityWindow,
			&i.RecentCorrectnessWindow,
			&i.Repetition,
			&i.IntervalDays,
			&i.EaseFactor,
			&i.NextReviewAt,
			&i.SuspendedReason,
			&i.StateCreatedAt,
			&i.StateUpdatedAt,
			&i.LastRecommendedAt,
			&i.LastRecommendationRunID,
			&i.ServingCreatedAt,
			&i.ServingUpdatedAt,
			&i.UnitKind,
			&i.UnitLabel,
			&i.UnitPos,
			&i.UnitEnglishDef,
			&i.UnitChineseDef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNewCandidates = `-- name: FindNewCandidates :many
select
  s.user_id,
  s.coarse_unit_id,
  s.is_target,
  s.target_source,
  s.target_source_ref_id,
  s.target_priority,
  s.status,
  s.progress_percent,
  s.mastery_score,
  s.first_seen_at,
  s.last_seen_at,
  s.last_reviewed_at,
  s.seen_count,
  s.strong_event_count,
  s.review_count,
  s.correct_count,
  s.wrong_count,
  s.consecutive_correct,
  s.consecutive_wrong,
  s.last_quality,
  s.recent_quality_window,
  s.recent_correctness_window,
  s.repetition,
  s.interval_days,
  s.ease_factor,
  s.next_review_at,
  s.suspended_reason,
  s.created_at as state_created_at,
  s.updated_at as state_updated_at,
  us.last_recommended_at,
  us.last_recommendation_run_id,
  us.created_at as serving_created_at,
  us.updated_at as serving_updated_at,
  u.kind as unit_kind,
  u.label as unit_label,
  u.pos as unit_pos,
  u.english_def as unit_english_def,
  u.chinese_def as unit_chinese_def
from learning.user_unit_states s
join semantic.coarse_unit u on u.id = s.coarse_unit_id
left join recommendation.user_unit_serving_states us
  on us.user_id = s.user_id
 and us.coarse_unit_id = s.coarse_unit_id
where s.user_id = $1
  and s.is_target = true
  and s.status = 'new'
order by s.target_priority desc, s.coarse_unit_id asc
`

type FindNewCandidatesRow struct {
	UserID                  pgtype.UUID
	CoarseUnitID            int64
	IsTarget                bool
	TargetSource            pgtype.Text
	TargetSourceRefID       pgtype.Text
	TargetPriority          pgtype.Numeric
	Status                  string
	ProgressPercent         pgtype.Numeric
	MasteryScore            pgtype.Numeric
	FirstSeenAt             pgtype.Timestamptz
	LastSeenAt              pgtype.Timestamptz
	LastReviewedAt          pgtype.Timestamptz
	SeenCount               int32
	StrongEventCount        int32
	ReviewCount             int32
	CorrectCount            int32
	WrongCount              int32
	ConsecutiveCorrect      int32
	ConsecutiveWrong        int32
	LastQuality             pgtype.Int2
	RecentQualityWindow     []int16
	RecentCorrectnessWindow []bool
	Repetition              int32
	IntervalDays            pgtype.Numeric
	EaseFactor              pgtype.Numeric
	NextReviewAt            pgtype.Timestamptz
	SuspendedReason         pgtype.Text
	StateCreatedAt          pgtype.Timestamptz
	StateUpdatedAt          pgtype.Timestamptz
	LastRecommendedAt       pgtype.Timestamptz
	LastRecommendationRunID pgtype.UUID
	ServingCreatedAt        pgtype.Timestamptz
	ServingUpdatedAt        pgtype.Timestamptz
	UnitKind                string
	UnitLabel               string
	UnitPos                 pgtype.Text
	UnitEnglishDef          pgtype.Text
	UnitChineseDef          pgtype.Text
}

func (q *Queries) FindNewCandidates(ctx context.Context, userID pgtype.UUID) ([]FindNewCandidatesRow, error) {
	rows, err := q.db.Query(ctx, findNewCandidates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindNewCandidatesRow
	for rows.Next() {
		var i FindNewCandidatesRow
		if err := rows.Scan(
			&i.UserID,
			&i.CoarseUnitID,
			&i.IsTarget,
			&i.TargetSource,
			&i.TargetSourceRefID,
			&i.TargetPriority,
			&i.Status,
			&i.ProgressPercent,
			&i.MasteryScore,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.LastReviewedAt,
			&i.SeenCount,
			&i.StrongEventCount,
			&i.ReviewCount,
			&i.CorrectCount,
			&i.WrongCount,
			&i.ConsecutiveCorrect,
			&i.ConsecutiveWrong,
			&i.LastQuality,
			&i.RecentQualityWindow,
			&i.RecentCorrectnessWindow,
			&i.Repetition,
			&i.IntervalDays,
			&i.EaseFactor,
			&i.NextReviewAt,
			&i.SuspendedReason,
			&i.StateCreatedAt,
			&i.StateUpdatedAt,
			&i.LastRecommendedAt,
			&i.LastRecommendationRunID,
			&i.ServingCreatedAt,
			&i.ServingUpdatedAt,
			&i.UnitKind,
			&i.UnitLabel,
			&i.UnitPos,
			&i.UnitEnglishDef,
			&i.UnitChineseDef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
