// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthUser struct {
	ID pgtype.UUID
}

type CatalogVideo struct {
	VideoID pgtype.UUID
}

type LearningSchedulerRun struct {
	RunID               pgtype.UUID
	UserID              pgtype.UUID
	RequestedLimit      int32
	GeneratedAt         pgtype.Timestamptz
	DueReviewCount      int32
	SelectedReviewCount int32
	SelectedNewCount    int32
	Context             []byte
}

type LearningSchedulerRunItem struct {
	RunID         pgtype.UUID
	UserID        pgtype.UUID
	CoarseUnitID  int64
	RecommendType string
	Rank          int32
	Score         pgtype.Numeric
	ReasonCodes   []string
}

type LearningUnitLearningEvent struct {
	EventID        int64
	UserID         pgtype.UUID
	CoarseUnitID   int64
	VideoID        pgtype.UUID
	EventType      string
	SourceType     string
	SourceRefID    pgtype.Text
	IsCorrect      pgtype.Bool
	Quality        pgtype.Int2
	ResponseTimeMs pgtype.Int4
	Metadata       []byte
	OccurredAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type LearningUserSchedulerSetting struct {
	UserID               pgtype.UUID
	SessionDefaultLimit  int32
	DailyNewUnitQuota    int32
	DailyReviewSoftLimit int32
	DailyReviewHardLimit int32
	Timezone             pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type LearningUserUnitState struct {
	UserID             pgtype.UUID
	CoarseUnitID       int64
	IsTarget           bool
	TargetSource       pgtype.Text
	TargetSourceRefID  pgtype.Text
	TargetPriority     pgtype.Numeric
	Status             string
	ProgressPercent    pgtype.Numeric
	MasteryScore       pgtype.Numeric
	FirstSeenAt        pgtype.Timestamptz
	LastSeenAt         pgtype.Timestamptz
	LastReviewedAt     pgtype.Timestamptz
	LastRecommendedAt  pgtype.Timestamptz
	SeenCount          int32
	StrongEventCount   int32
	ReviewCount        int32
	CorrectCount       int32
	WrongCount         int32
	ConsecutiveCorrect int32
	ConsecutiveWrong   int32
	LastQuality        pgtype.Int2
	Repetition         int32
	IntervalDays       pgtype.Numeric
	EaseFactor         pgtype.Numeric
	NextReviewAt       pgtype.Timestamptz
	SuspendedReason    pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type SemanticCoarseUnit struct {
	ID         int64
	Kind       string
	Label      string
	Pos        pgtype.Text
	EnglishDef pgtype.Text
	ChineseDef pgtype.Text
}
