// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scheduler_runs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSchedulerRuns = `-- name: CountSchedulerRuns :one
select count(*)::bigint
from recommendation.scheduler_runs
`

func (q *Queries) CountSchedulerRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSchedulerRuns)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertSchedulerRun = `-- name: UpsertSchedulerRun :exec
insert into recommendation.scheduler_runs (
  run_id,
  user_id,
  requested_limit,
  generated_at,
  due_review_count,
  selected_review_count,
  selected_new_count,
  context
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
on conflict (run_id) do update
set
  user_id = excluded.user_id,
  requested_limit = excluded.requested_limit,
  generated_at = excluded.generated_at,
  due_review_count = excluded.due_review_count,
  selected_review_count = excluded.selected_review_count,
  selected_new_count = excluded.selected_new_count,
  context = excluded.context
`

type UpsertSchedulerRunParams struct {
	RunID               pgtype.UUID
	UserID              pgtype.UUID
	RequestedLimit      int32
	GeneratedAt         pgtype.Timestamptz
	DueReviewCount      int32
	SelectedReviewCount int32
	SelectedNewCount    int32
	Context             []byte
}

func (q *Queries) UpsertSchedulerRun(ctx context.Context, arg UpsertSchedulerRunParams) error {
	_, err := q.db.Exec(ctx, upsertSchedulerRun,
		arg.RunID,
		arg.UserID,
		arg.RequestedLimit,
		arg.GeneratedAt,
		arg.DueReviewCount,
		arg.SelectedReviewCount,
		arg.SelectedNewCount,
		arg.Context,
	)
	return err
}

const upsertSchedulerRunItem = `-- name: UpsertSchedulerRunItem :exec
insert into recommendation.scheduler_run_items (
  run_id,
  user_id,
  coarse_unit_id,
  recommend_type,
  rank,
  score,
  reason_codes
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
on conflict (run_id, coarse_unit_id) do update
set
  user_id = excluded.user_id,
  recommend_type = excluded.recommend_type,
  rank = excluded.rank,
  score = excluded.score,
  reason_codes = excluded.reason_codes
`

type UpsertSchedulerRunItemParams struct {
	RunID         pgtype.UUID
	UserID        pgtype.UUID
	CoarseUnitID  int64
	RecommendType string
	Rank          int32
	Score         pgtype.Numeric
	ReasonCodes   []string
}

func (q *Queries) UpsertSchedulerRunItem(ctx context.Context, arg UpsertSchedulerRunItemParams) error {
	_, err := q.db.Exec(ctx, upsertSchedulerRunItem,
		arg.RunID,
		arg.UserID,
		arg.CoarseUnitID,
		arg.RecommendType,
		arg.Rank,
		arg.Score,
		arg.ReasonCodes,
	)
	return err
}
