// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scheduler_runs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSchedulerRuns = `-- name: CountSchedulerRuns :one
select count(*)::bigint
from learning.scheduler_runs
`

func (q *Queries) CountSchedulerRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSchedulerRuns)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserSchedulerSettings = `-- name: GetUserSchedulerSettings :one
select user_id, session_default_limit, daily_new_unit_quota, daily_review_soft_limit, daily_review_hard_limit, timezone, created_at, updated_at
from learning.user_scheduler_settings
where user_id = $1
limit 1
`

func (q *Queries) GetUserSchedulerSettings(ctx context.Context, userID pgtype.UUID) (LearningUserSchedulerSetting, error) {
	row := q.db.QueryRow(ctx, getUserSchedulerSettings, userID)
	var i LearningUserSchedulerSetting
	err := row.Scan(
		&i.UserID,
		&i.SessionDefaultLimit,
		&i.DailyNewUnitQuota,
		&i.DailyReviewSoftLimit,
		&i.DailyReviewHardLimit,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSchedulerRun = `-- name: InsertSchedulerRun :exec
insert into learning.scheduler_runs (
  run_id,
  user_id,
  requested_limit,
  generated_at,
  due_review_count,
  selected_review_count,
  selected_new_count,
  context
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
`

type InsertSchedulerRunParams struct {
	RunID               pgtype.UUID
	UserID              pgtype.UUID
	RequestedLimit      int32
	GeneratedAt         pgtype.Timestamptz
	DueReviewCount      int32
	SelectedReviewCount int32
	SelectedNewCount    int32
	Context             []byte
}

func (q *Queries) InsertSchedulerRun(ctx context.Context, arg InsertSchedulerRunParams) error {
	_, err := q.db.Exec(ctx, insertSchedulerRun,
		arg.RunID,
		arg.UserID,
		arg.RequestedLimit,
		arg.GeneratedAt,
		arg.DueReviewCount,
		arg.SelectedReviewCount,
		arg.SelectedNewCount,
		arg.Context,
	)
	return err
}

const insertSchedulerRunItem = `-- name: InsertSchedulerRunItem :exec
insert into learning.scheduler_run_items (
  run_id,
  user_id,
  coarse_unit_id,
  recommend_type,
  rank,
  score,
  reason_codes
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
`

type InsertSchedulerRunItemParams struct {
	RunID         pgtype.UUID
	UserID        pgtype.UUID
	CoarseUnitID  int64
	RecommendType string
	Rank          int32
	Score         pgtype.Numeric
	ReasonCodes   []string
}

func (q *Queries) InsertSchedulerRunItem(ctx context.Context, arg InsertSchedulerRunItemParams) error {
	_, err := q.db.Exec(ctx, insertSchedulerRunItem,
		arg.RunID,
		arg.UserID,
		arg.CoarseUnitID,
		arg.RecommendType,
		arg.Rank,
		arg.Score,
		arg.ReasonCodes,
	)
	return err
}
