// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: serving_states.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertUserUnitServingState = `-- name: UpsertUserUnitServingState :exec
insert into recommendation.user_unit_serving_states (
  user_id,
  coarse_unit_id,
  last_recommended_at,
  last_recommendation_run_id,
  created_at,
  updated_at
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
on conflict (user_id, coarse_unit_id) do update
set
  last_recommended_at = excluded.last_recommended_at,
  last_recommendation_run_id = excluded.last_recommendation_run_id,
  updated_at = excluded.updated_at
`

type UpsertUserUnitServingStateParams struct {
	UserID                  pgtype.UUID
	CoarseUnitID            int64
	LastRecommendedAt       pgtype.Timestamptz
	LastRecommendationRunID pgtype.UUID
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

func (q *Queries) UpsertUserUnitServingState(ctx context.Context, arg UpsertUserUnitServingStateParams) error {
	_, err := q.db.Exec(ctx, upsertUserUnitServingState,
		arg.UserID,
		arg.CoarseUnitID,
		arg.LastRecommendedAt,
		arg.LastRecommendationRunID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
