// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package learningenginesqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthUser struct {
	ID               pgtype.UUID        `json:"id"`
	Email            pgtype.Text        `json:"email"`
	EmailConfirmedAt pgtype.Timestamptz `json:"email_confirmed_at"`
}

type CatalogVideo struct {
	VideoID pgtype.UUID `json:"video_id"`
}

type LearningUnitLearningEvent struct {
	EventID                   pgtype.UUID        `json:"event_id"`
	LedgerSeq                 pgtype.Int8        `json:"ledger_seq"`
	UserID                    pgtype.UUID        `json:"user_id"`
	CoarseUnitID              int64              `json:"coarse_unit_id"`
	VideoID                   pgtype.UUID        `json:"video_id"`
	EventType                 string             `json:"event_type"`
	ReducerEffect             string             `json:"reducer_effect"`
	ProgressQuality           pgtype.Int2        `json:"progress_quality"`
	SourceType                string             `json:"source_type"`
	SourceRefID               string             `json:"source_ref_id"`
	IsCorrect                 pgtype.Bool        `json:"is_correct"`
	CountsTowardSuccessStreak bool               `json:"counts_toward_success_streak"`
	ConsumedWatchSessionIds   []pgtype.UUID      `json:"consumed_watch_session_ids"`
	Metadata                  []byte             `json:"metadata"`
	OccurredAt                pgtype.Timestamptz `json:"occurred_at"`
	ResetBoundaryAt           pgtype.Timestamptz `json:"reset_boundary_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
}

type LearningUserLearningProfile struct {
	UserID                      pgtype.UUID        `json:"user_id"`
	ActiveCollectionID          pgtype.UUID        `json:"active_collection_id"`
	ActiveCollectionSlug        string             `json:"active_collection_slug"`
	ActiveCollectionActivatedAt pgtype.Timestamptz `json:"active_collection_activated_at"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
}

type LearningUserUnitState struct {
	UserID                  pgtype.UUID        `json:"user_id"`
	CoarseUnitID            int64              `json:"coarse_unit_id"`
	IsTarget                bool               `json:"is_target"`
	TargetSource            pgtype.Text        `json:"target_source"`
	TargetSourceRefID       pgtype.Text        `json:"target_source_ref_id"`
	TargetPriority          pgtype.Numeric     `json:"target_priority"`
	Status                  string             `json:"status"`
	ProgressPercent         pgtype.Numeric     `json:"progress_percent"`
	MasteryScore            pgtype.Numeric     `json:"mastery_score"`
	FirstObservedAt         pgtype.Timestamptz `json:"first_observed_at"`
	LastObservedAt          pgtype.Timestamptz `json:"last_observed_at"`
	ObservationCount        int32              `json:"observation_count"`
	ProgressEventCount      int32              `json:"progress_event_count"`
	LastProgressAt          pgtype.Timestamptz `json:"last_progress_at"`
	LastProgressQuality     pgtype.Int2        `json:"last_progress_quality"`
	RecentProgressQualities []int16            `json:"recent_progress_qualities"`
	RecentProgressPasses    []bool             `json:"recent_progress_passes"`
	ProgressSuccessCount    int32              `json:"progress_success_count"`
	ProgressFailureCount    int32              `json:"progress_failure_count"`
	ConsecutiveSuccessCount int32              `json:"consecutive_success_count"`
	ConsecutiveFailureCount int32              `json:"consecutive_failure_count"`
	ScheduleRepetition      int32              `json:"schedule_repetition"`
	ScheduleIntervalDays    pgtype.Numeric     `json:"schedule_interval_days"`
	ScheduleEaseFactor      pgtype.Numeric     `json:"schedule_ease_factor"`
	NextReviewAt            pgtype.Timestamptz `json:"next_review_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type SemanticCoarseUnit struct {
	ID              int64              `json:"id"`
	Kind            string             `json:"kind"`
	Label           string             `json:"label"`
	Lang            string             `json:"lang"`
	Pos             pgtype.Text        `json:"pos"`
	EnglishDef      pgtype.Text        `json:"english_def"`
	ChineseDef      pgtype.Text        `json:"chinese_def"`
	ChineseCriteria pgtype.Text        `json:"chinese_criteria"`
	ChineseLabel    pgtype.Text        `json:"chinese_label"`
	EnglishLabel    pgtype.Text        `json:"english_label"`
	Pattern         []byte             `json:"pattern"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Version         int32              `json:"version"`
	FineUnitIds     []int64            `json:"fine_unit_ids"`
	OriginalDefs    []string           `json:"original_defs"`
}

type SemanticUnitCollection struct {
	CollectionID    pgtype.UUID `json:"collection_id"`
	Slug            string      `json:"slug"`
	Name            string      `json:"name"`
	Status          string      `json:"status"`
	CoarseUnitCount int32       `json:"coarse_unit_count"`
}

type SemanticUnitCollectionMember struct {
	CollectionID   pgtype.UUID        `json:"collection_id"`
	CoarseUnitID   int64              `json:"coarse_unit_id"`
	SortOrder      int32              `json:"sort_order"`
	TargetPriority pgtype.Numeric     `json:"target_priority"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
