// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package learningenginesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateUnitCollectionTarget(ctx context.Context, arg ActivateUnitCollectionTargetParams) (ActivateUnitCollectionTargetRow, error)
	AppendLearningEvents(ctx context.Context, events []byte) ([]AppendLearningEventsRow, error)
	BatchUpsertUserUnitStates(ctx context.Context, states []byte) ([]LearningUserUnitState, error)
	DeleteUserUnitStatesByUser(ctx context.Context, userID pgtype.UUID) error
	EnsureTargetUnits(ctx context.Context, arg EnsureTargetUnitsParams) error
	GetActiveLearningTargetCoarseUnitIDs(ctx context.Context, userID pgtype.UUID) (GetActiveLearningTargetCoarseUnitIDsRow, error)
	GetActiveUnitCollection(ctx context.Context, userID pgtype.UUID) (GetActiveUnitCollectionRow, error)
	GetUserUnitState(ctx context.Context, arg GetUserUnitStateParams) (LearningUserUnitState, error)
	GetUserUnitStateForUpdate(ctx context.Context, arg GetUserUnitStateForUpdateParams) (LearningUserUnitState, error)
	ListLearningEventsByUserOrdered(ctx context.Context, userID pgtype.UUID) ([]LearningUnitLearningEvent, error)
	ListLearningEventsByUserUnitOrdered(ctx context.Context, arg ListLearningEventsByUserUnitOrderedParams) ([]LearningUnitLearningEvent, error)
	ListMasteredUnitProgress(ctx context.Context, arg ListMasteredUnitProgressParams) ([]ListMasteredUnitProgressRow, error)
	ListUnmasteredUnitProgress(ctx context.Context, arg ListUnmasteredUnitProgressParams) ([]ListUnmasteredUnitProgressRow, error)
	ListUserUnitStates(ctx context.Context, arg ListUserUnitStatesParams) ([]LearningUserUnitState, error)
	ListUserUnitStatesForUpdateByUnitIDs(ctx context.Context, arg ListUserUnitStatesForUpdateByUnitIDsParams) ([]LearningUserUnitState, error)
	SetTargetInactive(ctx context.Context, arg SetTargetInactiveParams) error
	UpsertUserUnitState(ctx context.Context, arg UpsertUserUnitStateParams) (LearningUserUnitState, error)
}

var _ Querier = (*Queries)(nil)
