// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: unit_learning_events.sql

package learningenginesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendLearningEvents = `-- name: AppendLearningEvents :many
with input as (
  select
    (item.value->>'input_index')::integer as input_index,
    (item.value->>'user_id')::uuid as user_id,
    (item.value->>'coarse_unit_id')::bigint as coarse_unit_id,
    nullif(item.value->>'video_id', '')::uuid as video_id,
    item.value->>'event_type' as event_type,
    item.value->>'reducer_effect' as reducer_effect,
    nullif(item.value->>'progress_quality', '')::smallint as progress_quality,
    item.value->>'source_type' as source_type,
    item.value->>'source_ref_id' as source_ref_id,
    nullif(item.value->>'is_correct', '')::boolean as is_correct,
    coalesce((item.value->>'counts_toward_success_streak')::boolean, false) as counts_toward_success_streak,
    array(
      select jsonb_array_elements_text(
        case
          when jsonb_typeof(item.value->'consumed_watch_session_ids') = 'array'
            then item.value->'consumed_watch_session_ids'
          else '[]'::jsonb
        end
      )::uuid
    ) as consumed_watch_session_ids,
    coalesce(item.value->'metadata', '{}'::jsonb) as metadata,
    (item.value->>'occurred_at')::timestamptz as occurred_at
  from jsonb_array_elements($1::jsonb) as item(value)
),
inserted as (
insert into learning.unit_learning_events (
  user_id,
  coarse_unit_id,
  video_id,
  event_type,
  reducer_effect,
  progress_quality,
  source_type,
  source_ref_id,
  is_correct,
  counts_toward_success_streak,
  consumed_watch_session_ids,
  metadata,
  occurred_at
)
select
  user_id,
  coarse_unit_id,
  video_id,
  event_type,
  reducer_effect,
  progress_quality,
  source_type,
  source_ref_id,
  is_correct,
  counts_toward_success_streak,
  consumed_watch_session_ids,
  coalesce(metadata, '{}'::jsonb),
  occurred_at
from input
order by input_index asc
on conflict (user_id, source_type, source_ref_id, coarse_unit_id) do nothing
returning event_id, user_id, coarse_unit_id, video_id, event_type, reducer_effect, progress_quality, source_type, source_ref_id, is_correct, counts_toward_success_streak, consumed_watch_session_ids, metadata, occurred_at, created_at
)
select event_id, user_id, coarse_unit_id, video_id, event_type, reducer_effect, progress_quality, source_type, source_ref_id, is_correct, counts_toward_success_streak, consumed_watch_session_ids, metadata, occurred_at, created_at
from inserted
order by coarse_unit_id asc, occurred_at asc, event_id asc
`

type AppendLearningEventsRow struct {
	EventID                   pgtype.UUID        `json:"event_id"`
	UserID                    pgtype.UUID        `json:"user_id"`
	CoarseUnitID              int64              `json:"coarse_unit_id"`
	VideoID                   pgtype.UUID        `json:"video_id"`
	EventType                 string             `json:"event_type"`
	ReducerEffect             string             `json:"reducer_effect"`
	ProgressQuality           pgtype.Int2        `json:"progress_quality"`
	SourceType                string             `json:"source_type"`
	SourceRefID               string             `json:"source_ref_id"`
	IsCorrect                 pgtype.Bool        `json:"is_correct"`
	CountsTowardSuccessStreak bool               `json:"counts_toward_success_streak"`
	ConsumedWatchSessionIds   []pgtype.UUID      `json:"consumed_watch_session_ids"`
	Metadata                  []byte             `json:"metadata"`
	OccurredAt                pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AppendLearningEvents(ctx context.Context, events []byte) ([]AppendLearningEventsRow, error) {
	rows, err := q.db.Query(ctx, appendLearningEvents, events)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppendLearningEventsRow{}
	for rows.Next() {
		var i AppendLearningEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.UserID,
			&i.CoarseUnitID,
			&i.VideoID,
			&i.EventType,
			&i.ReducerEffect,
			&i.ProgressQuality,
			&i.SourceType,
			&i.SourceRefID,
			&i.IsCorrect,
			&i.CountsTowardSuccessStreak,
			&i.ConsumedWatchSessionIds,
			&i.Metadata,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLearningEventByUserSourceRef = `-- name: GetLearningEventByUserSourceRef :one
select event_id, user_id, coarse_unit_id, video_id, event_type, reducer_effect, progress_quality, source_type, source_ref_id, is_correct, counts_toward_success_streak, consumed_watch_session_ids, metadata, occurred_at, created_at
from learning.unit_learning_events
where user_id = $1
  and source_type = $2
  and source_ref_id = $3
order by created_at asc, event_id asc
limit 1
`

type GetLearningEventByUserSourceRefParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	SourceType  string      `json:"source_type"`
	SourceRefID string      `json:"source_ref_id"`
}

func (q *Queries) GetLearningEventByUserSourceRef(ctx context.Context, arg GetLearningEventByUserSourceRefParams) (LearningUnitLearningEvent, error) {
	row := q.db.QueryRow(ctx, getLearningEventByUserSourceRef, arg.UserID, arg.SourceType, arg.SourceRefID)
	var i LearningUnitLearningEvent
	err := row.Scan(
		&i.EventID,
		&i.UserID,
		&i.CoarseUnitID,
		&i.VideoID,
		&i.EventType,
		&i.ReducerEffect,
		&i.ProgressQuality,
		&i.SourceType,
		&i.SourceRefID,
		&i.IsCorrect,
		&i.CountsTowardSuccessStreak,
		&i.ConsumedWatchSessionIds,
		&i.Metadata,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listLearningEventsByUserOrdered = `-- name: ListLearningEventsByUserOrdered :many
select event_id, user_id, coarse_unit_id, video_id, event_type, reducer_effect, progress_quality, source_type, source_ref_id, is_correct, counts_toward_success_streak, consumed_watch_session_ids, metadata, occurred_at, created_at
from learning.unit_learning_events
where user_id = $1
order by occurred_at asc, event_id asc
`

func (q *Queries) ListLearningEventsByUserOrdered(ctx context.Context, userID pgtype.UUID) ([]LearningUnitLearningEvent, error) {
	rows, err := q.db.Query(ctx, listLearningEventsByUserOrdered, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningUnitLearningEvent{}
	for rows.Next() {
		var i LearningUnitLearningEvent
		if err := rows.Scan(
			&i.EventID,
			&i.UserID,
			&i.CoarseUnitID,
			&i.VideoID,
			&i.EventType,
			&i.ReducerEffect,
			&i.ProgressQuality,
			&i.SourceType,
			&i.SourceRefID,
			&i.IsCorrect,
			&i.CountsTowardSuccessStreak,
			&i.ConsumedWatchSessionIds,
			&i.Metadata,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningEventsByUserUnitOrdered = `-- name: ListLearningEventsByUserUnitOrdered :many
select event_id, user_id, coarse_unit_id, video_id, event_type, reducer_effect, progress_quality, source_type, source_ref_id, is_correct, counts_toward_success_streak, consumed_watch_session_ids, metadata, occurred_at, created_at
from learning.unit_learning_events
where user_id = $1
  and coarse_unit_id = $2
order by occurred_at asc, event_id asc
`

type ListLearningEventsByUserUnitOrderedParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	CoarseUnitID int64       `json:"coarse_unit_id"`
}

func (q *Queries) ListLearningEventsByUserUnitOrdered(ctx context.Context, arg ListLearningEventsByUserUnitOrderedParams) ([]LearningUnitLearningEvent, error) {
	rows, err := q.db.Query(ctx, listLearningEventsByUserUnitOrdered, arg.UserID, arg.CoarseUnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningUnitLearningEvent{}
	for rows.Next() {
		var i LearningUnitLearningEvent
		if err := rows.Scan(
			&i.EventID,
			&i.UserID,
			&i.CoarseUnitID,
			&i.VideoID,
			&i.EventType,
			&i.ReducerEffect,
			&i.ProgressQuality,
			&i.SourceType,
			&i.SourceRefID,
			&i.IsCorrect,
			&i.CountsTowardSuccessStreak,
			&i.ConsumedWatchSessionIds,
			&i.Metadata,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
