// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_unit_states.sql

package learningenginesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateUnitCollectionTarget = `-- name: ActivateUnitCollectionTarget :one
with selected_collection as (
  select
    collection_id,
    slug,
    coarse_unit_count
  from semantic.unit_collections
  where slug = $1
    and status = 'active'
),
new_members as (
  select
    m.collection_id,
    m.coarse_unit_id,
    0::numeric as target_priority
  from semantic.unit_collection_members m
  join selected_collection c
    on c.collection_id = m.collection_id
),
profile_upsert as (
  insert into learning.user_learning_profiles (
    user_id,
    active_collection_id,
    active_collection_slug,
    active_collection_activated_at,
    updated_at
  )
  select
    $2,
    collection_id,
    slug,
    now(),
    now()
  from selected_collection
  on conflict (user_id) do update
  set
    active_collection_id = excluded.active_collection_id,
    active_collection_slug = excluded.active_collection_slug,
    active_collection_activated_at = now(),
    updated_at = now()
  returning user_id
),
deactivated as (
  update learning.user_unit_states s
  set
    is_target = false,
    updated_at = now()
  where s.user_id = $2
    and s.target_source = 'unit_collection'
    and s.is_target = true
    and not exists (
      select 1
      from new_members nm
      where nm.coarse_unit_id = s.coarse_unit_id
    )
  returning s.coarse_unit_id
),
upserted as (
  insert into learning.user_unit_states (
    user_id,
    coarse_unit_id,
    is_target,
    target_source,
    target_source_ref_id,
    target_priority
  )
  select
    $2,
    nm.coarse_unit_id,
    true,
    'unit_collection',
    nm.collection_id::text,
    nm.target_priority
  from new_members nm
  on conflict (user_id, coarse_unit_id) do update
  set
    is_target = true,
    target_source = 'unit_collection',
    target_source_ref_id = excluded.target_source_ref_id,
    target_priority = excluded.target_priority,
    updated_at = now()
  returning coarse_unit_id
)
select
  c.collection_id,
  c.slug,
  coalesce(count(u.coarse_unit_id), 0)::integer as target_count
from selected_collection c
left join upserted u on true
group by c.collection_id, c.slug
`

type ActivateUnitCollectionTargetParams struct {
	CollectionSlug string      `json:"collection_slug"`
	UserID         pgtype.UUID `json:"user_id"`
}

type ActivateUnitCollectionTargetRow struct {
	CollectionID pgtype.UUID `json:"collection_id"`
	Slug         string      `json:"slug"`
	TargetCount  int32       `json:"target_count"`
}

func (q *Queries) ActivateUnitCollectionTarget(ctx context.Context, arg ActivateUnitCollectionTargetParams) (ActivateUnitCollectionTargetRow, error) {
	row := q.db.QueryRow(ctx, activateUnitCollectionTarget, arg.CollectionSlug, arg.UserID)
	var i ActivateUnitCollectionTargetRow
	err := row.Scan(&i.CollectionID, &i.Slug, &i.TargetCount)
	return i, err
}

const batchUpsertUserUnitStates = `-- name: BatchUpsertUserUnitStates :many
with input as (
  select
    (item.value->>'user_id')::uuid as user_id,
    (item.value->>'coarse_unit_id')::bigint as coarse_unit_id,
    (item.value->>'is_target')::boolean as is_target,
    nullif(item.value->>'target_source', '') as target_source,
    nullif(item.value->>'target_source_ref_id', '') as target_source_ref_id,
    (item.value->>'target_priority')::numeric as target_priority,
    item.value->>'status' as status,
    (item.value->>'progress_percent')::numeric as progress_percent,
    (item.value->>'mastery_score')::numeric as mastery_score,
    nullif(item.value->>'first_observed_at', '')::timestamptz as first_observed_at,
    nullif(item.value->>'last_observed_at', '')::timestamptz as last_observed_at,
    (item.value->>'observation_count')::integer as observation_count,
    (item.value->>'progress_event_count')::integer as progress_event_count,
    nullif(item.value->>'last_progress_at', '')::timestamptz as last_progress_at,
    nullif(item.value->>'last_progress_quality', '')::smallint as last_progress_quality,
    coalesce((select array_agg(value::smallint) from jsonb_array_elements_text(coalesce(item.value->'recent_progress_qualities', '[]'::jsonb)) as q(value)), '{}'::smallint[]) as recent_progress_qualities,
    coalesce((select array_agg(value::boolean) from jsonb_array_elements_text(coalesce(item.value->'recent_progress_passes', '[]'::jsonb)) as p(value)), '{}'::boolean[]) as recent_progress_passes,
    (item.value->>'progress_success_count')::integer as progress_success_count,
    (item.value->>'progress_failure_count')::integer as progress_failure_count,
    (item.value->>'consecutive_success_count')::integer as consecutive_success_count,
    (item.value->>'consecutive_failure_count')::integer as consecutive_failure_count,
    (item.value->>'schedule_repetition')::integer as schedule_repetition,
    (item.value->>'schedule_interval_days')::numeric as schedule_interval_days,
    (item.value->>'schedule_ease_factor')::numeric as schedule_ease_factor,
    nullif(item.value->>'next_review_at', '')::timestamptz as next_review_at
  from jsonb_array_elements($1::jsonb) as item(value)
)
insert into learning.user_unit_states (
  user_id,
  coarse_unit_id,
  is_target,
  target_source,
  target_source_ref_id,
  target_priority,
  status,
  progress_percent,
  mastery_score,
  first_observed_at,
  last_observed_at,
  observation_count,
  progress_event_count,
  last_progress_at,
  last_progress_quality,
  recent_progress_qualities,
  recent_progress_passes,
  progress_success_count,
  progress_failure_count,
  consecutive_success_count,
  consecutive_failure_count,
  schedule_repetition,
  schedule_interval_days,
  schedule_ease_factor,
  next_review_at,
  updated_at
)
select
  user_id,
  coarse_unit_id,
  is_target,
  target_source,
  target_source_ref_id,
  target_priority,
  status,
  progress_percent,
  mastery_score,
  first_observed_at,
  last_observed_at,
  observation_count,
  progress_event_count,
  last_progress_at,
  last_progress_quality,
  coalesce(recent_progress_qualities, '{}'::smallint[]),
  coalesce(recent_progress_passes, '{}'::boolean[]),
  progress_success_count,
  progress_failure_count,
  consecutive_success_count,
  consecutive_failure_count,
  schedule_repetition,
  schedule_interval_days,
  schedule_ease_factor,
  next_review_at,
  now()
from input
on conflict (user_id, coarse_unit_id) do update
set
  is_target = excluded.is_target,
  target_source = excluded.target_source,
  target_source_ref_id = excluded.target_source_ref_id,
  target_priority = excluded.target_priority,
  status = excluded.status,
  progress_percent = excluded.progress_percent,
  mastery_score = excluded.mastery_score,
  first_observed_at = excluded.first_observed_at,
  last_observed_at = excluded.last_observed_at,
  observation_count = excluded.observation_count,
  progress_event_count = excluded.progress_event_count,
  last_progress_at = excluded.last_progress_at,
  last_progress_quality = excluded.last_progress_quality,
  recent_progress_qualities = excluded.recent_progress_qualities,
  recent_progress_passes = excluded.recent_progress_passes,
  progress_success_count = excluded.progress_success_count,
  progress_failure_count = excluded.progress_failure_count,
  consecutive_success_count = excluded.consecutive_success_count,
  consecutive_failure_count = excluded.consecutive_failure_count,
  schedule_repetition = excluded.schedule_repetition,
  schedule_interval_days = excluded.schedule_interval_days,
  schedule_ease_factor = excluded.schedule_ease_factor,
  next_review_at = excluded.next_review_at,
  updated_at = now()
returning user_id, coarse_unit_id, is_target, target_source, target_source_ref_id, target_priority, status, progress_percent, mastery_score, first_observed_at, last_observed_at, observation_count, progress_event_count, last_progress_at, last_progress_quality, recent_progress_qualities, recent_progress_passes, progress_success_count, progress_failure_count, consecutive_success_count, consecutive_failure_count, schedule_repetition, schedule_interval_days, schedule_ease_factor, next_review_at, created_at, updated_at
`

func (q *Queries) BatchUpsertUserUnitStates(ctx context.Context, states []byte) ([]LearningUserUnitState, error) {
	rows, err := q.db.Query(ctx, batchUpsertUserUnitStates, states)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningUserUnitState{}
	for rows.Next() {
		var i LearningUserUnitState
		if err := rows.Scan(
			&i.UserID,
			&i.CoarseUnitID,
			&i.IsTarget,
			&i.TargetSource,
			&i.TargetSourceRefID,
			&i.TargetPriority,
			&i.Status,
			&i.ProgressPercent,
			&i.MasteryScore,
			&i.FirstObservedAt,
			&i.LastObservedAt,
			&i.ObservationCount,
			&i.ProgressEventCount,
			&i.LastProgressAt,
			&i.LastProgressQuality,
			&i.RecentProgressQualities,
			&i.RecentProgressPasses,
			&i.ProgressSuccessCount,
			&i.ProgressFailureCount,
			&i.ConsecutiveSuccessCount,
			&i.ConsecutiveFailureCount,
			&i.ScheduleRepetition,
			&i.ScheduleIntervalDays,
			&i.ScheduleEaseFactor,
			&i.NextReviewAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUserUnitStatesByUser = `-- name: DeleteUserUnitStatesByUser :exec
delete from learning.user_unit_states
where user_id = $1
`

func (q *Queries) DeleteUserUnitStatesByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserUnitStatesByUser, userID)
	return err
}

const ensureTargetUnits = `-- name: EnsureTargetUnits :exec
with raw_input as (
  select
    ordinality::integer as input_index,
    (item->>'coarse_unit_id')::bigint as coarse_unit_id,
    nullif(item->>'target_source', '') as target_source,
    nullif(item->>'target_source_ref_id', '') as target_source_ref_id,
    (item->>'target_priority')::numeric as target_priority
  from jsonb_array_elements($2::jsonb) with ordinality as targets(item, ordinality)
),
input as (
  select distinct on (coarse_unit_id)
    coarse_unit_id,
    target_source,
    target_source_ref_id,
    target_priority
  from raw_input
  order by coarse_unit_id, input_index desc
)
insert into learning.user_unit_states (
  user_id,
  coarse_unit_id,
  is_target,
  target_source,
  target_source_ref_id,
  target_priority
)
select
  $1,
  coarse_unit_id,
  true,
  target_source,
  target_source_ref_id,
  target_priority
from input
on conflict (user_id, coarse_unit_id) do update
set
  is_target = true,
  target_source = excluded.target_source,
  target_source_ref_id = excluded.target_source_ref_id,
  target_priority = excluded.target_priority,
  updated_at = now()
`

type EnsureTargetUnitsParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Targets []byte      `json:"targets"`
}

func (q *Queries) EnsureTargetUnits(ctx context.Context, arg EnsureTargetUnitsParams) error {
	_, err := q.db.Exec(ctx, ensureTargetUnits, arg.UserID, arg.Targets)
	return err
}

const getActiveLearningTargetCoarseUnitIDs = `-- name: GetActiveLearningTargetCoarseUnitIDs :one
with profile as (
  select p.active_collection_slug
  from learning.user_learning_profiles p
  where p.user_id = $1
),
targets as (
  select coalesce(array_agg(s.coarse_unit_id order by s.coarse_unit_id), '{}'::bigint[]) as coarse_unit_ids
  from learning.user_unit_states s
  where s.user_id = $1
    and s.is_target = true
    and s.status in ('new', 'learning', 'reviewing')
)
select
  coalesce((select active_collection_slug from profile), '')::text as active_collection_slug,
  coalesce((select coarse_unit_ids from targets), '{}'::bigint[])::bigint[] as coarse_unit_ids,
  exists(select 1 from profile) as has_active_profile
`

type GetActiveLearningTargetCoarseUnitIDsRow struct {
	ActiveCollectionSlug string  `json:"active_collection_slug"`
	CoarseUnitIds        []int64 `json:"coarse_unit_ids"`
	HasActiveProfile     bool    `json:"has_active_profile"`
}

func (q *Queries) GetActiveLearningTargetCoarseUnitIDs(ctx context.Context, userID pgtype.UUID) (GetActiveLearningTargetCoarseUnitIDsRow, error) {
	row := q.db.QueryRow(ctx, getActiveLearningTargetCoarseUnitIDs, userID)
	var i GetActiveLearningTargetCoarseUnitIDsRow
	err := row.Scan(&i.ActiveCollectionSlug, &i.CoarseUnitIds, &i.HasActiveProfile)
	return i, err
}

const getActiveUnitCollection = `-- name: GetActiveUnitCollection :one
select
  active_collection_id,
  active_collection_slug
from learning.user_learning_profiles
where user_id = $1
`

type GetActiveUnitCollectionRow struct {
	ActiveCollectionID   pgtype.UUID `json:"active_collection_id"`
	ActiveCollectionSlug string      `json:"active_collection_slug"`
}

func (q *Queries) GetActiveUnitCollection(ctx context.Context, userID pgtype.UUID) (GetActiveUnitCollectionRow, error) {
	row := q.db.QueryRow(ctx, getActiveUnitCollection, userID)
	var i GetActiveUnitCollectionRow
	err := row.Scan(&i.ActiveCollectionID, &i.ActiveCollectionSlug)
	return i, err
}

const getUserUnitState = `-- name: GetUserUnitState :one
select user_id, coarse_unit_id, is_target, target_source, target_source_ref_id, target_priority, status, progress_percent, mastery_score, first_observed_at, last_observed_at, observation_count, progress_event_count, last_progress_at, last_progress_quality, recent_progress_qualities, recent_progress_passes, progress_success_count, progress_failure_count, consecutive_success_count, consecutive_failure_count, schedule_repetition, schedule_interval_days, schedule_ease_factor, next_review_at, created_at, updated_at
from learning.user_unit_states
where user_id = $1
  and coarse_unit_id = $2
`

type GetUserUnitStateParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	CoarseUnitID int64       `json:"coarse_unit_id"`
}

func (q *Queries) GetUserUnitState(ctx context.Context, arg GetUserUnitStateParams) (LearningUserUnitState, error) {
	row := q.db.QueryRow(ctx, getUserUnitState, arg.UserID, arg.CoarseUnitID)
	var i LearningUserUnitState
	err := row.Scan(
		&i.UserID,
		&i.CoarseUnitID,
		&i.IsTarget,
		&i.TargetSource,
		&i.TargetSourceRefID,
		&i.TargetPriority,
		&i.Status,
		&i.ProgressPercent,
		&i.MasteryScore,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.ObservationCount,
		&i.ProgressEventCount,
		&i.LastProgressAt,
		&i.LastProgressQuality,
		&i.RecentProgressQualities,
		&i.RecentProgressPasses,
		&i.ProgressSuccessCount,
		&i.ProgressFailureCount,
		&i.ConsecutiveSuccessCount,
		&i.ConsecutiveFailureCount,
		&i.ScheduleRepetition,
		&i.ScheduleIntervalDays,
		&i.ScheduleEaseFactor,
		&i.NextReviewAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserUnitStateForUpdate = `-- name: GetUserUnitStateForUpdate :one
select user_id, coarse_unit_id, is_target, target_source, target_source_ref_id, target_priority, status, progress_percent, mastery_score, first_observed_at, last_observed_at, observation_count, progress_event_count, last_progress_at, last_progress_quality, recent_progress_qualities, recent_progress_passes, progress_success_count, progress_failure_count, consecutive_success_count, consecutive_failure_count, schedule_repetition, schedule_interval_days, schedule_ease_factor, next_review_at, created_at, updated_at
from learning.user_unit_states
where user_id = $1
  and coarse_unit_id = $2
for update
`

type GetUserUnitStateForUpdateParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	CoarseUnitID int64       `json:"coarse_unit_id"`
}

func (q *Queries) GetUserUnitStateForUpdate(ctx context.Context, arg GetUserUnitStateForUpdateParams) (LearningUserUnitState, error) {
	row := q.db.QueryRow(ctx, getUserUnitStateForUpdate, arg.UserID, arg.CoarseUnitID)
	var i LearningUserUnitState
	err := row.Scan(
		&i.UserID,
		&i.CoarseUnitID,
		&i.IsTarget,
		&i.TargetSource,
		&i.TargetSourceRefID,
		&i.TargetPriority,
		&i.Status,
		&i.ProgressPercent,
		&i.MasteryScore,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.ObservationCount,
		&i.ProgressEventCount,
		&i.LastProgressAt,
		&i.LastProgressQuality,
		&i.RecentProgressQualities,
		&i.RecentProgressPasses,
		&i.ProgressSuccessCount,
		&i.ProgressFailureCount,
		&i.ConsecutiveSuccessCount,
		&i.ConsecutiveFailureCount,
		&i.ScheduleRepetition,
		&i.ScheduleIntervalDays,
		&i.ScheduleEaseFactor,
		&i.NextReviewAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserUnitStates = `-- name: ListUserUnitStates :many
select user_id, coarse_unit_id, is_target, target_source, target_source_ref_id, target_priority, status, progress_percent, mastery_score, first_observed_at, last_observed_at, observation_count, progress_event_count, last_progress_at, last_progress_quality, recent_progress_qualities, recent_progress_passes, progress_success_count, progress_failure_count, consecutive_success_count, consecutive_failure_count, schedule_repetition, schedule_interval_days, schedule_ease_factor, next_review_at, created_at, updated_at
from learning.user_unit_states
where user_id = $1
  and (not $2::boolean or is_target = true)
order by coarse_unit_id asc
`

type ListUserUnitStatesParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	OnlyTarget bool        `json:"only_target"`
}

func (q *Queries) ListUserUnitStates(ctx context.Context, arg ListUserUnitStatesParams) ([]LearningUserUnitState, error) {
	rows, err := q.db.Query(ctx, listUserUnitStates, arg.UserID, arg.OnlyTarget)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningUserUnitState{}
	for rows.Next() {
		var i LearningUserUnitState
		if err := rows.Scan(
			&i.UserID,
			&i.CoarseUnitID,
			&i.IsTarget,
			&i.TargetSource,
			&i.TargetSourceRefID,
			&i.TargetPriority,
			&i.Status,
			&i.ProgressPercent,
			&i.MasteryScore,
			&i.FirstObservedAt,
			&i.LastObservedAt,
			&i.ObservationCount,
			&i.ProgressEventCount,
			&i.LastProgressAt,
			&i.LastProgressQuality,
			&i.RecentProgressQualities,
			&i.RecentProgressPasses,
			&i.ProgressSuccessCount,
			&i.ProgressFailureCount,
			&i.ConsecutiveSuccessCount,
			&i.ConsecutiveFailureCount,
			&i.ScheduleRepetition,
			&i.ScheduleIntervalDays,
			&i.ScheduleEaseFactor,
			&i.NextReviewAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserUnitStatesForUpdateByUnitIDs = `-- name: ListUserUnitStatesForUpdateByUnitIDs :many
select user_id, coarse_unit_id, is_target, target_source, target_source_ref_id, target_priority, status, progress_percent, mastery_score, first_observed_at, last_observed_at, observation_count, progress_event_count, last_progress_at, last_progress_quality, recent_progress_qualities, recent_progress_passes, progress_success_count, progress_failure_count, consecutive_success_count, consecutive_failure_count, schedule_repetition, schedule_interval_days, schedule_ease_factor, next_review_at, created_at, updated_at
from learning.user_unit_states
where user_id = $1
  and coarse_unit_id = any($2::bigint[])
order by coarse_unit_id asc
for update
`

type ListUserUnitStatesForUpdateByUnitIDsParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	CoarseUnitIds []int64     `json:"coarse_unit_ids"`
}

func (q *Queries) ListUserUnitStatesForUpdateByUnitIDs(ctx context.Context, arg ListUserUnitStatesForUpdateByUnitIDsParams) ([]LearningUserUnitState, error) {
	rows, err := q.db.Query(ctx, listUserUnitStatesForUpdateByUnitIDs, arg.UserID, arg.CoarseUnitIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningUserUnitState{}
	for rows.Next() {
		var i LearningUserUnitState
		if err := rows.Scan(
			&i.UserID,
			&i.CoarseUnitID,
			&i.IsTarget,
			&i.TargetSource,
			&i.TargetSourceRefID,
			&i.TargetPriority,
			&i.Status,
			&i.ProgressPercent,
			&i.MasteryScore,
			&i.FirstObservedAt,
			&i.LastObservedAt,
			&i.ObservationCount,
			&i.ProgressEventCount,
			&i.LastProgressAt,
			&i.LastProgressQuality,
			&i.RecentProgressQualities,
			&i.RecentProgressPasses,
			&i.ProgressSuccessCount,
			&i.ProgressFailureCount,
			&i.ConsecutiveSuccessCount,
			&i.ConsecutiveFailureCount,
			&i.ScheduleRepetition,
			&i.ScheduleIntervalDays,
			&i.ScheduleEaseFactor,
			&i.NextReviewAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTargetInactive = `-- name: SetTargetInactive :exec
update learning.user_unit_states
set
  is_target = false,
  updated_at = now()
where user_id = $1
  and coarse_unit_id = $2
`

type SetTargetInactiveParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	CoarseUnitID int64       `json:"coarse_unit_id"`
}

func (q *Queries) SetTargetInactive(ctx context.Context, arg SetTargetInactiveParams) error {
	_, err := q.db.Exec(ctx, setTargetInactive, arg.UserID, arg.CoarseUnitID)
	return err
}

const upsertUserUnitState = `-- name: UpsertUserUnitState :one
insert into learning.user_unit_states (
  user_id,
  coarse_unit_id,
  is_target,
  target_source,
  target_source_ref_id,
  target_priority,
  status,
  progress_percent,
  mastery_score,
  first_observed_at,
  last_observed_at,
  observation_count,
  progress_event_count,
  last_progress_at,
  last_progress_quality,
  recent_progress_qualities,
  recent_progress_passes,
  progress_success_count,
  progress_failure_count,
  consecutive_success_count,
  consecutive_failure_count,
  schedule_repetition,
  schedule_interval_days,
  schedule_ease_factor,
  next_review_at,
  updated_at
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $21,
  $22,
  $23,
  $24,
  $25,
  now()
)
on conflict (user_id, coarse_unit_id) do update
set
  is_target = excluded.is_target,
  target_source = excluded.target_source,
  target_source_ref_id = excluded.target_source_ref_id,
  target_priority = excluded.target_priority,
  status = excluded.status,
  progress_percent = excluded.progress_percent,
  mastery_score = excluded.mastery_score,
  first_observed_at = excluded.first_observed_at,
  last_observed_at = excluded.last_observed_at,
  observation_count = excluded.observation_count,
  progress_event_count = excluded.progress_event_count,
  last_progress_at = excluded.last_progress_at,
  last_progress_quality = excluded.last_progress_quality,
  recent_progress_qualities = excluded.recent_progress_qualities,
  recent_progress_passes = excluded.recent_progress_passes,
  progress_success_count = excluded.progress_success_count,
  progress_failure_count = excluded.progress_failure_count,
  consecutive_success_count = excluded.consecutive_success_count,
  consecutive_failure_count = excluded.consecutive_failure_count,
  schedule_repetition = excluded.schedule_repetition,
  schedule_interval_days = excluded.schedule_interval_days,
  schedule_ease_factor = excluded.schedule_ease_factor,
  next_review_at = excluded.next_review_at,
  updated_at = now()
returning user_id, coarse_unit_id, is_target, target_source, target_source_ref_id, target_priority, status, progress_percent, mastery_score, first_observed_at, last_observed_at, observation_count, progress_event_count, last_progress_at, last_progress_quality, recent_progress_qualities, recent_progress_passes, progress_success_count, progress_failure_count, consecutive_success_count, consecutive_failure_count, schedule_repetition, schedule_interval_days, schedule_ease_factor, next_review_at, created_at, updated_at
`

type UpsertUserUnitStateParams struct {
	UserID                  pgtype.UUID        `json:"user_id"`
	CoarseUnitID            int64              `json:"coarse_unit_id"`
	IsTarget                bool               `json:"is_target"`
	TargetSource            pgtype.Text        `json:"target_source"`
	TargetSourceRefID       pgtype.Text        `json:"target_source_ref_id"`
	TargetPriority          pgtype.Numeric     `json:"target_priority"`
	Status                  string             `json:"status"`
	ProgressPercent         pgtype.Numeric     `json:"progress_percent"`
	MasteryScore            pgtype.Numeric     `json:"mastery_score"`
	FirstObservedAt         pgtype.Timestamptz `json:"first_observed_at"`
	LastObservedAt          pgtype.Timestamptz `json:"last_observed_at"`
	ObservationCount        int32              `json:"observation_count"`
	ProgressEventCount      int32              `json:"progress_event_count"`
	LastProgressAt          pgtype.Timestamptz `json:"last_progress_at"`
	LastProgressQuality     pgtype.Int2        `json:"last_progress_quality"`
	RecentProgressQualities []int16            `json:"recent_progress_qualities"`
	RecentProgressPasses    []bool             `json:"recent_progress_passes"`
	ProgressSuccessCount    int32              `json:"progress_success_count"`
	ProgressFailureCount    int32              `json:"progress_failure_count"`
	ConsecutiveSuccessCount int32              `json:"consecutive_success_count"`
	ConsecutiveFailureCount int32              `json:"consecutive_failure_count"`
	ScheduleRepetition      int32              `json:"schedule_repetition"`
	ScheduleIntervalDays    pgtype.Numeric     `json:"schedule_interval_days"`
	ScheduleEaseFactor      pgtype.Numeric     `json:"schedule_ease_factor"`
	NextReviewAt            pgtype.Timestamptz `json:"next_review_at"`
}

func (q *Queries) UpsertUserUnitState(ctx context.Context, arg UpsertUserUnitStateParams) (LearningUserUnitState, error) {
	row := q.db.QueryRow(ctx, upsertUserUnitState,
		arg.UserID,
		arg.CoarseUnitID,
		arg.IsTarget,
		arg.TargetSource,
		arg.TargetSourceRefID,
		arg.TargetPriority,
		arg.Status,
		arg.ProgressPercent,
		arg.MasteryScore,
		arg.FirstObservedAt,
		arg.LastObservedAt,
		arg.ObservationCount,
		arg.ProgressEventCount,
		arg.LastProgressAt,
		arg.LastProgressQuality,
		arg.RecentProgressQualities,
		arg.RecentProgressPasses,
		arg.ProgressSuccessCount,
		arg.ProgressFailureCount,
		arg.ConsecutiveSuccessCount,
		arg.ConsecutiveFailureCount,
		arg.ScheduleRepetition,
		arg.ScheduleIntervalDays,
		arg.ScheduleEaseFactor,
		arg.NextReviewAt,
	)
	var i LearningUserUnitState
	err := row.Scan(
		&i.UserID,
		&i.CoarseUnitID,
		&i.IsTarget,
		&i.TargetSource,
		&i.TargetSourceRefID,
		&i.TargetPriority,
		&i.Status,
		&i.ProgressPercent,
		&i.MasteryScore,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.ObservationCount,
		&i.ProgressEventCount,
		&i.LastProgressAt,
		&i.LastProgressQuality,
		&i.RecentProgressQualities,
		&i.RecentProgressPasses,
		&i.ProgressSuccessCount,
		&i.ProgressFailureCount,
		&i.ConsecutiveSuccessCount,
		&i.ConsecutiveFailureCount,
		&i.ScheduleRepetition,
		&i.ScheduleIntervalDays,
		&i.ScheduleEaseFactor,
		&i.NextReviewAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
