// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_unit_states.sql

package learningenginesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchUpsertUserUnitStates = `-- name: BatchUpsertUserUnitStates :many
with input as (
  select
    (item.value->>'user_id')::uuid as user_id,
    (item.value->>'coarse_unit_id')::bigint as coarse_unit_id,
    (item.value->>'is_target')::boolean as is_target,
    nullif(item.value->>'target_source', '') as target_source,
    nullif(item.value->>'target_source_ref_id', '') as target_source_ref_id,
    (item.value->>'target_priority')::numeric as target_priority,
    item.value->>'status' as status,
    (item.value->>'progress_percent')::numeric as progress_percent,
    (item.value->>'mastery_score')::numeric as mastery_score,
    nullif(item.value->>'first_observed_at', '')::timestamptz as first_observed_at,
    nullif(item.value->>'last_observed_at', '')::timestamptz as last_observed_at,
    (item.value->>'observation_count')::integer as observation_count,
    (item.value->>'progress_event_count')::integer as progress_event_count,
    nullif(item.value->>'last_progress_at', '')::timestamptz as last_progress_at,
    nullif(item.value->>'last_progress_quality', '')::smallint as last_progress_quality,
    coalesce((select array_agg(value::smallint) from jsonb_array_elements_text(coalesce(item.value->'recent_progress_qualities', '[]'::jsonb)) as q(value)), '{}'::smallint[]) as recent_progress_qualities,
    coalesce((select array_agg(value::boolean) from jsonb_array_elements_text(coalesce(item.value->'recent_progress_passes', '[]'::jsonb)) as p(value)), '{}'::boolean[]) as recent_progress_passes,
    (item.value->>'progress_success_count')::integer as progress_success_count,
    (item.value->>'progress_failure_count')::integer as progress_failure_count,
    (item.value->>'consecutive_success_count')::integer as consecutive_success_count,
    (item.value->>'consecutive_failure_count')::integer as consecutive_failure_count,
    (item.value->>'schedule_repetition')::integer as schedule_repetition,
    (item.value->>'schedule_interval_days')::numeric as schedule_interval_days,
    (item.value->>'schedule_ease_factor')::numeric as schedule_ease_factor,
    nullif(item.value->>'next_review_at', '')::timestamptz as next_review_at,
    nullif(item.value->>'suspended_reason', '') as suspended_reason
  from jsonb_array_elements($1::jsonb) as item(value)
)
insert into learning.user_unit_states (
  user_id,
  coarse_unit_id,
  is_target,
  target_source,
  target_source_ref_id,
  target_priority,
  status,
  progress_percent,
  mastery_score,
  first_observed_at,
  last_observed_at,
  observation_count,
  progress_event_count,
  last_progress_at,
  last_progress_quality,
  recent_progress_qualities,
  recent_progress_passes,
  progress_success_count,
  progress_failure_count,
  consecutive_success_count,
  consecutive_failure_count,
  schedule_repetition,
  schedule_interval_days,
  schedule_ease_factor,
  next_review_at,
  suspended_reason,
  updated_at
)
select
  user_id,
  coarse_unit_id,
  is_target,
  target_source,
  target_source_ref_id,
  target_priority,
  status,
  progress_percent,
  mastery_score,
  first_observed_at,
  last_observed_at,
  observation_count,
  progress_event_count,
  last_progress_at,
  last_progress_quality,
  coalesce(recent_progress_qualities, '{}'::smallint[]),
  coalesce(recent_progress_passes, '{}'::boolean[]),
  progress_success_count,
  progress_failure_count,
  consecutive_success_count,
  consecutive_failure_count,
  schedule_repetition,
  schedule_interval_days,
  schedule_ease_factor,
  next_review_at,
  suspended_reason,
  now()
from input
on conflict (user_id, coarse_unit_id) do update
set
  is_target = excluded.is_target,
  target_source = excluded.target_source,
  target_source_ref_id = excluded.target_source_ref_id,
  target_priority = excluded.target_priority,
  status = excluded.status,
  progress_percent = excluded.progress_percent,
  mastery_score = excluded.mastery_score,
  first_observed_at = excluded.first_observed_at,
  last_observed_at = excluded.last_observed_at,
  observation_count = excluded.observation_count,
  progress_event_count = excluded.progress_event_count,
  last_progress_at = excluded.last_progress_at,
  last_progress_quality = excluded.last_progress_quality,
  recent_progress_qualities = excluded.recent_progress_qualities,
  recent_progress_passes = excluded.recent_progress_passes,
  progress_success_count = excluded.progress_success_count,
  progress_failure_count = excluded.progress_failure_count,
  consecutive_success_count = excluded.consecutive_success_count,
  consecutive_failure_count = excluded.consecutive_failure_count,
  schedule_repetition = excluded.schedule_repetition,
  schedule_interval_days = excluded.schedule_interval_days,
  schedule_ease_factor = excluded.schedule_ease_factor,
  next_review_at = excluded.next_review_at,
  suspended_reason = excluded.suspended_reason,
  updated_at = now()
returning user_id, coarse_unit_id, is_target, target_source, target_source_ref_id, target_priority, status, progress_percent, mastery_score, first_observed_at, last_observed_at, observation_count, progress_event_count, last_progress_at, last_progress_quality, recent_progress_qualities, recent_progress_passes, progress_success_count, progress_failure_count, consecutive_success_count, consecutive_failure_count, schedule_repetition, schedule_interval_days, schedule_ease_factor, next_review_at, suspended_reason, created_at, updated_at
`

func (q *Queries) BatchUpsertUserUnitStates(ctx context.Context, states []byte) ([]LearningUserUnitState, error) {
	rows, err := q.db.Query(ctx, batchUpsertUserUnitStates, states)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningUserUnitState{}
	for rows.Next() {
		var i LearningUserUnitState
		if err := rows.Scan(
			&i.UserID,
			&i.CoarseUnitID,
			&i.IsTarget,
			&i.TargetSource,
			&i.TargetSourceRefID,
			&i.TargetPriority,
			&i.Status,
			&i.ProgressPercent,
			&i.MasteryScore,
			&i.FirstObservedAt,
			&i.LastObservedAt,
			&i.ObservationCount,
			&i.ProgressEventCount,
			&i.LastProgressAt,
			&i.LastProgressQuality,
			&i.RecentProgressQualities,
			&i.RecentProgressPasses,
			&i.ProgressSuccessCount,
			&i.ProgressFailureCount,
			&i.ConsecutiveSuccessCount,
			&i.ConsecutiveFailureCount,
			&i.ScheduleRepetition,
			&i.ScheduleIntervalDays,
			&i.ScheduleEaseFactor,
			&i.NextReviewAt,
			&i.SuspendedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUserUnitStatesByUser = `-- name: DeleteUserUnitStatesByUser :exec
delete from learning.user_unit_states
where user_id = $1
`

func (q *Queries) DeleteUserUnitStatesByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserUnitStatesByUser, userID)
	return err
}

const ensureTargetUnit = `-- name: EnsureTargetUnit :exec
insert into learning.user_unit_states (
  user_id,
  coarse_unit_id,
  is_target,
  target_source,
  target_source_ref_id,
  target_priority
) values (
  $1,
  $2,
  true,
  $3,
  $4,
  $5
)
on conflict (user_id, coarse_unit_id) do update
set
  is_target = true,
  target_source = excluded.target_source,
  target_source_ref_id = excluded.target_source_ref_id,
  target_priority = excluded.target_priority,
  updated_at = now()
`

type EnsureTargetUnitParams struct {
	UserID            pgtype.UUID    `json:"user_id"`
	CoarseUnitID      int64          `json:"coarse_unit_id"`
	TargetSource      pgtype.Text    `json:"target_source"`
	TargetSourceRefID pgtype.Text    `json:"target_source_ref_id"`
	TargetPriority    pgtype.Numeric `json:"target_priority"`
}

func (q *Queries) EnsureTargetUnit(ctx context.Context, arg EnsureTargetUnitParams) error {
	_, err := q.db.Exec(ctx, ensureTargetUnit,
		arg.UserID,
		arg.CoarseUnitID,
		arg.TargetSource,
		arg.TargetSourceRefID,
		arg.TargetPriority,
	)
	return err
}

const getUserUnitStateForUpdate = `-- name: GetUserUnitStateForUpdate :one
select user_id, coarse_unit_id, is_target, target_source, target_source_ref_id, target_priority, status, progress_percent, mastery_score, first_observed_at, last_observed_at, observation_count, progress_event_count, last_progress_at, last_progress_quality, recent_progress_qualities, recent_progress_passes, progress_success_count, progress_failure_count, consecutive_success_count, consecutive_failure_count, schedule_repetition, schedule_interval_days, schedule_ease_factor, next_review_at, suspended_reason, created_at, updated_at
from learning.user_unit_states
where user_id = $1
  and coarse_unit_id = $2
for update
`

type GetUserUnitStateForUpdateParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	CoarseUnitID int64       `json:"coarse_unit_id"`
}

func (q *Queries) GetUserUnitStateForUpdate(ctx context.Context, arg GetUserUnitStateForUpdateParams) (LearningUserUnitState, error) {
	row := q.db.QueryRow(ctx, getUserUnitStateForUpdate, arg.UserID, arg.CoarseUnitID)
	var i LearningUserUnitState
	err := row.Scan(
		&i.UserID,
		&i.CoarseUnitID,
		&i.IsTarget,
		&i.TargetSource,
		&i.TargetSourceRefID,
		&i.TargetPriority,
		&i.Status,
		&i.ProgressPercent,
		&i.MasteryScore,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.ObservationCount,
		&i.ProgressEventCount,
		&i.LastProgressAt,
		&i.LastProgressQuality,
		&i.RecentProgressQualities,
		&i.RecentProgressPasses,
		&i.ProgressSuccessCount,
		&i.ProgressFailureCount,
		&i.ConsecutiveSuccessCount,
		&i.ConsecutiveFailureCount,
		&i.ScheduleRepetition,
		&i.ScheduleIntervalDays,
		&i.ScheduleEaseFactor,
		&i.NextReviewAt,
		&i.SuspendedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserUnitStates = `-- name: ListUserUnitStates :many
select user_id, coarse_unit_id, is_target, target_source, target_source_ref_id, target_priority, status, progress_percent, mastery_score, first_observed_at, last_observed_at, observation_count, progress_event_count, last_progress_at, last_progress_quality, recent_progress_qualities, recent_progress_passes, progress_success_count, progress_failure_count, consecutive_success_count, consecutive_failure_count, schedule_repetition, schedule_interval_days, schedule_ease_factor, next_review_at, suspended_reason, created_at, updated_at
from learning.user_unit_states
where user_id = $1
  and (not $2::boolean or is_target = true)
  and (not $3::boolean or status <> 'suspended')
order by coarse_unit_id asc
`

type ListUserUnitStatesParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	OnlyTarget       bool        `json:"only_target"`
	ExcludeSuspended bool        `json:"exclude_suspended"`
}

func (q *Queries) ListUserUnitStates(ctx context.Context, arg ListUserUnitStatesParams) ([]LearningUserUnitState, error) {
	rows, err := q.db.Query(ctx, listUserUnitStates, arg.UserID, arg.OnlyTarget, arg.ExcludeSuspended)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningUserUnitState{}
	for rows.Next() {
		var i LearningUserUnitState
		if err := rows.Scan(
			&i.UserID,
			&i.CoarseUnitID,
			&i.IsTarget,
			&i.TargetSource,
			&i.TargetSourceRefID,
			&i.TargetPriority,
			&i.Status,
			&i.ProgressPercent,
			&i.MasteryScore,
			&i.FirstObservedAt,
			&i.LastObservedAt,
			&i.ObservationCount,
			&i.ProgressEventCount,
			&i.LastProgressAt,
			&i.LastProgressQuality,
			&i.RecentProgressQualities,
			&i.RecentProgressPasses,
			&i.ProgressSuccessCount,
			&i.ProgressFailureCount,
			&i.ConsecutiveSuccessCount,
			&i.ConsecutiveFailureCount,
			&i.ScheduleRepetition,
			&i.ScheduleIntervalDays,
			&i.ScheduleEaseFactor,
			&i.NextReviewAt,
			&i.SuspendedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserUnitStatesForUpdateByUnitIDs = `-- name: ListUserUnitStatesForUpdateByUnitIDs :many
select user_id, coarse_unit_id, is_target, target_source, target_source_ref_id, target_priority, status, progress_percent, mastery_score, first_observed_at, last_observed_at, observation_count, progress_event_count, last_progress_at, last_progress_quality, recent_progress_qualities, recent_progress_passes, progress_success_count, progress_failure_count, consecutive_success_count, consecutive_failure_count, schedule_repetition, schedule_interval_days, schedule_ease_factor, next_review_at, suspended_reason, created_at, updated_at
from learning.user_unit_states
where user_id = $1
  and coarse_unit_id = any($2::bigint[])
order by coarse_unit_id asc
for update
`

type ListUserUnitStatesForUpdateByUnitIDsParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	CoarseUnitIds []int64     `json:"coarse_unit_ids"`
}

func (q *Queries) ListUserUnitStatesForUpdateByUnitIDs(ctx context.Context, arg ListUserUnitStatesForUpdateByUnitIDsParams) ([]LearningUserUnitState, error) {
	rows, err := q.db.Query(ctx, listUserUnitStatesForUpdateByUnitIDs, arg.UserID, arg.CoarseUnitIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningUserUnitState{}
	for rows.Next() {
		var i LearningUserUnitState
		if err := rows.Scan(
			&i.UserID,
			&i.CoarseUnitID,
			&i.IsTarget,
			&i.TargetSource,
			&i.TargetSourceRefID,
			&i.TargetPriority,
			&i.Status,
			&i.ProgressPercent,
			&i.MasteryScore,
			&i.FirstObservedAt,
			&i.LastObservedAt,
			&i.ObservationCount,
			&i.ProgressEventCount,
			&i.LastProgressAt,
			&i.LastProgressQuality,
			&i.RecentProgressQualities,
			&i.RecentProgressPasses,
			&i.ProgressSuccessCount,
			&i.ProgressFailureCount,
			&i.ConsecutiveSuccessCount,
			&i.ConsecutiveFailureCount,
			&i.ScheduleRepetition,
			&i.ScheduleIntervalDays,
			&i.ScheduleEaseFactor,
			&i.NextReviewAt,
			&i.SuspendedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTargetInactive = `-- name: SetTargetInactive :exec
update learning.user_unit_states
set
  is_target = false,
  updated_at = now()
where user_id = $1
  and coarse_unit_id = $2
`

type SetTargetInactiveParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	CoarseUnitID int64       `json:"coarse_unit_id"`
}

func (q *Queries) SetTargetInactive(ctx context.Context, arg SetTargetInactiveParams) error {
	_, err := q.db.Exec(ctx, setTargetInactive, arg.UserID, arg.CoarseUnitID)
	return err
}

const upsertUserUnitState = `-- name: UpsertUserUnitState :one
insert into learning.user_unit_states (
  user_id,
  coarse_unit_id,
  is_target,
  target_source,
  target_source_ref_id,
  target_priority,
  status,
  progress_percent,
  mastery_score,
  first_observed_at,
  last_observed_at,
  observation_count,
  progress_event_count,
  last_progress_at,
  last_progress_quality,
  recent_progress_qualities,
  recent_progress_passes,
  progress_success_count,
  progress_failure_count,
  consecutive_success_count,
  consecutive_failure_count,
  schedule_repetition,
  schedule_interval_days,
  schedule_ease_factor,
  next_review_at,
  suspended_reason,
  updated_at
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $21,
  $22,
  $23,
  $24,
  $25,
  $26,
  now()
)
on conflict (user_id, coarse_unit_id) do update
set
  is_target = excluded.is_target,
  target_source = excluded.target_source,
  target_source_ref_id = excluded.target_source_ref_id,
  target_priority = excluded.target_priority,
  status = excluded.status,
  progress_percent = excluded.progress_percent,
  mastery_score = excluded.mastery_score,
  first_observed_at = excluded.first_observed_at,
  last_observed_at = excluded.last_observed_at,
  observation_count = excluded.observation_count,
  progress_event_count = excluded.progress_event_count,
  last_progress_at = excluded.last_progress_at,
  last_progress_quality = excluded.last_progress_quality,
  recent_progress_qualities = excluded.recent_progress_qualities,
  recent_progress_passes = excluded.recent_progress_passes,
  progress_success_count = excluded.progress_success_count,
  progress_failure_count = excluded.progress_failure_count,
  consecutive_success_count = excluded.consecutive_success_count,
  consecutive_failure_count = excluded.consecutive_failure_count,
  schedule_repetition = excluded.schedule_repetition,
  schedule_interval_days = excluded.schedule_interval_days,
  schedule_ease_factor = excluded.schedule_ease_factor,
  next_review_at = excluded.next_review_at,
  suspended_reason = excluded.suspended_reason,
  updated_at = now()
returning user_id, coarse_unit_id, is_target, target_source, target_source_ref_id, target_priority, status, progress_percent, mastery_score, first_observed_at, last_observed_at, observation_count, progress_event_count, last_progress_at, last_progress_quality, recent_progress_qualities, recent_progress_passes, progress_success_count, progress_failure_count, consecutive_success_count, consecutive_failure_count, schedule_repetition, schedule_interval_days, schedule_ease_factor, next_review_at, suspended_reason, created_at, updated_at
`

type UpsertUserUnitStateParams struct {
	UserID                  pgtype.UUID        `json:"user_id"`
	CoarseUnitID            int64              `json:"coarse_unit_id"`
	IsTarget                bool               `json:"is_target"`
	TargetSource            pgtype.Text        `json:"target_source"`
	TargetSourceRefID       pgtype.Text        `json:"target_source_ref_id"`
	TargetPriority          pgtype.Numeric     `json:"target_priority"`
	Status                  string             `json:"status"`
	ProgressPercent         pgtype.Numeric     `json:"progress_percent"`
	MasteryScore            pgtype.Numeric     `json:"mastery_score"`
	FirstObservedAt         pgtype.Timestamptz `json:"first_observed_at"`
	LastObservedAt          pgtype.Timestamptz `json:"last_observed_at"`
	ObservationCount        int32              `json:"observation_count"`
	ProgressEventCount      int32              `json:"progress_event_count"`
	LastProgressAt          pgtype.Timestamptz `json:"last_progress_at"`
	LastProgressQuality     pgtype.Int2        `json:"last_progress_quality"`
	RecentProgressQualities []int16            `json:"recent_progress_qualities"`
	RecentProgressPasses    []bool             `json:"recent_progress_passes"`
	ProgressSuccessCount    int32              `json:"progress_success_count"`
	ProgressFailureCount    int32              `json:"progress_failure_count"`
	ConsecutiveSuccessCount int32              `json:"consecutive_success_count"`
	ConsecutiveFailureCount int32              `json:"consecutive_failure_count"`
	ScheduleRepetition      int32              `json:"schedule_repetition"`
	ScheduleIntervalDays    pgtype.Numeric     `json:"schedule_interval_days"`
	ScheduleEaseFactor      pgtype.Numeric     `json:"schedule_ease_factor"`
	NextReviewAt            pgtype.Timestamptz `json:"next_review_at"`
	SuspendedReason         pgtype.Text        `json:"suspended_reason"`
}

func (q *Queries) UpsertUserUnitState(ctx context.Context, arg UpsertUserUnitStateParams) (LearningUserUnitState, error) {
	row := q.db.QueryRow(ctx, upsertUserUnitState,
		arg.UserID,
		arg.CoarseUnitID,
		arg.IsTarget,
		arg.TargetSource,
		arg.TargetSourceRefID,
		arg.TargetPriority,
		arg.Status,
		arg.ProgressPercent,
		arg.MasteryScore,
		arg.FirstObservedAt,
		arg.LastObservedAt,
		arg.ObservationCount,
		arg.ProgressEventCount,
		arg.LastProgressAt,
		arg.LastProgressQuality,
		arg.RecentProgressQualities,
		arg.RecentProgressPasses,
		arg.ProgressSuccessCount,
		arg.ProgressFailureCount,
		arg.ConsecutiveSuccessCount,
		arg.ConsecutiveFailureCount,
		arg.ScheduleRepetition,
		arg.ScheduleIntervalDays,
		arg.ScheduleEaseFactor,
		arg.NextReviewAt,
		arg.SuspendedReason,
	)
	var i LearningUserUnitState
	err := row.Scan(
		&i.UserID,
		&i.CoarseUnitID,
		&i.IsTarget,
		&i.TargetSource,
		&i.TargetSourceRefID,
		&i.TargetPriority,
		&i.Status,
		&i.ProgressPercent,
		&i.MasteryScore,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.ObservationCount,
		&i.ProgressEventCount,
		&i.LastProgressAt,
		&i.LastProgressQuality,
		&i.RecentProgressQualities,
		&i.RecentProgressPasses,
		&i.ProgressSuccessCount,
		&i.ProgressFailureCount,
		&i.ConsecutiveSuccessCount,
		&i.ConsecutiveFailureCount,
		&i.ScheduleRepetition,
		&i.ScheduleIntervalDays,
		&i.ScheduleEaseFactor,
		&i.NextReviewAt,
		&i.SuspendedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
