// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package learningenginesqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthUser struct {
	ID pgtype.UUID `json:"id"`
}

type CatalogVideo struct {
	VideoID pgtype.UUID `json:"video_id"`
}

type LearningUnitLearningEvent struct {
	EventID         pgtype.UUID        `json:"event_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	CoarseUnitID    int64              `json:"coarse_unit_id"`
	VideoID         pgtype.UUID        `json:"video_id"`
	EventType       string             `json:"event_type"`
	ReducerEffect   string             `json:"reducer_effect"`
	ProgressQuality pgtype.Int2        `json:"progress_quality"`
	SourceType      string             `json:"source_type"`
	SourceRefID     string             `json:"source_ref_id"`
	IsCorrect       pgtype.Bool        `json:"is_correct"`
	Metadata        []byte             `json:"metadata"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type LearningUserUnitState struct {
	UserID                  pgtype.UUID        `json:"user_id"`
	CoarseUnitID            int64              `json:"coarse_unit_id"`
	IsTarget                bool               `json:"is_target"`
	TargetSource            pgtype.Text        `json:"target_source"`
	TargetSourceRefID       pgtype.Text        `json:"target_source_ref_id"`
	TargetPriority          pgtype.Numeric     `json:"target_priority"`
	Status                  string             `json:"status"`
	ProgressPercent         pgtype.Numeric     `json:"progress_percent"`
	MasteryScore            pgtype.Numeric     `json:"mastery_score"`
	FirstObservedAt         pgtype.Timestamptz `json:"first_observed_at"`
	LastObservedAt          pgtype.Timestamptz `json:"last_observed_at"`
	ObservationCount        int32              `json:"observation_count"`
	ProgressEventCount      int32              `json:"progress_event_count"`
	LastProgressAt          pgtype.Timestamptz `json:"last_progress_at"`
	LastProgressQuality     pgtype.Int2        `json:"last_progress_quality"`
	RecentProgressQualities []int16            `json:"recent_progress_qualities"`
	RecentProgressPasses    []bool             `json:"recent_progress_passes"`
	ProgressSuccessCount    int32              `json:"progress_success_count"`
	ProgressFailureCount    int32              `json:"progress_failure_count"`
	ConsecutiveSuccessCount int32              `json:"consecutive_success_count"`
	ConsecutiveFailureCount int32              `json:"consecutive_failure_count"`
	ScheduleRepetition      int32              `json:"schedule_repetition"`
	ScheduleIntervalDays    pgtype.Numeric     `json:"schedule_interval_days"`
	ScheduleEaseFactor      pgtype.Numeric     `json:"schedule_ease_factor"`
	NextReviewAt            pgtype.Timestamptz `json:"next_review_at"`
	SuspendedReason         pgtype.Text        `json:"suspended_reason"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type SemanticCoarseUnit struct {
	ID              int64              `json:"id"`
	Kind            string             `json:"kind"`
	Label           string             `json:"label"`
	Lang            string             `json:"lang"`
	Pos             pgtype.Text        `json:"pos"`
	EnglishDef      pgtype.Text        `json:"english_def"`
	ChineseDef      pgtype.Text        `json:"chinese_def"`
	ChineseCriteria pgtype.Text        `json:"chinese_criteria"`
	ChineseLabel    pgtype.Text        `json:"chinese_label"`
	EnglishLabel    pgtype.Text        `json:"english_label"`
	Pattern         []byte             `json:"pattern"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Version         int32              `json:"version"`
	FineUnitIds     []int64            `json:"fine_unit_ids"`
	OriginalDefs    []string           `json:"original_defs"`
}
