// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package learningenginesqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthUser struct {
	ID pgtype.UUID `json:"id"`
}

type CatalogVideo struct {
	VideoID pgtype.UUID `json:"video_id"`
}

type LearningUnitLearningEvent struct {
	EventID        int64              `json:"event_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	CoarseUnitID   int64              `json:"coarse_unit_id"`
	VideoID        pgtype.UUID        `json:"video_id"`
	EventType      string             `json:"event_type"`
	SourceType     string             `json:"source_type"`
	SourceRefID    pgtype.Text        `json:"source_ref_id"`
	IsCorrect      pgtype.Bool        `json:"is_correct"`
	Quality        pgtype.Int2        `json:"quality"`
	ResponseTimeMs pgtype.Int4        `json:"response_time_ms"`
	Metadata       []byte             `json:"metadata"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type LearningUserUnitState struct {
	UserID                  pgtype.UUID        `json:"user_id"`
	CoarseUnitID            int64              `json:"coarse_unit_id"`
	IsTarget                bool               `json:"is_target"`
	TargetSource            pgtype.Text        `json:"target_source"`
	TargetSourceRefID       pgtype.Text        `json:"target_source_ref_id"`
	TargetPriority          pgtype.Numeric     `json:"target_priority"`
	Status                  string             `json:"status"`
	ProgressPercent         pgtype.Numeric     `json:"progress_percent"`
	MasteryScore            pgtype.Numeric     `json:"mastery_score"`
	FirstSeenAt             pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt              pgtype.Timestamptz `json:"last_seen_at"`
	LastReviewedAt          pgtype.Timestamptz `json:"last_reviewed_at"`
	SeenCount               int32              `json:"seen_count"`
	StrongEventCount        int32              `json:"strong_event_count"`
	ReviewCount             int32              `json:"review_count"`
	CorrectCount            int32              `json:"correct_count"`
	WrongCount              int32              `json:"wrong_count"`
	ConsecutiveCorrect      int32              `json:"consecutive_correct"`
	ConsecutiveWrong        int32              `json:"consecutive_wrong"`
	LastQuality             pgtype.Int2        `json:"last_quality"`
	RecentQualityWindow     []int16            `json:"recent_quality_window"`
	RecentCorrectnessWindow []bool             `json:"recent_correctness_window"`
	Repetition              int32              `json:"repetition"`
	IntervalDays            pgtype.Numeric     `json:"interval_days"`
	EaseFactor              pgtype.Numeric     `json:"ease_factor"`
	NextReviewAt            pgtype.Timestamptz `json:"next_review_at"`
	SuspendedReason         pgtype.Text        `json:"suspended_reason"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type SemanticCoarseUnit struct {
	ID int64 `json:"id"`
}
