// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package learningenginesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AppendLearningEvent(ctx context.Context, arg AppendLearningEventParams) (LearningUnitLearningEvent, error)
	EnsureTargetUnit(ctx context.Context, arg EnsureTargetUnitParams) error
	GetUserUnitStateForUpdate(ctx context.Context, arg GetUserUnitStateForUpdateParams) (LearningUserUnitState, error)
	ListLearningEventsByUserOrdered(ctx context.Context, userID pgtype.UUID) ([]LearningUnitLearningEvent, error)
	ListLearningEventsByUserUnitOrdered(ctx context.Context, arg ListLearningEventsByUserUnitOrderedParams) ([]LearningUnitLearningEvent, error)
	ListRecommendationUnitStates(ctx context.Context, userID pgtype.UUID) ([]LearningUserUnitState, error)
	ListUserUnitStates(ctx context.Context, userID pgtype.UUID) ([]LearningUserUnitState, error)
	ResumeTargetUnit(ctx context.Context, arg ResumeTargetUnitParams) error
	SetTargetInactive(ctx context.Context, arg SetTargetInactiveParams) error
	SuspendTargetUnit(ctx context.Context, arg SuspendTargetUnitParams) error
	UpsertUserUnitState(ctx context.Context, arg UpsertUserUnitStateParams) (LearningUserUnitState, error)
}

var _ Querier = (*Queries)(nil)
