// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: unit_states.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserUnitStates = `-- name: CountUserUnitStates :one
select count(*)::bigint
from learning.user_unit_states
`

func (q *Queries) CountUserUnitStates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUserUnitStates)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteUserUnitStatesByUser = `-- name: DeleteUserUnitStatesByUser :exec
delete from learning.user_unit_states
where user_id = $1
`

func (q *Queries) DeleteUserUnitStatesByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserUnitStatesByUser, userID)
	return err
}

const getUserUnitStateByUserAndUnit = `-- name: GetUserUnitStateByUserAndUnit :one
select user_id, coarse_unit_id, is_target, target_source, target_source_ref_id, target_priority, status, progress_percent, mastery_score, first_seen_at, last_seen_at, last_reviewed_at, seen_count, strong_event_count, review_count, correct_count, wrong_count, consecutive_correct, consecutive_wrong, last_quality, recent_quality_window, recent_correctness_window, repetition, interval_days, ease_factor, next_review_at, suspended_reason, created_at, updated_at
from learning.user_unit_states
where user_id = $1
  and coarse_unit_id = $2
limit 1
`

type GetUserUnitStateByUserAndUnitParams struct {
	UserID       pgtype.UUID
	CoarseUnitID int64
}

func (q *Queries) GetUserUnitStateByUserAndUnit(ctx context.Context, arg GetUserUnitStateByUserAndUnitParams) (LearningUserUnitState, error) {
	row := q.db.QueryRow(ctx, getUserUnitStateByUserAndUnit, arg.UserID, arg.CoarseUnitID)
	var i LearningUserUnitState
	err := row.Scan(
		&i.UserID,
		&i.CoarseUnitID,
		&i.IsTarget,
		&i.TargetSource,
		&i.TargetSourceRefID,
		&i.TargetPriority,
		&i.Status,
		&i.ProgressPercent,
		&i.MasteryScore,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.LastReviewedAt,
		&i.SeenCount,
		&i.StrongEventCount,
		&i.ReviewCount,
		&i.CorrectCount,
		&i.WrongCount,
		&i.ConsecutiveCorrect,
		&i.ConsecutiveWrong,
		&i.LastQuality,
		&i.RecentQualityWindow,
		&i.RecentCorrectnessWindow,
		&i.Repetition,
		&i.IntervalDays,
		&i.EaseFactor,
		&i.NextReviewAt,
		&i.SuspendedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserUnitState = `-- name: UpsertUserUnitState :exec
insert into learning.user_unit_states (
  user_id,
  coarse_unit_id,
  is_target,
  target_source,
  target_source_ref_id,
  target_priority,
  status,
  progress_percent,
  mastery_score,
  first_seen_at,
  last_seen_at,
  last_reviewed_at,
  seen_count,
  strong_event_count,
  review_count,
  correct_count,
  wrong_count,
  consecutive_correct,
  consecutive_wrong,
  last_quality,
  recent_quality_window,
  recent_correctness_window,
  repetition,
  interval_days,
  ease_factor,
  next_review_at,
  suspended_reason,
  created_at,
  updated_at
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $21,
  $22,
  $23,
  $24,
  $25,
  $26,
  $27,
  $28,
  $29
)
on conflict (user_id, coarse_unit_id) do update
set
  is_target = excluded.is_target,
  target_source = excluded.target_source,
  target_source_ref_id = excluded.target_source_ref_id,
  target_priority = excluded.target_priority,
  status = excluded.status,
  progress_percent = excluded.progress_percent,
  mastery_score = excluded.mastery_score,
  first_seen_at = excluded.first_seen_at,
  last_seen_at = excluded.last_seen_at,
  last_reviewed_at = excluded.last_reviewed_at,
  seen_count = excluded.seen_count,
  strong_event_count = excluded.strong_event_count,
  review_count = excluded.review_count,
  correct_count = excluded.correct_count,
  wrong_count = excluded.wrong_count,
  consecutive_correct = excluded.consecutive_correct,
  consecutive_wrong = excluded.consecutive_wrong,
  last_quality = excluded.last_quality,
  recent_quality_window = excluded.recent_quality_window,
  recent_correctness_window = excluded.recent_correctness_window,
  repetition = excluded.repetition,
  interval_days = excluded.interval_days,
  ease_factor = excluded.ease_factor,
  next_review_at = excluded.next_review_at,
  suspended_reason = excluded.suspended_reason,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at
`

type UpsertUserUnitStateParams struct {
	UserID                  pgtype.UUID
	CoarseUnitID            int64
	IsTarget                bool
	TargetSource            pgtype.Text
	TargetSourceRefID       pgtype.Text
	TargetPriority          pgtype.Numeric
	Status                  string
	ProgressPercent         pgtype.Numeric
	MasteryScore            pgtype.Numeric
	FirstSeenAt             pgtype.Timestamptz
	LastSeenAt              pgtype.Timestamptz
	LastReviewedAt          pgtype.Timestamptz
	SeenCount               int32
	StrongEventCount        int32
	ReviewCount             int32
	CorrectCount            int32
	WrongCount              int32
	ConsecutiveCorrect      int32
	ConsecutiveWrong        int32
	LastQuality             pgtype.Int2
	RecentQualityWindow     []int16
	RecentCorrectnessWindow []bool
	Repetition              int32
	IntervalDays            pgtype.Numeric
	EaseFactor              pgtype.Numeric
	NextReviewAt            pgtype.Timestamptz
	SuspendedReason         pgtype.Text
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

func (q *Queries) UpsertUserUnitState(ctx context.Context, arg UpsertUserUnitStateParams) error {
	_, err := q.db.Exec(ctx, upsertUserUnitState,
		arg.UserID,
		arg.CoarseUnitID,
		arg.IsTarget,
		arg.TargetSource,
		arg.TargetSourceRefID,
		arg.TargetPriority,
		arg.Status,
		arg.ProgressPercent,
		arg.MasteryScore,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.LastReviewedAt,
		arg.SeenCount,
		arg.StrongEventCount,
		arg.ReviewCount,
		arg.CorrectCount,
		arg.WrongCount,
		arg.ConsecutiveCorrect,
		arg.ConsecutiveWrong,
		arg.LastQuality,
		arg.RecentQualityWindow,
		arg.RecentCorrectnessWindow,
		arg.Repetition,
		arg.IntervalDays,
		arg.EaseFactor,
		arg.NextReviewAt,
		arg.SuspendedReason,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
