// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: unit_learning_events.sql

package learningenginesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendLearningEvent = `-- name: AppendLearningEvent :one
insert into learning.unit_learning_events (
  user_id,
  coarse_unit_id,
  video_id,
  event_type,
  source_type,
  source_ref_id,
  is_correct,
  quality,
  response_time_ms,
  metadata,
  occurred_at
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11
)
returning event_id, user_id, coarse_unit_id, video_id, event_type, source_type, source_ref_id, is_correct, quality, response_time_ms, metadata, occurred_at, created_at
`

type AppendLearningEventParams struct {
	UserID         pgtype.UUID        `json:"user_id"`
	CoarseUnitID   int64              `json:"coarse_unit_id"`
	VideoID        pgtype.UUID        `json:"video_id"`
	EventType      string             `json:"event_type"`
	SourceType     string             `json:"source_type"`
	SourceRefID    pgtype.Text        `json:"source_ref_id"`
	IsCorrect      pgtype.Bool        `json:"is_correct"`
	Quality        pgtype.Int2        `json:"quality"`
	ResponseTimeMs pgtype.Int4        `json:"response_time_ms"`
	Metadata       []byte             `json:"metadata"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) AppendLearningEvent(ctx context.Context, arg AppendLearningEventParams) (LearningUnitLearningEvent, error) {
	row := q.db.QueryRow(ctx, appendLearningEvent,
		arg.UserID,
		arg.CoarseUnitID,
		arg.VideoID,
		arg.EventType,
		arg.SourceType,
		arg.SourceRefID,
		arg.IsCorrect,
		arg.Quality,
		arg.ResponseTimeMs,
		arg.Metadata,
		arg.OccurredAt,
	)
	var i LearningUnitLearningEvent
	err := row.Scan(
		&i.EventID,
		&i.UserID,
		&i.CoarseUnitID,
		&i.VideoID,
		&i.EventType,
		&i.SourceType,
		&i.SourceRefID,
		&i.IsCorrect,
		&i.Quality,
		&i.ResponseTimeMs,
		&i.Metadata,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listLearningEventsByUserOrdered = `-- name: ListLearningEventsByUserOrdered :many
select event_id, user_id, coarse_unit_id, video_id, event_type, source_type, source_ref_id, is_correct, quality, response_time_ms, metadata, occurred_at, created_at
from learning.unit_learning_events
where user_id = $1
order by occurred_at asc, event_id asc
`

func (q *Queries) ListLearningEventsByUserOrdered(ctx context.Context, userID pgtype.UUID) ([]LearningUnitLearningEvent, error) {
	rows, err := q.db.Query(ctx, listLearningEventsByUserOrdered, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningUnitLearningEvent{}
	for rows.Next() {
		var i LearningUnitLearningEvent
		if err := rows.Scan(
			&i.EventID,
			&i.UserID,
			&i.CoarseUnitID,
			&i.VideoID,
			&i.EventType,
			&i.SourceType,
			&i.SourceRefID,
			&i.IsCorrect,
			&i.Quality,
			&i.ResponseTimeMs,
			&i.Metadata,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningEventsByUserUnitOrdered = `-- name: ListLearningEventsByUserUnitOrdered :many
select event_id, user_id, coarse_unit_id, video_id, event_type, source_type, source_ref_id, is_correct, quality, response_time_ms, metadata, occurred_at, created_at
from learning.unit_learning_events
where user_id = $1
  and coarse_unit_id = $2
order by occurred_at asc, event_id asc
`

type ListLearningEventsByUserUnitOrderedParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	CoarseUnitID int64       `json:"coarse_unit_id"`
}

func (q *Queries) ListLearningEventsByUserUnitOrdered(ctx context.Context, arg ListLearningEventsByUserUnitOrderedParams) ([]LearningUnitLearningEvent, error) {
	rows, err := q.db.Query(ctx, listLearningEventsByUserUnitOrdered, arg.UserID, arg.CoarseUnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningUnitLearningEvent{}
	for rows.Next() {
		var i LearningUnitLearningEvent
		if err := rows.Scan(
			&i.EventID,
			&i.UserID,
			&i.CoarseUnitID,
			&i.VideoID,
			&i.EventType,
			&i.SourceType,
			&i.SourceRefID,
			&i.IsCorrect,
			&i.Quality,
			&i.ResponseTimeMs,
			&i.Metadata,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
