// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: unit_events.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnitLearningEvents = `-- name: CountUnitLearningEvents :one
select count(*)::bigint
from learning.unit_learning_events
`

func (q *Queries) CountUnitLearningEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnitLearningEvents)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertUnitLearningEvent = `-- name: InsertUnitLearningEvent :exec
insert into learning.unit_learning_events (
  user_id,
  coarse_unit_id,
  video_id,
  event_type,
  source_type,
  source_ref_id,
  is_correct,
  quality,
  response_time_ms,
  metadata,
  occurred_at,
  created_at
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12
)
`

type InsertUnitLearningEventParams struct {
	UserID         pgtype.UUID
	CoarseUnitID   int64
	VideoID        pgtype.UUID
	EventType      string
	SourceType     string
	SourceRefID    pgtype.Text
	IsCorrect      pgtype.Bool
	Quality        pgtype.Int2
	ResponseTimeMs pgtype.Int4
	Metadata       []byte
	OccurredAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertUnitLearningEvent(ctx context.Context, arg InsertUnitLearningEventParams) error {
	_, err := q.db.Exec(ctx, insertUnitLearningEvent,
		arg.UserID,
		arg.CoarseUnitID,
		arg.VideoID,
		arg.EventType,
		arg.SourceType,
		arg.SourceRefID,
		arg.IsCorrect,
		arg.Quality,
		arg.ResponseTimeMs,
		arg.Metadata,
		arg.OccurredAt,
		arg.CreatedAt,
	)
	return err
}

const listUnitLearningEventsByUserOrdered = `-- name: ListUnitLearningEventsByUserOrdered :many
select event_id, user_id, coarse_unit_id, video_id, event_type, source_type, source_ref_id, is_correct, quality, response_time_ms, metadata, occurred_at, created_at
from learning.unit_learning_events
where user_id = $1
order by occurred_at asc, event_id asc
`

func (q *Queries) ListUnitLearningEventsByUserOrdered(ctx context.Context, userID pgtype.UUID) ([]LearningUnitLearningEvent, error) {
	rows, err := q.db.Query(ctx, listUnitLearningEventsByUserOrdered, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningUnitLearningEvent
	for rows.Next() {
		var i LearningUnitLearningEvent
		if err := rows.Scan(
			&i.EventID,
			&i.UserID,
			&i.CoarseUnitID,
			&i.VideoID,
			&i.EventType,
			&i.SourceType,
			&i.SourceRefID,
			&i.IsCorrect,
			&i.Quality,
			&i.ResponseTimeMs,
			&i.Metadata,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
