// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_unit_states.sql

package learningenginesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserUnitStatesByUser = `-- name: DeleteUserUnitStatesByUser :exec
delete from learning.user_unit_states
where user_id = $1
`

func (q *Queries) DeleteUserUnitStatesByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserUnitStatesByUser, userID)
	return err
}

const ensureTargetUnit = `-- name: EnsureTargetUnit :exec
insert into learning.user_unit_states (
  user_id,
  coarse_unit_id,
  is_target,
  target_source,
  target_source_ref_id,
  target_priority
) values (
  $1,
  $2,
  true,
  $3,
  $4,
  $5
)
on conflict (user_id, coarse_unit_id) do update
set
  is_target = true,
  target_source = excluded.target_source,
  target_source_ref_id = excluded.target_source_ref_id,
  target_priority = excluded.target_priority,
  updated_at = now()
`

type EnsureTargetUnitParams struct {
	UserID            pgtype.UUID    `json:"user_id"`
	CoarseUnitID      int64          `json:"coarse_unit_id"`
	TargetSource      pgtype.Text    `json:"target_source"`
	TargetSourceRefID pgtype.Text    `json:"target_source_ref_id"`
	TargetPriority    pgtype.Numeric `json:"target_priority"`
}

func (q *Queries) EnsureTargetUnit(ctx context.Context, arg EnsureTargetUnitParams) error {
	_, err := q.db.Exec(ctx, ensureTargetUnit,
		arg.UserID,
		arg.CoarseUnitID,
		arg.TargetSource,
		arg.TargetSourceRefID,
		arg.TargetPriority,
	)
	return err
}

const getUserUnitStateForUpdate = `-- name: GetUserUnitStateForUpdate :one
select user_id, coarse_unit_id, is_target, target_source, target_source_ref_id, target_priority, status, progress_percent, mastery_score, first_seen_at, last_seen_at, last_reviewed_at, seen_count, strong_event_count, review_count, correct_count, wrong_count, consecutive_correct, consecutive_wrong, last_quality, recent_quality_window, recent_correctness_window, repetition, interval_days, ease_factor, next_review_at, suspended_reason, created_at, updated_at
from learning.user_unit_states
where user_id = $1
  and coarse_unit_id = $2
for update
`

type GetUserUnitStateForUpdateParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	CoarseUnitID int64       `json:"coarse_unit_id"`
}

func (q *Queries) GetUserUnitStateForUpdate(ctx context.Context, arg GetUserUnitStateForUpdateParams) (LearningUserUnitState, error) {
	row := q.db.QueryRow(ctx, getUserUnitStateForUpdate, arg.UserID, arg.CoarseUnitID)
	var i LearningUserUnitState
	err := row.Scan(
		&i.UserID,
		&i.CoarseUnitID,
		&i.IsTarget,
		&i.TargetSource,
		&i.TargetSourceRefID,
		&i.TargetPriority,
		&i.Status,
		&i.ProgressPercent,
		&i.MasteryScore,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.LastReviewedAt,
		&i.SeenCount,
		&i.StrongEventCount,
		&i.ReviewCount,
		&i.CorrectCount,
		&i.WrongCount,
		&i.ConsecutiveCorrect,
		&i.ConsecutiveWrong,
		&i.LastQuality,
		&i.RecentQualityWindow,
		&i.RecentCorrectnessWindow,
		&i.Repetition,
		&i.IntervalDays,
		&i.EaseFactor,
		&i.NextReviewAt,
		&i.SuspendedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserUnitStates = `-- name: ListUserUnitStates :many
select user_id, coarse_unit_id, is_target, target_source, target_source_ref_id, target_priority, status, progress_percent, mastery_score, first_seen_at, last_seen_at, last_reviewed_at, seen_count, strong_event_count, review_count, correct_count, wrong_count, consecutive_correct, consecutive_wrong, last_quality, recent_quality_window, recent_correctness_window, repetition, interval_days, ease_factor, next_review_at, suspended_reason, created_at, updated_at
from learning.user_unit_states
where user_id = $1
  and (not $2::boolean or is_target = true)
  and (not $3::boolean or status <> 'suspended')
order by coarse_unit_id asc
`

type ListUserUnitStatesParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	OnlyTarget       bool        `json:"only_target"`
	ExcludeSuspended bool        `json:"exclude_suspended"`
}

func (q *Queries) ListUserUnitStates(ctx context.Context, arg ListUserUnitStatesParams) ([]LearningUserUnitState, error) {
	rows, err := q.db.Query(ctx, listUserUnitStates, arg.UserID, arg.OnlyTarget, arg.ExcludeSuspended)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningUserUnitState{}
	for rows.Next() {
		var i LearningUserUnitState
		if err := rows.Scan(
			&i.UserID,
			&i.CoarseUnitID,
			&i.IsTarget,
			&i.TargetSource,
			&i.TargetSourceRefID,
			&i.TargetPriority,
			&i.Status,
			&i.ProgressPercent,
			&i.MasteryScore,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.LastReviewedAt,
			&i.SeenCount,
			&i.StrongEventCount,
			&i.ReviewCount,
			&i.CorrectCount,
			&i.WrongCount,
			&i.ConsecutiveCorrect,
			&i.ConsecutiveWrong,
			&i.LastQuality,
			&i.RecentQualityWindow,
			&i.RecentCorrectnessWindow,
			&i.Repetition,
			&i.IntervalDays,
			&i.EaseFactor,
			&i.NextReviewAt,
			&i.SuspendedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTargetInactive = `-- name: SetTargetInactive :exec
update learning.user_unit_states
set
  is_target = false,
  updated_at = now()
where user_id = $1
  and coarse_unit_id = $2
`

type SetTargetInactiveParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	CoarseUnitID int64       `json:"coarse_unit_id"`
}

func (q *Queries) SetTargetInactive(ctx context.Context, arg SetTargetInactiveParams) error {
	_, err := q.db.Exec(ctx, setTargetInactive, arg.UserID, arg.CoarseUnitID)
	return err
}

const upsertUserUnitState = `-- name: UpsertUserUnitState :one
insert into learning.user_unit_states (
  user_id,
  coarse_unit_id,
  is_target,
  target_source,
  target_source_ref_id,
  target_priority,
  status,
  progress_percent,
  mastery_score,
  first_seen_at,
  last_seen_at,
  last_reviewed_at,
  seen_count,
  strong_event_count,
  review_count,
  correct_count,
  wrong_count,
  consecutive_correct,
  consecutive_wrong,
  last_quality,
  recent_quality_window,
  recent_correctness_window,
  repetition,
  interval_days,
  ease_factor,
  next_review_at,
  suspended_reason,
  updated_at
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $21,
  $22,
  $23,
  $24,
  $25,
  $26,
  $27,
  now()
)
on conflict (user_id, coarse_unit_id) do update
set
  is_target = excluded.is_target,
  target_source = excluded.target_source,
  target_source_ref_id = excluded.target_source_ref_id,
  target_priority = excluded.target_priority,
  status = excluded.status,
  progress_percent = excluded.progress_percent,
  mastery_score = excluded.mastery_score,
  first_seen_at = excluded.first_seen_at,
  last_seen_at = excluded.last_seen_at,
  last_reviewed_at = excluded.last_reviewed_at,
  seen_count = excluded.seen_count,
  strong_event_count = excluded.strong_event_count,
  review_count = excluded.review_count,
  correct_count = excluded.correct_count,
  wrong_count = excluded.wrong_count,
  consecutive_correct = excluded.consecutive_correct,
  consecutive_wrong = excluded.consecutive_wrong,
  last_quality = excluded.last_quality,
  recent_quality_window = excluded.recent_quality_window,
  recent_correctness_window = excluded.recent_correctness_window,
  repetition = excluded.repetition,
  interval_days = excluded.interval_days,
  ease_factor = excluded.ease_factor,
  next_review_at = excluded.next_review_at,
  suspended_reason = excluded.suspended_reason,
  updated_at = now()
returning user_id, coarse_unit_id, is_target, target_source, target_source_ref_id, target_priority, status, progress_percent, mastery_score, first_seen_at, last_seen_at, last_reviewed_at, seen_count, strong_event_count, review_count, correct_count, wrong_count, consecutive_correct, consecutive_wrong, last_quality, recent_quality_window, recent_correctness_window, repetition, interval_days, ease_factor, next_review_at, suspended_reason, created_at, updated_at
`

type UpsertUserUnitStateParams struct {
	UserID                  pgtype.UUID        `json:"user_id"`
	CoarseUnitID            int64              `json:"coarse_unit_id"`
	IsTarget                bool               `json:"is_target"`
	TargetSource            pgtype.Text        `json:"target_source"`
	TargetSourceRefID       pgtype.Text        `json:"target_source_ref_id"`
	TargetPriority          pgtype.Numeric     `json:"target_priority"`
	Status                  string             `json:"status"`
	ProgressPercent         pgtype.Numeric     `json:"progress_percent"`
	MasteryScore            pgtype.Numeric     `json:"mastery_score"`
	FirstSeenAt             pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt              pgtype.Timestamptz `json:"last_seen_at"`
	LastReviewedAt          pgtype.Timestamptz `json:"last_reviewed_at"`
	SeenCount               int32              `json:"seen_count"`
	StrongEventCount        int32              `json:"strong_event_count"`
	ReviewCount             int32              `json:"review_count"`
	CorrectCount            int32              `json:"correct_count"`
	WrongCount              int32              `json:"wrong_count"`
	ConsecutiveCorrect      int32              `json:"consecutive_correct"`
	ConsecutiveWrong        int32              `json:"consecutive_wrong"`
	LastQuality             pgtype.Int2        `json:"last_quality"`
	RecentQualityWindow     []int16            `json:"recent_quality_window"`
	RecentCorrectnessWindow []bool             `json:"recent_correctness_window"`
	Repetition              int32              `json:"repetition"`
	IntervalDays            pgtype.Numeric     `json:"interval_days"`
	EaseFactor              pgtype.Numeric     `json:"ease_factor"`
	NextReviewAt            pgtype.Timestamptz `json:"next_review_at"`
	SuspendedReason         pgtype.Text        `json:"suspended_reason"`
}

func (q *Queries) UpsertUserUnitState(ctx context.Context, arg UpsertUserUnitStateParams) (LearningUserUnitState, error) {
	row := q.db.QueryRow(ctx, upsertUserUnitState,
		arg.UserID,
		arg.CoarseUnitID,
		arg.IsTarget,
		arg.TargetSource,
		arg.TargetSourceRefID,
		arg.TargetPriority,
		arg.Status,
		arg.ProgressPercent,
		arg.MasteryScore,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.LastReviewedAt,
		arg.SeenCount,
		arg.StrongEventCount,
		arg.ReviewCount,
		arg.CorrectCount,
		arg.WrongCount,
		arg.ConsecutiveCorrect,
		arg.ConsecutiveWrong,
		arg.LastQuality,
		arg.RecentQualityWindow,
		arg.RecentCorrectnessWindow,
		arg.Repetition,
		arg.IntervalDays,
		arg.EaseFactor,
		arg.NextReviewAt,
		arg.SuspendedReason,
	)
	var i LearningUserUnitState
	err := row.Scan(
		&i.UserID,
		&i.CoarseUnitID,
		&i.IsTarget,
		&i.TargetSource,
		&i.TargetSourceRefID,
		&i.TargetPriority,
		&i.Status,
		&i.ProgressPercent,
		&i.MasteryScore,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.LastReviewedAt,
		&i.SeenCount,
		&i.StrongEventCount,
		&i.ReviewCount,
		&i.CorrectCount,
		&i.WrongCount,
		&i.ConsecutiveCorrect,
		&i.ConsecutiveWrong,
		&i.LastQuality,
		&i.RecentQualityWindow,
		&i.RecentCorrectnessWindow,
		&i.Repetition,
		&i.IntervalDays,
		&i.EaseFactor,
		&i.NextReviewAt,
		&i.SuspendedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
