// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_stats.sql

package usersqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWatchDuration = `-- name: AddWatchDuration :exec
with stats as (
  insert into app_user.user_activity_stats (
    user_id,
    total_watch_ms,
    updated_at
  ) values (
    $1,
    greatest($4::bigint, 0),
    now()
  )
  on conflict (user_id) do update set
    total_watch_ms = app_user.user_activity_stats.total_watch_ms + greatest($4::bigint, 0),
    updated_at = now()
)
insert into app_user.user_daily_activity_stats (
  user_id,
  local_date,
  timezone,
  watch_ms,
  first_activity_at,
  last_activity_at,
  updated_at
) values (
  $1,
  $2::date,
  $3,
  greatest($4::bigint, 0),
  $5,
  $5,
  now()
)
on conflict (user_id, local_date) do update set
  timezone = excluded.timezone,
  watch_ms = app_user.user_daily_activity_stats.watch_ms + excluded.watch_ms,
  first_activity_at = least(coalesce(app_user.user_daily_activity_stats.first_activity_at, excluded.first_activity_at), excluded.first_activity_at),
  last_activity_at = greatest(coalesce(app_user.user_daily_activity_stats.last_activity_at, excluded.last_activity_at), excluded.last_activity_at),
  updated_at = now()
`

type AddWatchDurationParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	LocalDate    pgtype.Date        `json:"local_date"`
	Timezone     string             `json:"timezone"`
	DeltaWatchMs int64              `json:"delta_watch_ms"`
	ActivityAt   pgtype.Timestamptz `json:"activity_at"`
}

func (q *Queries) AddWatchDuration(ctx context.Context, arg AddWatchDurationParams) error {
	_, err := q.db.Exec(ctx, addWatchDuration,
		arg.UserID,
		arg.LocalDate,
		arg.Timezone,
		arg.DeltaWatchMs,
		arg.ActivityAt,
	)
	return err
}

const incrementLearningInteraction = `-- name: IncrementLearningInteraction :exec
insert into app_user.user_daily_activity_stats (
  user_id,
  local_date,
  timezone,
  learning_interaction_count,
  first_activity_at,
  last_activity_at,
  updated_at
) values (
  $1,
  $2::date,
  $3,
  1,
  $4,
  $4,
  now()
)
on conflict (user_id, local_date) do update set
  timezone = excluded.timezone,
  learning_interaction_count = app_user.user_daily_activity_stats.learning_interaction_count + 1,
  first_activity_at = least(coalesce(app_user.user_daily_activity_stats.first_activity_at, excluded.first_activity_at), excluded.first_activity_at),
  last_activity_at = greatest(coalesce(app_user.user_daily_activity_stats.last_activity_at, excluded.last_activity_at), excluded.last_activity_at),
  updated_at = now()
`

type IncrementLearningInteractionParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	LocalDate  pgtype.Date        `json:"local_date"`
	Timezone   string             `json:"timezone"`
	ActivityAt pgtype.Timestamptz `json:"activity_at"`
}

func (q *Queries) IncrementLearningInteraction(ctx context.Context, arg IncrementLearningInteractionParams) error {
	_, err := q.db.Exec(ctx, incrementLearningInteraction,
		arg.UserID,
		arg.LocalDate,
		arg.Timezone,
		arg.ActivityAt,
	)
	return err
}

const incrementQuizAttempt = `-- name: IncrementQuizAttempt :exec
with stats as (
  insert into app_user.user_activity_stats (
    user_id,
    quiz_attempt_count,
    updated_at
  ) values (
    $1,
    1,
    now()
  )
  on conflict (user_id) do update set
    quiz_attempt_count = app_user.user_activity_stats.quiz_attempt_count + 1,
    updated_at = now()
)
insert into app_user.user_daily_activity_stats (
  user_id,
  local_date,
  timezone,
  quiz_attempt_count,
  first_activity_at,
  last_activity_at,
  updated_at
) values (
  $1,
  $2::date,
  $3,
  1,
  $4,
  $4,
  now()
)
on conflict (user_id, local_date) do update set
  timezone = excluded.timezone,
  quiz_attempt_count = app_user.user_daily_activity_stats.quiz_attempt_count + 1,
  first_activity_at = least(coalesce(app_user.user_daily_activity_stats.first_activity_at, excluded.first_activity_at), excluded.first_activity_at),
  last_activity_at = greatest(coalesce(app_user.user_daily_activity_stats.last_activity_at, excluded.last_activity_at), excluded.last_activity_at),
  updated_at = now()
`

type IncrementQuizAttemptParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	LocalDate  pgtype.Date        `json:"local_date"`
	Timezone   string             `json:"timezone"`
	ActivityAt pgtype.Timestamptz `json:"activity_at"`
}

func (q *Queries) IncrementQuizAttempt(ctx context.Context, arg IncrementQuizAttemptParams) error {
	_, err := q.db.Exec(ctx, incrementQuizAttempt,
		arg.UserID,
		arg.LocalDate,
		arg.Timezone,
		arg.ActivityAt,
	)
	return err
}

const incrementStartedUnit = `-- name: IncrementStartedUnit :exec
insert into app_user.user_activity_stats (
  user_id,
  started_unit_count,
  updated_at
) values (
  $1,
  1,
  now()
)
on conflict (user_id) do update set
  started_unit_count = app_user.user_activity_stats.started_unit_count + 1,
  updated_at = now()
`

func (q *Queries) IncrementStartedUnit(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementStartedUnit, userID)
	return err
}
