// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feedback.sql

package usersqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFeedbackImages = `-- name: CountFeedbackImages :one
select count(*)::integer
from app_user.feedback_images
where submission_id = $1
`

func (q *Queries) CountFeedbackImages(ctx context.Context, submissionID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countFeedbackImages, submissionID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertFeedbackImage = `-- name: InsertFeedbackImage :exec
insert into app_user.feedback_images (
  id,
  submission_id,
  sort_order,
  content_type,
  size_bytes,
  sha256,
  width,
  height,
  image_data
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
`

type InsertFeedbackImageParams struct {
	ID           pgtype.UUID `json:"id"`
	SubmissionID pgtype.UUID `json:"submission_id"`
	SortOrder    int32       `json:"sort_order"`
	ContentType  string      `json:"content_type"`
	SizeBytes    int32       `json:"size_bytes"`
	Sha256       string      `json:"sha256"`
	Width        int32       `json:"width"`
	Height       int32       `json:"height"`
	ImageData    []byte      `json:"image_data"`
}

func (q *Queries) InsertFeedbackImage(ctx context.Context, arg InsertFeedbackImageParams) error {
	_, err := q.db.Exec(ctx, insertFeedbackImage,
		arg.ID,
		arg.SubmissionID,
		arg.SortOrder,
		arg.ContentType,
		arg.SizeBytes,
		arg.Sha256,
		arg.Width,
		arg.Height,
		arg.ImageData,
	)
	return err
}

const upsertFeedbackSubmission = `-- name: UpsertFeedbackSubmission :one
insert into app_user.feedback_submissions (
  id,
  user_id,
  client_feedback_id,
  payload
) values (
  $1,
  $2,
  $3,
  $4
)
on conflict (user_id, client_feedback_id) do update
set client_feedback_id = excluded.client_feedback_id
returning id, created_at, (xmax = 0) as inserted
`

type UpsertFeedbackSubmissionParams struct {
	ID               pgtype.UUID `json:"id"`
	UserID           pgtype.UUID `json:"user_id"`
	ClientFeedbackID pgtype.UUID `json:"client_feedback_id"`
	Payload          []byte      `json:"payload"`
}

type UpsertFeedbackSubmissionRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Inserted  bool               `json:"inserted"`
}

func (q *Queries) UpsertFeedbackSubmission(ctx context.Context, arg UpsertFeedbackSubmissionParams) (UpsertFeedbackSubmissionRow, error) {
	row := q.db.QueryRow(ctx, upsertFeedbackSubmission,
		arg.ID,
		arg.UserID,
		arg.ClientFeedbackID,
		arg.Payload,
	)
	var i UpsertFeedbackSubmissionRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Inserted)
	return i, err
}
