// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: legal_documents.sql

package usersqlc

import (
	"context"
)

const getLegalDocument = `-- name: GetLegalDocument :one
select
  document_type,
  title,
  markdown,
  version,
  updated_at
from app_user.legal_documents
where document_type = $1
`

func (q *Queries) GetLegalDocument(ctx context.Context, documentType string) (AppUserLegalDocument, error) {
	row := q.db.QueryRow(ctx, getLegalDocument, documentType)
	var i AppUserLegalDocument
	err := row.Scan(
		&i.DocumentType,
		&i.Title,
		&i.Markdown,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}
