// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package usersqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppUserFeedbackImage struct {
	ID           pgtype.UUID        `json:"id"`
	SubmissionID pgtype.UUID        `json:"submission_id"`
	SortOrder    int32              `json:"sort_order"`
	ContentType  string             `json:"content_type"`
	SizeBytes    int32              `json:"size_bytes"`
	Sha256       string             `json:"sha256"`
	Width        int32              `json:"width"`
	Height       int32              `json:"height"`
	ImageData    []byte             `json:"image_data"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AppUserFeedbackSubmission struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	ClientFeedbackID pgtype.UUID        `json:"client_feedback_id"`
	Payload          []byte             `json:"payload"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type AppUserUserActivityStat struct {
	UserID           pgtype.UUID        `json:"user_id"`
	TotalWatchMs     int64              `json:"total_watch_ms"`
	QuizAttemptCount int64              `json:"quiz_attempt_count"`
	StartedUnitCount int64              `json:"started_unit_count"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type AppUserUserDailyActivityStat struct {
	UserID                   pgtype.UUID        `json:"user_id"`
	LocalDate                pgtype.Date        `json:"local_date"`
	Timezone                 string             `json:"timezone"`
	WatchMs                  int64              `json:"watch_ms"`
	QuizAttemptCount         int64              `json:"quiz_attempt_count"`
	LearningInteractionCount int64              `json:"learning_interaction_count"`
	FirstActivityAt          pgtype.Timestamptz `json:"first_activity_at"`
	LastActivityAt           pgtype.Timestamptz `json:"last_activity_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type AppUserUserProfile struct {
	UserID           pgtype.UUID        `json:"user_id"`
	Email            pgtype.Text        `json:"email"`
	EmailConfirmedAt pgtype.Timestamptz `json:"email_confirmed_at"`
	DisplayName      pgtype.Text        `json:"display_name"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	Locale           string             `json:"locale"`
	Timezone         pgtype.Text        `json:"timezone"`
	OnboardingStatus string             `json:"onboarding_status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type AuthUser struct {
	ID               pgtype.UUID        `json:"id"`
	Email            pgtype.Text        `json:"email"`
	EmailConfirmedAt pgtype.Timestamptz `json:"email_confirmed_at"`
}
