// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package usersqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddWatchDuration(ctx context.Context, arg AddWatchDurationParams) error
	EnsureActivityStats(ctx context.Context, userID pgtype.UUID) error
	GetActivityStats(ctx context.Context, userID pgtype.UUID) (AppUserUserActivityStat, error)
	GetAuthUser(ctx context.Context, id pgtype.UUID) (AuthUser, error)
	GetCurrentActivityStreakDays(ctx context.Context, arg GetCurrentActivityStreakDaysParams) (int64, error)
	GetUserProfile(ctx context.Context, userID pgtype.UUID) (AppUserUserProfile, error)
	IncrementLearningInteraction(ctx context.Context, arg IncrementLearningInteractionParams) error
	IncrementQuizAttempt(ctx context.Context, arg IncrementQuizAttemptParams) error
	IncrementStartedUnit(ctx context.Context, userID pgtype.UUID) error
	InsertRepairedUserProfile(ctx context.Context, arg InsertRepairedUserProfileParams) (AppUserUserProfile, error)
	ListDailyActivityStats(ctx context.Context, arg ListDailyActivityStatsParams) ([]AppUserUserDailyActivityStat, error)
	UpdateOnboardingStatus(ctx context.Context, arg UpdateOnboardingStatusParams) error
	UpdateUserTimezone(ctx context.Context, arg UpdateUserTimezoneParams) error
}

var _ Querier = (*Queries)(nil)
