// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_profiles.sql

package usersqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureActivityStats = `-- name: EnsureActivityStats :exec
insert into app_user.user_activity_stats (user_id)
values ($1)
on conflict (user_id) do nothing
`

func (q *Queries) EnsureActivityStats(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureActivityStats, userID)
	return err
}

const getActivityStats = `-- name: GetActivityStats :one
select user_id, total_watch_ms, quiz_attempt_count, started_unit_count, updated_at
from app_user.user_activity_stats
where user_id = $1
`

func (q *Queries) GetActivityStats(ctx context.Context, userID pgtype.UUID) (AppUserUserActivityStat, error) {
	row := q.db.QueryRow(ctx, getActivityStats, userID)
	var i AppUserUserActivityStat
	err := row.Scan(
		&i.UserID,
		&i.TotalWatchMs,
		&i.QuizAttemptCount,
		&i.StartedUnitCount,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthUser = `-- name: GetAuthUser :one
select id, email, email_confirmed_at
from auth.users
where id = $1
`

func (q *Queries) GetAuthUser(ctx context.Context, id pgtype.UUID) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getAuthUser, id)
	var i AuthUser
	err := row.Scan(&i.ID, &i.Email, &i.EmailConfirmedAt)
	return i, err
}

const getCurrentActivityStreakDays = `-- name: GetCurrentActivityStreakDays :one
with recursive anchor as (
  select candidate.local_date
  from (
    select $1::date as local_date
    union all
    select ($1::date - 1)::date as local_date
  ) candidate
  where exists (
    select 1
    from app_user.user_daily_activity_stats s
    where s.user_id = $2
      and s.local_date = candidate.local_date
      and (
        s.watch_ms > 0
        or s.quiz_attempt_count > 0
        or s.learning_interaction_count > 0
      )
  )
  order by candidate.local_date desc
  limit 1
),
streak(local_date) as (
  select local_date
  from anchor
  union all
  select (streak.local_date - 1)::date
  from streak
  where exists (
    select 1
    from app_user.user_daily_activity_stats s
    where s.user_id = $2
      and s.local_date = (streak.local_date - 1)::date
      and (
        s.watch_ms > 0
        or s.quiz_attempt_count > 0
        or s.learning_interaction_count > 0
      )
  )
)
select count(*)::bigint
from streak
`

type GetCurrentActivityStreakDaysParams struct {
	Today  pgtype.Date `json:"today"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetCurrentActivityStreakDays(ctx context.Context, arg GetCurrentActivityStreakDaysParams) (int64, error) {
	row := q.db.QueryRow(ctx, getCurrentActivityStreakDays, arg.Today, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserProfile = `-- name: GetUserProfile :one
select user_id, email, email_confirmed_at, display_name, avatar_url, locale, timezone, onboarding_status, birth_date, gender, education_stage, ip_region, created_at, updated_at
from app_user.user_profiles
where user_id = $1
`

type GetUserProfileRow struct {
	UserID           pgtype.UUID        `json:"user_id"`
	Email            pgtype.Text        `json:"email"`
	EmailConfirmedAt pgtype.Timestamptz `json:"email_confirmed_at"`
	DisplayName      string             `json:"display_name"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	Locale           string             `json:"locale"`
	Timezone         pgtype.Text        `json:"timezone"`
	OnboardingStatus string             `json:"onboarding_status"`
	BirthDate        pgtype.Date        `json:"birth_date"`
	Gender           pgtype.Text        `json:"gender"`
	EducationStage   pgtype.Text        `json:"education_stage"`
	IpRegion         pgtype.Text        `json:"ip_region"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserProfile(ctx context.Context, userID pgtype.UUID) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, userID)
	var i GetUserProfileRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.EmailConfirmedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Locale,
		&i.Timezone,
		&i.OnboardingStatus,
		&i.BirthDate,
		&i.Gender,
		&i.EducationStage,
		&i.IpRegion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRepairedUserProfile = `-- name: InsertRepairedUserProfile :one
insert into app_user.user_profiles (
  user_id,
  email,
  email_confirmed_at,
  display_name,
  locale,
  onboarding_status
) values (
  $1,
  $2,
  $3,
  coalesce(nullif(split_part(coalesce($2::text, ''), '@', 1), ''), 'user'),
  'zh-CN',
  'new'
)
on conflict (user_id) do nothing
returning user_id, email, email_confirmed_at, display_name, avatar_url, locale, timezone, onboarding_status, birth_date, gender, education_stage, ip_region, created_at, updated_at
`

type InsertRepairedUserProfileParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	Email            pgtype.Text        `json:"email"`
	EmailConfirmedAt pgtype.Timestamptz `json:"email_confirmed_at"`
}

type InsertRepairedUserProfileRow struct {
	UserID           pgtype.UUID        `json:"user_id"`
	Email            pgtype.Text        `json:"email"`
	EmailConfirmedAt pgtype.Timestamptz `json:"email_confirmed_at"`
	DisplayName      string             `json:"display_name"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	Locale           string             `json:"locale"`
	Timezone         pgtype.Text        `json:"timezone"`
	OnboardingStatus string             `json:"onboarding_status"`
	BirthDate        pgtype.Date        `json:"birth_date"`
	Gender           pgtype.Text        `json:"gender"`
	EducationStage   pgtype.Text        `json:"education_stage"`
	IpRegion         pgtype.Text        `json:"ip_region"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertRepairedUserProfile(ctx context.Context, arg InsertRepairedUserProfileParams) (InsertRepairedUserProfileRow, error) {
	row := q.db.QueryRow(ctx, insertRepairedUserProfile, arg.UserID, arg.Email, arg.EmailConfirmedAt)
	var i InsertRepairedUserProfileRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.EmailConfirmedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Locale,
		&i.Timezone,
		&i.OnboardingStatus,
		&i.BirthDate,
		&i.Gender,
		&i.EducationStage,
		&i.IpRegion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDailyActivityStats = `-- name: ListDailyActivityStats :many
select user_id, local_date, timezone, watch_ms, quiz_attempt_count, learning_interaction_count, first_activity_at, last_activity_at, updated_at
from app_user.user_daily_activity_stats
where user_id = $1
  and local_date between $2::date and $3::date
order by local_date asc
`

type ListDailyActivityStatsParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

func (q *Queries) ListDailyActivityStats(ctx context.Context, arg ListDailyActivityStatsParams) ([]AppUserUserDailyActivityStat, error) {
	rows, err := q.db.Query(ctx, listDailyActivityStats, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppUserUserDailyActivityStat{}
	for rows.Next() {
		var i AppUserUserDailyActivityStat
		if err := rows.Scan(
			&i.UserID,
			&i.LocalDate,
			&i.Timezone,
			&i.WatchMs,
			&i.QuizAttemptCount,
			&i.LearningInteractionCount,
			&i.FirstActivityAt,
			&i.LastActivityAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOnboardingStatus = `-- name: UpdateOnboardingStatus :exec
update app_user.user_profiles
set onboarding_status = $1,
    updated_at = now()
where user_id = $2
`

type UpdateOnboardingStatusParams struct {
	OnboardingStatus string      `json:"onboarding_status"`
	UserID           pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateOnboardingStatus(ctx context.Context, arg UpdateOnboardingStatusParams) error {
	_, err := q.db.Exec(ctx, updateOnboardingStatus, arg.OnboardingStatus, arg.UserID)
	return err
}

const updateUserTimezone = `-- name: UpdateUserTimezone :exec
update app_user.user_profiles
set timezone = $1,
    updated_at = now()
where user_id = $2
  and timezone is distinct from $1
`

type UpdateUserTimezoneParams struct {
	Timezone pgtype.Text `json:"timezone"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateUserTimezone(ctx context.Context, arg UpdateUserTimezoneParams) error {
	_, err := q.db.Exec(ctx, updateUserTimezone, arg.Timezone, arg.UserID)
	return err
}
